/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct Ident {
    uint8_t* name;
    uint64_t len;
};

struct Span {
    uint64_t start;
    uint64_t end;
};

struct Type {
    struct TypeKind* kind;
    struct Ident* name;
    struct Type** inner;
    bool is_mut;
    uint64_t size;
    struct Span* span;
};

struct Literal {
    struct LitKind* kind;
    int64_t int_val;
    bool bool_val;
    uint8_t* str_ptr;
    uint64_t str_len;
};

struct Expr {
    struct ExprKind* kind;
    struct Span* span;
    struct Literal* lit;
    struct Ident* name;
    struct BinOp* bin_op;
    struct Expr** left;
    struct Expr** right;
    struct UnOp* un_op;
    struct Expr** operand;
    struct Expr** callee;
    struct ExprList** args;
    struct Expr** object;
    struct Ident* field;
    struct Expr** cond;
    struct Block** then_block;
    struct Block** else_block;
    struct Block** body;
};

struct Stmt {
    struct StmtKind* kind;
    struct Span* span;
    struct Ident* let_name;
    struct Type** let_type;
    struct Expr** let_value;
    bool is_mut;
    struct Expr** expr;
    struct Expr** ret_value;
};

struct Block {
    struct StmtList** stmts;
    struct Span* span;
};

struct Param {
    struct Ident* name;
    struct Type* ty;
    struct Span* span;
};

struct Function {
    struct Ident* name;
    struct ParamList** params;
    struct Type** ret_type;
    struct Block* body;
    bool is_pub;
    struct Span* span;
};

struct StructField {
    struct Ident* name;
    struct Type* ty;
    bool is_pub;
};

struct StructDef {
    struct Ident* name;
    struct FieldList** fields;
    bool is_pub;
    struct Span* span;
};

struct EnumVariant {
    struct Ident* name;
    struct Span* span;
};

struct EnumDef {
    struct Ident* name;
    struct VariantList** variants;
    bool is_pub;
    struct Span* span;
};

struct ImplBlock {
    struct Ident* target;
    struct FunctionList** methods;
    struct Span* span;
};

struct ExternFn {
    struct Ident* name;
    struct ParamList** params;
    struct Type** ret_type;
    struct Span* span;
};

struct ExternBlock {
    uint8_t* abi;
    struct ExternFnList** items;
    struct Span* span;
};

struct Item {
    struct ItemKind* kind;
    struct Function* func;
    struct StructDef* struct_def;
    struct EnumDef* enum_def;
    struct ImplBlock* impl_block;
    struct ExternBlock* extern_block;
};

struct Program {
    struct ItemList** items;
};

struct ExprList {
    struct Expr** data;
    uint64_t len;
    uint64_t cap;
};

struct StmtList {
    struct Stmt** data;
    uint64_t len;
    uint64_t cap;
};

struct ParamList {
    struct Param** data;
    uint64_t len;
    uint64_t cap;
};

struct FieldList {
    struct StructField** data;
    uint64_t len;
    uint64_t cap;
};

struct VariantList {
    struct EnumVariant** data;
    uint64_t len;
    uint64_t cap;
};

struct FunctionList {
    struct Function** data;
    uint64_t len;
    uint64_t cap;
};

struct ExternFnList {
    struct ExternFn** data;
    uint64_t len;
    uint64_t cap;
};

struct ItemList {
    struct Item** data;
    uint64_t len;
    uint64_t cap;
};

void Ident_new(struct Ident*, uint8_t*, uint64_t);
void Span_new(struct Span*, uint64_t, uint64_t);
void Span_dummy(struct Span*);
void Type_new_named(struct Type*, struct Ident*);
void Type_new_unit(struct Type*);
void Literal_new_int(struct Literal*, int64_t);
void Literal_new_bool(struct Literal*, bool);
void main(void);

void Ident_new(struct Ident* _arg0, uint8_t* _arg1, uint64_t _arg2) {
    struct Ident* _t0;
    uint64_t _t2;
    uint64_t* _t4;
    uint8_t* _t1;
    uint8_t** _t3;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = &_t0->name;
    *_t3 = _t1;
    _t4 = &_t0->len;
    *_t4 = _t2;
    return;
}

void Span_new(struct Span* _arg0, uint64_t _arg1, uint64_t _arg2) {
    struct Span* _t0;
    uint64_t _t1;
    uint64_t _t2;
    uint64_t* _t3;
    uint64_t* _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = &_t0->start;
    *_t3 = _t1;
    _t4 = &_t0->end;
    *_t4 = _t2;
    return;
}

void Span_dummy(struct Span* _arg0) {
    struct Span* _t0;
    uint64_t* _t1;
    uint64_t* _t2;
    
    _t0 = _arg0;
    _t1 = &_t0->start;
    *_t1 = 0LL;
    _t2 = &_t0->end;
    *_t2 = 0LL;
    return;
}

void Type_new_named(struct Type* _arg0, struct Ident* _arg1) {
    bool* _t6;
    struct Ident* _t1;
    struct Ident** _t3;
    struct Span* _t8;
    struct Span** _t9;
    struct Type* _t0;
    struct Type** _t4;
    struct Type*** _t5;
    struct TypeKind** _t2;
    uint64_t* _t7;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = &_t0->kind;
    *_t2 = TypeKind_Named;
    _t3 = &_t0->name;
    *_t3 = _t1;
    _t4 = (struct Type**)0LL;
    _t5 = &_t0->inner;
    *_t5 = _t4;
    _t6 = &_t0->is_mut;
    *_t6 = 0;
    _t7 = &_t0->size;
    *_t7 = 0LL;
    struct Span _alloca__t8;
    _t8 = &_alloca__t8;
    Span_dummy(_t8);
    _t9 = &_t0->span;
    *_t9 = _t8;
    return;
}

void Type_new_unit(struct Type* _arg0) {
    bool* _t7;
    struct Ident* _t3;
    struct Ident** _t4;
    struct Span* _t9;
    struct Span** _t10;
    struct Type* _t0;
    struct Type** _t5;
    struct Type*** _t6;
    struct TypeKind** _t1;
    uint64_t* _t8;
    uint8_t* _t2;
    
    _t0 = _arg0;
    _t1 = &_t0->kind;
    *_t1 = TypeKind_Unit;
    _t2 = (uint8_t*)0LL;
    struct Ident _alloca__t3;
    _t3 = &_alloca__t3;
    Ident_new(_t3, _t2, 0LL);
    _t4 = &_t0->name;
    *_t4 = _t3;
    _t5 = (struct Type**)0LL;
    _t6 = &_t0->inner;
    *_t6 = _t5;
    _t7 = &_t0->is_mut;
    *_t7 = 0;
    _t8 = &_t0->size;
    *_t8 = 0LL;
    struct Span _alloca__t9;
    _t9 = &_alloca__t9;
    Span_dummy(_t9);
    _t10 = &_t0->span;
    *_t10 = _t9;
    return;
}

void Literal_new_int(struct Literal* _arg0, int64_t _arg1) {
    bool* _t4;
    int64_t _t1;
    int64_t* _t3;
    struct LitKind** _t2;
    struct Literal* _t0;
    uint64_t* _t7;
    uint8_t* _t5;
    uint8_t** _t6;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = &_t0->kind;
    *_t2 = LitKind_Int;
    _t3 = &_t0->int_val;
    *_t3 = _t1;
    _t4 = &_t0->bool_val;
    *_t4 = 0;
    _t5 = (uint8_t*)0LL;
    _t6 = &_t0->str_ptr;
    *_t6 = _t5;
    _t7 = &_t0->str_len;
    *_t7 = 0LL;
    return;
}

void Literal_new_bool(struct Literal* _arg0, bool _arg1) {
    bool _t1;
    bool* _t4;
    int64_t* _t3;
    struct LitKind** _t2;
    struct Literal* _t0;
    uint64_t* _t7;
    uint8_t* _t5;
    uint8_t** _t6;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = &_t0->kind;
    *_t2 = LitKind_Bool;
    _t3 = &_t0->int_val;
    *_t3 = 0LL;
    _t4 = &_t0->bool_val;
    *_t4 = _t1;
    _t5 = (uint8_t*)0LL;
    _t6 = &_t0->str_ptr;
    *_t6 = _t5;
    _t7 = &_t0->str_len;
    *_t7 = 0LL;
    return;
}

void main(void) {
    int64_t _t0;
    
    puts("AST types defined!");
    return;
}

