/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct TargetInfo {
    struct TargetArch* arch;
    uint8_t* triple;
    uint64_t pointer_size;
};

struct LLVMTypeHandle {
    uint64_t id;
};

struct LLVMValueHandle {
    uint64_t id;
};

struct LLVMBlockHandle {
    uint64_t id;
};

struct CodeGen {
    struct TargetInfo* target;
    uint8_t* module_name;
    uint64_t next_value_id;
    uint64_t next_block_id;
    uint64_t current_function;
    uint64_t current_block;
    uint8_t* llvm_module;
    uint8_t* llvm_builder;
    uint8_t* llvm_context;
};

void TargetInfo_native(struct TargetInfo*);
void TargetInfo_x86_64(struct TargetInfo*);
void LLVMTypeHandle_new(struct LLVMTypeHandle*, uint64_t);
void LLVMValueHandle_new(struct LLVMValueHandle*, uint64_t);
void LLVMBlockHandle_new(struct LLVMBlockHandle*, uint64_t);
void CodeGen_new(struct CodeGen*, uint8_t*);
void CodeGen_init_targets(void);
void CodeGen_declare_builtins(struct CodeGen*);
uint8_t* CodeGen_ir_type_to_llvm(struct CodeGen*, uint8_t);
bool CodeGen_generate(struct CodeGen*);
bool CodeGen_generate_function(struct CodeGen*);
bool CodeGen_generate_block(struct CodeGen*);
void CodeGen_generate_instruction(struct LLVMValueHandle*, struct CodeGen*);
uint8_t* CodeGen_generate_binop_ffi(struct CodeGen*, uint8_t, uint8_t*, uint8_t*);
void CodeGen_generate_binop(struct LLVMValueHandle*, struct CodeGen*);
uint8_t* CodeGen_generate_load_ffi(struct CodeGen*, uint8_t*, uint8_t*);
void CodeGen_generate_load(struct LLVMValueHandle*, struct CodeGen*);
uint8_t* CodeGen_generate_store_ffi(struct CodeGen*, uint8_t*, uint8_t*);
void CodeGen_generate_store(struct LLVMValueHandle*, struct CodeGen*);
uint8_t* CodeGen_generate_alloca_ffi(struct CodeGen*, uint8_t*);
void CodeGen_generate_alloca(struct LLVMValueHandle*, struct CodeGen*);
uint8_t* CodeGen_generate_call_ffi(struct CodeGen*, uint8_t*, uint8_t*, uint8_t**, uint32_t);
void CodeGen_generate_call(struct LLVMValueHandle*, struct CodeGen*);
uint8_t* CodeGen_generate_gep_ffi(struct CodeGen*, uint8_t*, uint8_t*, uint32_t);
void CodeGen_generate_gep(struct LLVMValueHandle*, struct CodeGen*);
uint8_t* CodeGen_generate_cast_ffi(struct CodeGen*, uint8_t*, uint8_t*);
void CodeGen_generate_cast(struct LLVMValueHandle*, struct CodeGen*);
bool CodeGen_generate_terminator(struct CodeGen*);
bool CodeGen_generate_return(struct CodeGen*);
bool CodeGen_generate_branch(struct CodeGen*);
bool CodeGen_generate_cond_branch(struct CodeGen*);
void CodeGen_get_value(struct LLVMValueHandle*, struct CodeGen*, uint64_t);
bool CodeGen_verify_module(struct CodeGen*);
bool CodeGen_emit_object(struct CodeGen*);
void CodeGen_print_ir(struct CodeGen*);
uint64_t CodeGen_alloc_value(struct CodeGen*);
uint64_t CodeGen_alloc_block(struct CodeGen*);
uint8_t* CodeGen_target_triple(struct CodeGen*);
uint8_t* CodeGen_name(struct CodeGen*);
void main(void);

void TargetInfo_native(struct TargetInfo* _arg0) {
    struct TargetArch** _t1;
    struct TargetInfo* _t0;
    uint64_t* _t4;
    uint8_t* _t2;
    uint8_t** _t3;
    
    _t0 = _arg0;
    _t1 = &_t0->arch;
    *_t1 = TargetArch_AArch64;
    _t2 = (uint8_t*)"aarch64-apple-darwin";
    _t3 = &_t0->triple;
    *_t3 = _t2;
    _t4 = &_t0->pointer_size;
    *_t4 = 8LL;
    return;
}

void TargetInfo_x86_64(struct TargetInfo* _arg0) {
    struct TargetArch** _t1;
    struct TargetInfo* _t0;
    uint64_t* _t4;
    uint8_t* _t2;
    uint8_t** _t3;
    
    _t0 = _arg0;
    _t1 = &_t0->arch;
    *_t1 = TargetArch_X86_64;
    _t2 = (uint8_t*)"x86_64-unknown-linux-gnu";
    _t3 = &_t0->triple;
    *_t3 = _t2;
    _t4 = &_t0->pointer_size;
    *_t4 = 8LL;
    return;
}

void LLVMTypeHandle_new(struct LLVMTypeHandle* _arg0, uint64_t _arg1) {
    struct LLVMTypeHandle* _t0;
    uint64_t _t1;
    uint64_t* _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = &_t0->id;
    *_t2 = _t1;
    return;
}

void LLVMValueHandle_new(struct LLVMValueHandle* _arg0, uint64_t _arg1) {
    struct LLVMValueHandle* _t0;
    uint64_t _t1;
    uint64_t* _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = &_t0->id;
    *_t2 = _t1;
    return;
}

void LLVMBlockHandle_new(struct LLVMBlockHandle* _arg0, uint64_t _arg1) {
    struct LLVMBlockHandle* _t0;
    uint64_t _t1;
    uint64_t* _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = &_t0->id;
    *_t2 = _t1;
    return;
}

void CodeGen_new(struct CodeGen* _arg0, uint8_t* _arg1) {
    int64_t _t2;
    int64_t _t3;
    int64_t _t4;
    int64_t _t5;
    int64_t _t6;
    int64_t _t7;
    struct CodeGen* _t0;
    struct TargetInfo* _t8;
    struct TargetInfo** _t9;
    uint64_t* _t11;
    uint64_t* _t12;
    uint64_t* _t13;
    uint64_t* _t14;
    uint8_t* _t1;
    uint8_t** _t10;
    uint8_t** _t15;
    uint8_t** _t16;
    uint8_t** _t17;
    
    _t0 = _arg0;
    _t1 = _arg1;
    LLVMModuleCreateWithName(_t1);
    _t3 = _t2;
    LLVMCreateBuilder();
    _t5 = _t4;
    LLVMGetGlobalContext();
    _t7 = _t6;
    struct TargetInfo _alloca__t8;
    _t8 = &_alloca__t8;
    TargetInfo_native(_t8);
    _t9 = &_t0->target;
    *_t9 = _t8;
    _t10 = &_t0->module_name;
    *_t10 = _t1;
    _t11 = &_t0->next_value_id;
    *_t11 = 0LL;
    _t12 = &_t0->next_block_id;
    *_t12 = 0LL;
    _t13 = &_t0->current_function;
    *_t13 = 0LL;
    _t14 = &_t0->current_block;
    *_t14 = 0LL;
    _t15 = &_t0->llvm_module;
    *_t15 = _t3;
    _t16 = &_t0->llvm_builder;
    *_t16 = _t5;
    _t17 = &_t0->llvm_context;
    *_t17 = _t7;
    return;
}

void CodeGen_init_targets(void) {
    
    return;
}

void CodeGen_declare_builtins(struct CodeGen* _arg0) {
    int32_t _t9;
    int64_t _t10;
    int64_t _t11;
    int64_t _t15;
    int64_t _t1;
    int64_t _t2;
    int64_t _t3;
    int64_t _t5;
    int64_t _t6;
    struct CodeGen* _t0;
    uint32_t _t4;
    uint32_t _t8;
    uint8_t* _t13;
    uint8_t* _t14;
    uint8_t** _t12;
    uint8_t** _t7;
    
    _t0 = _arg0;
    LLVMInt32Type();
    _t2 = _t1;
    LLVMInt8Type();
    _t4 = (uint32_t)0LL;
    LLVMPointerType(_t3, _t4);
    _t6 = _t5;
    _t7 = (uint8_t**)((void)0);
    _t8 = (uint32_t)1LL;
    _t9 = (int32_t)0LL;
    LLVMFunctionType(_t2, _t7, _t8, _t9);
    _t11 = _t10;
    _t12 = &_t0->llvm_module;
    _t13 = *_t12;
    _t14 = (uint8_t*)"puts";
    LLVMAddFunction(_t13, _t14, _t11);
    return;
}

uint8_t* CodeGen_ir_type_to_llvm(struct CodeGen* _arg0, uint8_t _arg1) {
    int64_t _t11;
    int64_t _t12;
    int64_t _t13;
    int64_t _t14;
    int64_t _t16;
    int64_t _t18;
    int64_t _t19;
    int64_t _t20;
    int64_t _t22;
    int64_t _t24;
    int64_t _t25;
    int64_t _t26;
    int64_t _t28;
    int64_t _t29;
    int64_t _t31;
    int64_t _t32;
    int64_t _t34;
    int64_t _t35;
    int64_t _t37;
    int64_t _t3;
    int64_t _t5;
    int64_t _t6;
    int64_t _t7;
    int64_t _t9;
    struct CodeGen* _t0;
    uint32_t _t36;
    uint8_t _t10;
    uint8_t _t15;
    uint8_t _t17;
    uint8_t _t1;
    uint8_t _t21;
    uint8_t _t23;
    uint8_t _t27;
    uint8_t _t2;
    uint8_t _t30;
    uint8_t _t33;
    uint8_t _t4;
    uint8_t _t8;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t)0LL;
    _t3 = _t1 == _t2;
    _t4 = (uint8_t)4LL;
    _t5 = _t1 == _t4;
    _t6 = _t3 || _t5;
    if (_t6) goto L_then; else goto L_else;
L_then:
    LLVMInt8Type();
    return _t7;
L_else:
    _t8 = (uint8_t)1LL;
    _t9 = _t1 == _t8;
    _t10 = (uint8_t)5LL;
    _t11 = _t1 == _t10;
    _t12 = _t9 || _t11;
    if (_t12) goto L_then; else goto L_else;
L_merge:
    LLVMInt64Type();
    return _t13;
L_then:
    LLVMInt16Type();
    return _t14;
L_else:
    _t15 = (uint8_t)2LL;
    _t16 = _t1 == _t15;
    _t17 = (uint8_t)6LL;
    _t18 = _t1 == _t17;
    _t19 = _t16 || _t18;
    if (_t19) goto L_then; else goto L_else;
L_merge:
    goto L_merge;
L_then:
    LLVMInt32Type();
    return _t20;
L_else:
    _t21 = (uint8_t)3LL;
    _t22 = _t1 == _t21;
    _t23 = (uint8_t)7LL;
    _t24 = _t1 == _t23;
    _t25 = _t22 || _t24;
    if (_t25) goto L_then; else goto L_else;
L_merge:
    goto L_merge;
L_then:
    LLVMInt64Type();
    return _t26;
L_else:
    _t27 = (uint8_t)8LL;
    _t28 = _t1 == _t27;
    if (_t28) goto L_then; else goto L_else;
L_merge:
    goto L_merge;
L_then:
    LLVMInt1Type();
    return _t29;
L_else:
    _t30 = (uint8_t)9LL;
    _t31 = _t1 == _t30;
    if (_t31) goto L_then; else goto L_else;
L_merge:
    goto L_merge;
L_then:
    LLVMVoidType();
    return _t32;
L_else:
    _t33 = (uint8_t)10LL;
    _t34 = _t1 == _t33;
    if (_t34) goto L_then; else goto L_else;
L_merge:
    goto L_merge;
L_then:
    LLVMInt8Type();
    _t36 = (uint32_t)0LL;
    LLVMPointerType(_t35, _t36);
    return _t37;
L_else:
    goto L_merge;
L_merge:
    goto L_merge;
}

bool CodeGen_generate(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    
    _t0 = _arg0;
    return 1;
}

bool CodeGen_generate_function(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    
    _t0 = _arg0;
    return 1;
}

bool CodeGen_generate_block(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    
    _t0 = _arg0;
    return 1;
}

void CodeGen_generate_instruction(struct LLVMValueHandle* _arg0, struct CodeGen* _arg1) {
    struct CodeGen* _t1;
    struct LLVMValueHandle* _t0;
    struct LLVMValueHandle* _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    struct LLVMValueHandle _alloca__t2;
    _t2 = &_alloca__t2;
    LLVMValueHandle_new(_t2, 0LL);
    return;
}

uint8_t* CodeGen_generate_binop_ffi(struct CodeGen* _arg0, uint8_t _arg1, uint8_t* _arg2, uint8_t* _arg3) {
    int64_t _t10;
    int64_t _t12;
    int64_t _t15;
    int64_t _t18;
    int64_t _t20;
    int64_t _t23;
    int64_t _t25;
    int64_t _t28;
    int64_t _t7;
    struct CodeGen* _t0;
    uint8_t _t11;
    uint8_t _t19;
    uint8_t _t1;
    uint8_t _t24;
    uint8_t _t6;
    uint8_t* _t14;
    uint8_t* _t17;
    uint8_t* _t22;
    uint8_t* _t27;
    uint8_t* _t2;
    uint8_t* _t3;
    uint8_t* _t4;
    uint8_t* _t5;
    uint8_t* _t9;
    uint8_t** _t13;
    uint8_t** _t16;
    uint8_t** _t21;
    uint8_t** _t26;
    uint8_t** _t8;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = _arg3;
    _t4 = (uint8_t*)"binop";
    _t5 = _t4;
    _t6 = (uint8_t)0LL;
    _t7 = _t1 == _t6;
    if (_t7) goto L_then; else goto L_else;
L_then:
    _t8 = &_t0->llvm_builder;
    _t9 = *_t8;
    LLVMBuildAdd(_t9, _t2, _t3, _t5);
    return _t10;
L_else:
    _t11 = (uint8_t)1LL;
    _t12 = _t1 == _t11;
    if (_t12) goto L_then; else goto L_else;
L_merge:
    _t13 = &_t0->llvm_builder;
    _t14 = *_t13;
    LLVMBuildAdd(_t14, _t2, _t3, _t5);
    return _t15;
L_then:
    _t16 = &_t0->llvm_builder;
    _t17 = *_t16;
    LLVMBuildSub(_t17, _t2, _t3, _t5);
    return _t18;
L_else:
    _t19 = (uint8_t)2LL;
    _t20 = _t1 == _t19;
    if (_t20) goto L_then; else goto L_else;
L_merge:
    goto L_merge;
L_then:
    _t21 = &_t0->llvm_builder;
    _t22 = *_t21;
    LLVMBuildMul(_t22, _t2, _t3, _t5);
    return _t23;
L_else:
    _t24 = (uint8_t)3LL;
    _t25 = _t1 == _t24;
    if (_t25) goto L_then; else goto L_else;
L_merge:
    goto L_merge;
L_then:
    _t26 = &_t0->llvm_builder;
    _t27 = *_t26;
    LLVMBuildSDiv(_t27, _t2, _t3, _t5);
    return _t28;
L_else:
    goto L_merge;
L_merge:
    goto L_merge;
}

void CodeGen_generate_binop(struct LLVMValueHandle* _arg0, struct CodeGen* _arg1) {
    struct CodeGen* _t1;
    struct LLVMValueHandle* _t0;
    struct LLVMValueHandle* _t4;
    uint64_t _t2;
    uint64_t _t3;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = CodeGen_alloc_value(_t1);
    _t3 = _t2;
    struct LLVMValueHandle _alloca__t4;
    _t4 = &_alloca__t4;
    LLVMValueHandle_new(_t4, _t3);
    return;
}

uint8_t* CodeGen_generate_load_ffi(struct CodeGen* _arg0, uint8_t* _arg1, uint8_t* _arg2) {
    int64_t _t6;
    struct CodeGen* _t0;
    uint8_t* _t1;
    uint8_t* _t2;
    uint8_t* _t4;
    uint8_t* _t5;
    uint8_t** _t3;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = &_t0->llvm_builder;
    _t4 = *_t3;
    _t5 = (uint8_t*)"load";
    LLVMBuildLoad2(_t4, _t1, _t2, _t5);
    return _t6;
}

void CodeGen_generate_load(struct LLVMValueHandle* _arg0, struct CodeGen* _arg1) {
    struct CodeGen* _t1;
    struct LLVMValueHandle* _t0;
    struct LLVMValueHandle* _t4;
    uint64_t _t2;
    uint64_t _t3;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = CodeGen_alloc_value(_t1);
    _t3 = _t2;
    struct LLVMValueHandle _alloca__t4;
    _t4 = &_alloca__t4;
    LLVMValueHandle_new(_t4, _t3);
    return;
}

uint8_t* CodeGen_generate_store_ffi(struct CodeGen* _arg0, uint8_t* _arg1, uint8_t* _arg2) {
    int64_t _t5;
    struct CodeGen* _t0;
    uint8_t* _t1;
    uint8_t* _t2;
    uint8_t* _t4;
    uint8_t** _t3;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = &_t0->llvm_builder;
    _t4 = *_t3;
    LLVMBuildStore(_t4, _t1, _t2);
    return _t5;
}

void CodeGen_generate_store(struct LLVMValueHandle* _arg0, struct CodeGen* _arg1) {
    struct CodeGen* _t1;
    struct LLVMValueHandle* _t0;
    struct LLVMValueHandle* _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    struct LLVMValueHandle _alloca__t2;
    _t2 = &_alloca__t2;
    LLVMValueHandle_new(_t2, 0LL);
    return;
}

uint8_t* CodeGen_generate_alloca_ffi(struct CodeGen* _arg0, uint8_t* _arg1) {
    int64_t _t5;
    struct CodeGen* _t0;
    uint8_t* _t1;
    uint8_t* _t3;
    uint8_t* _t4;
    uint8_t** _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = &_t0->llvm_builder;
    _t3 = *_t2;
    _t4 = (uint8_t*)"alloca";
    LLVMBuildAlloca(_t3, _t1, _t4);
    return _t5;
}

void CodeGen_generate_alloca(struct LLVMValueHandle* _arg0, struct CodeGen* _arg1) {
    struct CodeGen* _t1;
    struct LLVMValueHandle* _t0;
    struct LLVMValueHandle* _t4;
    uint64_t _t2;
    uint64_t _t3;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = CodeGen_alloc_value(_t1);
    _t3 = _t2;
    struct LLVMValueHandle _alloca__t4;
    _t4 = &_alloca__t4;
    LLVMValueHandle_new(_t4, _t3);
    return;
}

uint8_t* CodeGen_generate_call_ffi(struct CodeGen* _arg0, uint8_t* _arg1, uint8_t* _arg2, uint8_t** _arg3, uint32_t _arg4) {
    int64_t _t8;
    struct CodeGen* _t0;
    uint32_t _t4;
    uint8_t* _t1;
    uint8_t* _t2;
    uint8_t* _t6;
    uint8_t* _t7;
    uint8_t** _t3;
    uint8_t** _t5;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = _arg3;
    _t4 = _arg4;
    _t5 = &_t0->llvm_builder;
    _t6 = *_t5;
    _t7 = (uint8_t*)"call";
    LLVMBuildCall2(_t6, _t1, _t2, _t3, _t4, _t7);
    return _t8;
}

void CodeGen_generate_call(struct LLVMValueHandle* _arg0, struct CodeGen* _arg1) {
    struct CodeGen* _t1;
    struct LLVMValueHandle* _t0;
    struct LLVMValueHandle* _t4;
    uint64_t _t2;
    uint64_t _t3;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = CodeGen_alloc_value(_t1);
    _t3 = _t2;
    struct LLVMValueHandle _alloca__t4;
    _t4 = &_alloca__t4;
    LLVMValueHandle_new(_t4, _t3);
    return;
}

uint8_t* CodeGen_generate_gep_ffi(struct CodeGen* _arg0, uint8_t* _arg1, uint8_t* _arg2, uint32_t _arg3) {
    int64_t _t7;
    struct CodeGen* _t0;
    uint32_t _t3;
    uint8_t* _t1;
    uint8_t* _t2;
    uint8_t* _t5;
    uint8_t* _t6;
    uint8_t** _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = _arg3;
    _t4 = &_t0->llvm_builder;
    _t5 = *_t4;
    _t6 = (uint8_t*)"gep";
    LLVMBuildStructGEP2(_t5, _t1, _t2, _t3, _t6);
    return _t7;
}

void CodeGen_generate_gep(struct LLVMValueHandle* _arg0, struct CodeGen* _arg1) {
    struct CodeGen* _t1;
    struct LLVMValueHandle* _t0;
    struct LLVMValueHandle* _t4;
    uint64_t _t2;
    uint64_t _t3;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = CodeGen_alloc_value(_t1);
    _t3 = _t2;
    struct LLVMValueHandle _alloca__t4;
    _t4 = &_alloca__t4;
    LLVMValueHandle_new(_t4, _t3);
    return;
}

uint8_t* CodeGen_generate_cast_ffi(struct CodeGen* _arg0, uint8_t* _arg1, uint8_t* _arg2) {
    int64_t _t6;
    struct CodeGen* _t0;
    uint8_t* _t1;
    uint8_t* _t2;
    uint8_t* _t4;
    uint8_t* _t5;
    uint8_t** _t3;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = &_t0->llvm_builder;
    _t4 = *_t3;
    _t5 = (uint8_t*)"cast";
    LLVMBuildIntCast(_t4, _t1, _t2, _t5);
    return _t6;
}

void CodeGen_generate_cast(struct LLVMValueHandle* _arg0, struct CodeGen* _arg1) {
    struct CodeGen* _t1;
    struct LLVMValueHandle* _t0;
    struct LLVMValueHandle* _t4;
    uint64_t _t2;
    uint64_t _t3;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = CodeGen_alloc_value(_t1);
    _t3 = _t2;
    struct LLVMValueHandle _alloca__t4;
    _t4 = &_alloca__t4;
    LLVMValueHandle_new(_t4, _t3);
    return;
}

bool CodeGen_generate_terminator(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    
    _t0 = _arg0;
    return 1;
}

bool CodeGen_generate_return(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    
    _t0 = _arg0;
    return 1;
}

bool CodeGen_generate_branch(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    
    _t0 = _arg0;
    return 1;
}

bool CodeGen_generate_cond_branch(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    
    _t0 = _arg0;
    return 1;
}

void CodeGen_get_value(struct LLVMValueHandle* _arg0, struct CodeGen* _arg1, uint64_t _arg2) {
    struct CodeGen* _t1;
    struct LLVMValueHandle* _t0;
    struct LLVMValueHandle* _t3;
    uint64_t _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    struct LLVMValueHandle _alloca__t3;
    _t3 = &_alloca__t3;
    LLVMValueHandle_new(_t3, 0LL);
    return;
}

bool CodeGen_verify_module(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    
    _t0 = _arg0;
    return 1;
}

bool CodeGen_emit_object(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    
    _t0 = _arg0;
    return 1;
}

void CodeGen_print_ir(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    
    _t0 = _arg0;
    return;
}

uint64_t CodeGen_alloc_value(struct CodeGen* _arg0) {
    int64_t _t9;
    struct CodeGen* _t0;
    uint64_t _t2;
    uint64_t _t3;
    uint64_t _t5;
    uint64_t _t7;
    uint64_t _t8;
    uint64_t* _t10;
    uint64_t* _t1;
    uint64_t* _t4;
    uint64_t* _t6;
    
    _t0 = _arg0;
    _t1 = &_t0->next_value_id;
    _t2 = *_t1;
    _t3 = _t2;
    _t4 = &_t0->next_value_id;
    _t5 = *_t4;
    _t6 = &_t0->next_value_id;
    _t7 = *_t6;
    _t8 = (uint64_t)1LL;
    _t9 = _t7 + _t8;
    _t10 = &_t0->next_value_id;
    *_t10 = _t9;
    return _t3;
}

uint64_t CodeGen_alloc_block(struct CodeGen* _arg0) {
    int64_t _t9;
    struct CodeGen* _t0;
    uint64_t _t2;
    uint64_t _t3;
    uint64_t _t5;
    uint64_t _t7;
    uint64_t _t8;
    uint64_t* _t10;
    uint64_t* _t1;
    uint64_t* _t4;
    uint64_t* _t6;
    
    _t0 = _arg0;
    _t1 = &_t0->next_block_id;
    _t2 = *_t1;
    _t3 = _t2;
    _t4 = &_t0->next_block_id;
    _t5 = *_t4;
    _t6 = &_t0->next_block_id;
    _t7 = *_t6;
    _t8 = (uint64_t)1LL;
    _t9 = _t7 + _t8;
    _t10 = &_t0->next_block_id;
    *_t10 = _t9;
    return _t3;
}

uint8_t* CodeGen_target_triple(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    struct TargetInfo* _t2;
    struct TargetInfo** _t1;
    uint8_t* _t4;
    uint8_t** _t3;
    
    _t0 = _arg0;
    _t1 = &_t0->target;
    _t2 = *_t1;
    _t3 = &_t2->triple;
    _t4 = *_t3;
    return _t4;
}

uint8_t* CodeGen_name(struct CodeGen* _arg0) {
    struct CodeGen* _t0;
    uint8_t* _t2;
    uint8_t** _t1;
    
    _t0 = _arg0;
    _t1 = &_t0->module_name;
    _t2 = *_t1;
    return _t2;
}

void main(void) {
    int64_t _t0;
    int64_t _t12;
    int64_t _t5;
    struct CodeGen* _t3;
    struct CodeGen* _t4;
    uint64_t _t6;
    uint64_t _t7;
    uint64_t _t8;
    uint64_t _t9;
    uint8_t* _t10;
    uint8_t* _t11;
    uint8_t* _t1;
    uint8_t* _t2;
    
    puts("Codegen defined!");
    _t1 = (uint8_t*)"test_module";
    _t2 = _t1;
    struct CodeGen _alloca__t3;
    _t3 = &_alloca__t3;
    CodeGen_new(_t3, _t2);
    _t4 = _t3;
    CodeGen_declare_builtins(_t4);
    puts("Created codegen!");
    _t6 = CodeGen_alloc_value(_t4);
    _t7 = _t6;
    _t8 = CodeGen_alloc_block(_t4);
    _t9 = _t8;
    _t10 = CodeGen_ir_type_to_llvm(_t4, 0LL);
    _t11 = _t10;
    puts("Codegen self-hosting working!");
    return;
}

