/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct LLVMContext {
    void* ptr;
};

struct LLVMModule {
    void* ptr;
};

struct LLVMType {
    void* ptr;
};

struct LLVMBuilder {
    void* ptr;
};

struct LLVMValue {
    void* ptr;
};

struct LLVMBasicBlock {
    void* ptr;
};

void LLVMContext_create(struct LLVMContext*);
void LLVMContext_global(struct LLVMContext*);
void LLVMContext_dispose(struct LLVMContext**);
void* LLVMContext_raw(struct LLVMContext**);
void LLVMModule_create(struct LLVMModule*, uint8_t*, struct LLVMContext**);
void LLVMModule_dispose(struct LLVMModule**);
void LLVMModule_set_target(struct LLVMModule**, uint8_t*);
void LLVMModule_set_data_layout(struct LLVMModule**, uint8_t*);
uint8_t* LLVMModule_print_to_string(struct LLVMModule**);
bool LLVMModule_write_bitcode(struct LLVMModule**, uint8_t*);
void* LLVMModule_raw(struct LLVMModule**);
void LLVMType_void_type(struct LLVMType*, struct LLVMContext**);
void LLVMType_i1(struct LLVMType*, struct LLVMContext**);
void LLVMType_i8(struct LLVMType*, struct LLVMContext**);
void LLVMType_i16(struct LLVMType*, struct LLVMContext**);
void LLVMType_i32(struct LLVMType*, struct LLVMContext**);
void LLVMType_i64(struct LLVMType*, struct LLVMContext**);
void LLVMType_f32(struct LLVMType*, struct LLVMContext**);
void LLVMType_f64(struct LLVMType*, struct LLVMContext**);
void LLVMType_ptr(struct LLVMType*, struct LLVMType**);
void LLVMType_func(struct LLVMType*, struct LLVMType**, void**, uint32_t, bool);
void LLVMType_array(struct LLVMType*, struct LLVMType**, uint32_t);
void* LLVMType_raw(struct LLVMType**);
void LLVMBuilder_create(struct LLVMBuilder*, struct LLVMContext**);
void LLVMBuilder_dispose(struct LLVMBuilder**);
void LLVMBuilder_position_at_end(struct LLVMBuilder**, void*);
void* LLVMBuilder_raw(struct LLVMBuilder**);
void LLVMValue_from_ptr(struct LLVMValue*, void*);
void LLVMValue_const_int(struct LLVMValue*, struct LLVMType**, int64_t);
void LLVMValue_const_uint(struct LLVMValue*, struct LLVMType**, uint64_t);
void LLVMValue_const_real(struct LLVMValue*, struct LLVMType**, double);
void LLVMValue_const_null(struct LLVMValue*, struct LLVMType**);
bool LLVMValue_is_null(struct LLVMValue**);
void* LLVMValue_raw(struct LLVMValue**);
void LLVMBasicBlock_append(struct LLVMBasicBlock*, struct LLVMContext**, void*, uint8_t*);
void* LLVMBasicBlock_raw(struct LLVMBasicBlock**);
int32_t icmp_eq(void);
int32_t icmp_ne(void);
int32_t icmp_ugt(void);
int32_t icmp_uge(void);
int32_t icmp_ult(void);
int32_t icmp_ule(void);
int32_t icmp_sgt(void);
int32_t icmp_sge(void);
int32_t icmp_slt(void);
int32_t icmp_sle(void);
int32_t fcmp_oeq(void);
int32_t fcmp_ogt(void);
int32_t fcmp_oge(void);
int32_t fcmp_olt(void);
int32_t fcmp_ole(void);
int32_t fcmp_one(void);
int32_t verify_action_abort(void);
int32_t verify_action_print(void);
int32_t verify_action_return(void);
void llvm_init_all_targets(void);
uint8_t* llvm_default_triple(void);
int32_t opt_none(void);
int32_t opt_less(void);
int32_t opt_default(void);
int32_t opt_aggressive(void);
int32_t reloc_default(void);
int32_t reloc_static(void);
int32_t reloc_pic(void);
int32_t reloc_dynamic_no_pic(void);
int32_t code_model_default(void);
int32_t code_model_jit(void);
int32_t code_model_small(void);
int32_t code_model_kernel(void);
int32_t code_model_medium(void);
int32_t code_model_large(void);
int32_t codegen_asm(void);
int32_t codegen_obj(void);
int32_t main(void);

void LLVMContext_create(struct LLVMContext* _arg0) {
    int64_t _t1;
    int64_t _t2;
    struct LLVMContext* _t0;
    void** _t3;
    
    _t0 = _arg0;
    LLVMContextCreate();
    _t2 = _t1;
    _t3 = &_t0->ptr;
    *_t3 = _t2;
    return;
}

void LLVMContext_global(struct LLVMContext* _arg0) {
    int64_t _t1;
    int64_t _t2;
    struct LLVMContext* _t0;
    void** _t3;
    
    _t0 = _arg0;
    LLVMGetGlobalContext();
    _t2 = _t1;
    _t3 = &_t0->ptr;
    *_t3 = _t2;
    return;
}

void LLVMContext_dispose(struct LLVMContext** _arg0) {
    int64_t _t3;
    struct LLVMContext* _t1;
    struct LLVMContext* _t4;
    struct LLVMContext** _t0;
    void* _t2;
    
    _t0 = _arg0;
    _t1 = *_t0;
    _t2 = (void*)0LL;
    _t3 = ((void)0) != _t2;
    if (_t3) goto L_then; else goto L_else;
L_then:
    _t4 = *_t0;
    LLVMContextDispose(((void)0));
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    return;
}

void* LLVMContext_raw(struct LLVMContext** _arg0) {
    struct LLVMContext* _t1;
    struct LLVMContext** _t0;
    
    _t0 = _arg0;
    _t1 = *_t0;
    return ((void)0);
}

void LLVMModule_create(struct LLVMModule* _arg0, uint8_t* _arg1, struct LLVMContext** _arg2) {
    int64_t _t4;
    int64_t _t5;
    struct LLVMContext* _t3;
    struct LLVMContext** _t2;
    struct LLVMModule* _t0;
    uint8_t* _t1;
    void** _t6;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = *_t2;
    LLVMModuleCreateWithNameInContext(_t1, ((void)0));
    _t5 = _t4;
    _t6 = &_t0->ptr;
    *_t6 = _t5;
    return;
}

void LLVMModule_dispose(struct LLVMModule** _arg0) {
    int64_t _t3;
    struct LLVMModule* _t1;
    struct LLVMModule* _t4;
    struct LLVMModule** _t0;
    void* _t2;
    
    _t0 = _arg0;
    _t1 = *_t0;
    _t2 = (void*)0LL;
    _t3 = ((void)0) != _t2;
    if (_t3) goto L_then; else goto L_else;
L_then:
    _t4 = *_t0;
    LLVMDisposeModule(((void)0));
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    return;
}

void LLVMModule_set_target(struct LLVMModule** _arg0, uint8_t* _arg1) {
    struct LLVMModule* _t2;
    struct LLVMModule** _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t0;
    LLVMSetTarget(((void)0), _t1);
    return;
}

void LLVMModule_set_data_layout(struct LLVMModule** _arg0, uint8_t* _arg1) {
    struct LLVMModule* _t2;
    struct LLVMModule** _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t0;
    LLVMSetDataLayout(((void)0), _t1);
    return;
}

uint8_t* LLVMModule_print_to_string(struct LLVMModule** _arg0) {
    int64_t _t2;
    struct LLVMModule* _t1;
    struct LLVMModule** _t0;
    
    _t0 = _arg0;
    _t1 = *_t0;
    LLVMPrintModuleToString(((void)0));
    return _t2;
}

bool LLVMModule_write_bitcode(struct LLVMModule** _arg0, uint8_t* _arg1) {
    int32_t _t5;
    int64_t _t3;
    int64_t _t4;
    int64_t _t6;
    struct LLVMModule* _t2;
    struct LLVMModule** _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t0;
    LLVMWriteBitcodeToFile(((void)0), _t1);
    _t4 = _t3;
    _t5 = (int32_t)0LL;
    _t6 = _t4 == _t5;
    return _t6;
}

void* LLVMModule_raw(struct LLVMModule** _arg0) {
    struct LLVMModule* _t1;
    struct LLVMModule** _t0;
    
    _t0 = _arg0;
    _t1 = *_t0;
    return ((void)0);
}

void LLVMType_void_type(struct LLVMType* _arg0, struct LLVMContext** _arg1) {
    int64_t _t3;
    struct LLVMContext* _t2;
    struct LLVMContext** _t1;
    struct LLVMType* _t0;
    void** _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    LLVMVoidTypeInContext(((void)0));
    _t4 = &_t0->ptr;
    *_t4 = _t3;
    return;
}

void LLVMType_i1(struct LLVMType* _arg0, struct LLVMContext** _arg1) {
    int64_t _t3;
    struct LLVMContext* _t2;
    struct LLVMContext** _t1;
    struct LLVMType* _t0;
    void** _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    LLVMInt1TypeInContext(((void)0));
    _t4 = &_t0->ptr;
    *_t4 = _t3;
    return;
}

void LLVMType_i8(struct LLVMType* _arg0, struct LLVMContext** _arg1) {
    int64_t _t3;
    struct LLVMContext* _t2;
    struct LLVMContext** _t1;
    struct LLVMType* _t0;
    void** _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    LLVMInt8TypeInContext(((void)0));
    _t4 = &_t0->ptr;
    *_t4 = _t3;
    return;
}

void LLVMType_i16(struct LLVMType* _arg0, struct LLVMContext** _arg1) {
    int64_t _t3;
    struct LLVMContext* _t2;
    struct LLVMContext** _t1;
    struct LLVMType* _t0;
    void** _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    LLVMInt16TypeInContext(((void)0));
    _t4 = &_t0->ptr;
    *_t4 = _t3;
    return;
}

void LLVMType_i32(struct LLVMType* _arg0, struct LLVMContext** _arg1) {
    int64_t _t3;
    struct LLVMContext* _t2;
    struct LLVMContext** _t1;
    struct LLVMType* _t0;
    void** _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    LLVMInt32TypeInContext(((void)0));
    _t4 = &_t0->ptr;
    *_t4 = _t3;
    return;
}

void LLVMType_i64(struct LLVMType* _arg0, struct LLVMContext** _arg1) {
    int64_t _t3;
    struct LLVMContext* _t2;
    struct LLVMContext** _t1;
    struct LLVMType* _t0;
    void** _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    LLVMInt64TypeInContext(((void)0));
    _t4 = &_t0->ptr;
    *_t4 = _t3;
    return;
}

void LLVMType_f32(struct LLVMType* _arg0, struct LLVMContext** _arg1) {
    int64_t _t3;
    struct LLVMContext* _t2;
    struct LLVMContext** _t1;
    struct LLVMType* _t0;
    void** _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    LLVMFloatTypeInContext(((void)0));
    _t4 = &_t0->ptr;
    *_t4 = _t3;
    return;
}

void LLVMType_f64(struct LLVMType* _arg0, struct LLVMContext** _arg1) {
    int64_t _t3;
    struct LLVMContext* _t2;
    struct LLVMContext** _t1;
    struct LLVMType* _t0;
    void** _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    LLVMDoubleTypeInContext(((void)0));
    _t4 = &_t0->ptr;
    *_t4 = _t3;
    return;
}

void LLVMType_ptr(struct LLVMType* _arg0, struct LLVMType** _arg1) {
    int64_t _t4;
    struct LLVMType* _t0;
    struct LLVMType* _t2;
    struct LLVMType** _t1;
    uint32_t _t3;
    void** _t5;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    _t3 = (uint32_t)0LL;
    LLVMPointerType(((void)0), _t3);
    _t5 = &_t0->ptr;
    *_t5 = _t4;
    return;
}

void LLVMType_func(struct LLVMType* _arg0, struct LLVMType** _arg1, void** _arg2, uint32_t _arg3, bool _arg4) {
    bool _t4;
    int32_t _t8;
    int64_t _t5;
    int64_t _t6;
    int64_t _t9;
    struct LLVMType* _t0;
    struct LLVMType* _t7;
    struct LLVMType** _t1;
    uint32_t _t3;
    void** _t10;
    void** _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = _arg3;
    _t4 = _arg4;
    if (_t4) goto L_then; else goto L_else;
L_then:
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    _t5 = 1LL;
    _t6 = _t5;
    _t7 = *_t1;
    _t8 = (int32_t)_t6;
    LLVMFunctionType(((void)0), _t2, _t3, _t8);
    _t10 = &_t0->ptr;
    *_t10 = _t9;
    return;
}

void LLVMType_array(struct LLVMType* _arg0, struct LLVMType** _arg1, uint32_t _arg2) {
    int64_t _t4;
    struct LLVMType* _t0;
    struct LLVMType* _t3;
    struct LLVMType** _t1;
    uint32_t _t2;
    void** _t5;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = *_t1;
    LLVMArrayType(((void)0), _t2);
    _t5 = &_t0->ptr;
    *_t5 = _t4;
    return;
}

void* LLVMType_raw(struct LLVMType** _arg0) {
    struct LLVMType* _t1;
    struct LLVMType** _t0;
    
    _t0 = _arg0;
    _t1 = *_t0;
    return ((void)0);
}

void LLVMBuilder_create(struct LLVMBuilder* _arg0, struct LLVMContext** _arg1) {
    int64_t _t3;
    int64_t _t4;
    struct LLVMBuilder* _t0;
    struct LLVMContext* _t2;
    struct LLVMContext** _t1;
    void** _t5;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    LLVMCreateBuilderInContext(((void)0));
    _t4 = _t3;
    _t5 = &_t0->ptr;
    *_t5 = _t4;
    return;
}

void LLVMBuilder_dispose(struct LLVMBuilder** _arg0) {
    int64_t _t3;
    struct LLVMBuilder* _t1;
    struct LLVMBuilder* _t4;
    struct LLVMBuilder** _t0;
    void* _t2;
    
    _t0 = _arg0;
    _t1 = *_t0;
    _t2 = (void*)0LL;
    _t3 = ((void)0) != _t2;
    if (_t3) goto L_then; else goto L_else;
L_then:
    _t4 = *_t0;
    LLVMDisposeBuilder(((void)0));
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    return;
}

void LLVMBuilder_position_at_end(struct LLVMBuilder** _arg0, void* _arg1) {
    struct LLVMBuilder* _t2;
    struct LLVMBuilder** _t0;
    void* _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t0;
    LLVMPositionBuilderAtEnd(((void)0), _t1);
    return;
}

void* LLVMBuilder_raw(struct LLVMBuilder** _arg0) {
    struct LLVMBuilder* _t1;
    struct LLVMBuilder** _t0;
    
    _t0 = _arg0;
    _t1 = *_t0;
    return ((void)0);
}

void LLVMValue_from_ptr(struct LLVMValue* _arg0, void* _arg1) {
    struct LLVMValue* _t0;
    void* _t1;
    void** _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = &_t0->ptr;
    *_t2 = _t1;
    return;
}

void LLVMValue_const_int(struct LLVMValue* _arg0, struct LLVMType** _arg1, int64_t _arg2) {
    int32_t _t5;
    int64_t _t2;
    int64_t _t6;
    struct LLVMType* _t3;
    struct LLVMType** _t1;
    struct LLVMValue* _t0;
    uint64_t _t4;
    void** _t7;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = *_t1;
    _t4 = (uint64_t)_t2;
    _t5 = (int32_t)1LL;
    LLVMConstInt(((void)0), _t4, _t5);
    _t7 = &_t0->ptr;
    *_t7 = _t6;
    return;
}

void LLVMValue_const_uint(struct LLVMValue* _arg0, struct LLVMType** _arg1, uint64_t _arg2) {
    int32_t _t4;
    int64_t _t5;
    struct LLVMType* _t3;
    struct LLVMType** _t1;
    struct LLVMValue* _t0;
    uint64_t _t2;
    void** _t6;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = *_t1;
    _t4 = (int32_t)0LL;
    LLVMConstInt(((void)0), _t2, _t4);
    _t6 = &_t0->ptr;
    *_t6 = _t5;
    return;
}

void LLVMValue_const_real(struct LLVMValue* _arg0, struct LLVMType** _arg1, double _arg2) {
    double _t2;
    int64_t _t4;
    struct LLVMType* _t3;
    struct LLVMType** _t1;
    struct LLVMValue* _t0;
    void** _t5;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = *_t1;
    LLVMConstReal(((void)0), _t2);
    _t5 = &_t0->ptr;
    *_t5 = _t4;
    return;
}

void LLVMValue_const_null(struct LLVMValue* _arg0, struct LLVMType** _arg1) {
    int64_t _t3;
    struct LLVMType* _t2;
    struct LLVMType** _t1;
    struct LLVMValue* _t0;
    void** _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t1;
    LLVMConstNull(((void)0));
    _t4 = &_t0->ptr;
    *_t4 = _t3;
    return;
}

bool LLVMValue_is_null(struct LLVMValue** _arg0) {
    int64_t _t3;
    struct LLVMValue* _t1;
    struct LLVMValue** _t0;
    void* _t2;
    
    _t0 = _arg0;
    _t1 = *_t0;
    _t2 = (void*)0LL;
    _t3 = ((void)0) == _t2;
    return _t3;
}

void* LLVMValue_raw(struct LLVMValue** _arg0) {
    struct LLVMValue* _t1;
    struct LLVMValue** _t0;
    
    _t0 = _arg0;
    _t1 = *_t0;
    return ((void)0);
}

void LLVMBasicBlock_append(struct LLVMBasicBlock* _arg0, struct LLVMContext** _arg1, void* _arg2, uint8_t* _arg3) {
    int64_t _t5;
    int64_t _t6;
    struct LLVMBasicBlock* _t0;
    struct LLVMContext* _t4;
    struct LLVMContext** _t1;
    uint8_t* _t3;
    void* _t2;
    void** _t7;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = _arg3;
    _t4 = *_t1;
    LLVMAppendBasicBlockInContext(((void)0), _t2, _t3);
    _t6 = _t5;
    _t7 = &_t0->ptr;
    *_t7 = _t6;
    return;
}

void* LLVMBasicBlock_raw(struct LLVMBasicBlock** _arg0) {
    struct LLVMBasicBlock* _t1;
    struct LLVMBasicBlock** _t0;
    
    _t0 = _arg0;
    _t1 = *_t0;
    return ((void)0);
}

int32_t icmp_eq(void) {
    int32_t _t0;
    
    _t0 = (int32_t)32LL;
    return _t0;
}

int32_t icmp_ne(void) {
    int32_t _t0;
    
    _t0 = (int32_t)33LL;
    return _t0;
}

int32_t icmp_ugt(void) {
    int32_t _t0;
    
    _t0 = (int32_t)34LL;
    return _t0;
}

int32_t icmp_uge(void) {
    int32_t _t0;
    
    _t0 = (int32_t)35LL;
    return _t0;
}

int32_t icmp_ult(void) {
    int32_t _t0;
    
    _t0 = (int32_t)36LL;
    return _t0;
}

int32_t icmp_ule(void) {
    int32_t _t0;
    
    _t0 = (int32_t)37LL;
    return _t0;
}

int32_t icmp_sgt(void) {
    int32_t _t0;
    
    _t0 = (int32_t)38LL;
    return _t0;
}

int32_t icmp_sge(void) {
    int32_t _t0;
    
    _t0 = (int32_t)39LL;
    return _t0;
}

int32_t icmp_slt(void) {
    int32_t _t0;
    
    _t0 = (int32_t)40LL;
    return _t0;
}

int32_t icmp_sle(void) {
    int32_t _t0;
    
    _t0 = (int32_t)41LL;
    return _t0;
}

int32_t fcmp_oeq(void) {
    int32_t _t0;
    
    _t0 = (int32_t)1LL;
    return _t0;
}

int32_t fcmp_ogt(void) {
    int32_t _t0;
    
    _t0 = (int32_t)2LL;
    return _t0;
}

int32_t fcmp_oge(void) {
    int32_t _t0;
    
    _t0 = (int32_t)3LL;
    return _t0;
}

int32_t fcmp_olt(void) {
    int32_t _t0;
    
    _t0 = (int32_t)4LL;
    return _t0;
}

int32_t fcmp_ole(void) {
    int32_t _t0;
    
    _t0 = (int32_t)5LL;
    return _t0;
}

int32_t fcmp_one(void) {
    int32_t _t0;
    
    _t0 = (int32_t)6LL;
    return _t0;
}

int32_t verify_action_abort(void) {
    int32_t _t0;
    
    _t0 = (int32_t)0LL;
    return _t0;
}

int32_t verify_action_print(void) {
    int32_t _t0;
    
    _t0 = (int32_t)1LL;
    return _t0;
}

int32_t verify_action_return(void) {
    int32_t _t0;
    
    _t0 = (int32_t)2LL;
    return _t0;
}

void llvm_init_all_targets(void) {
    
    LLVMInitializeAllTargetInfos();
    LLVMInitializeAllTargets();
    LLVMInitializeAllTargetMCs();
    LLVMInitializeAllAsmPrinters();
    LLVMInitializeAllAsmParsers();
    return;
}

uint8_t* llvm_default_triple(void) {
    int64_t _t0;
    
    LLVMGetDefaultTargetTriple();
    return _t0;
}

int32_t opt_none(void) {
    int32_t _t0;
    
    _t0 = (int32_t)0LL;
    return _t0;
}

int32_t opt_less(void) {
    int32_t _t0;
    
    _t0 = (int32_t)1LL;
    return _t0;
}

int32_t opt_default(void) {
    int32_t _t0;
    
    _t0 = (int32_t)2LL;
    return _t0;
}

int32_t opt_aggressive(void) {
    int32_t _t0;
    
    _t0 = (int32_t)3LL;
    return _t0;
}

int32_t reloc_default(void) {
    int32_t _t0;
    
    _t0 = (int32_t)0LL;
    return _t0;
}

int32_t reloc_static(void) {
    int32_t _t0;
    
    _t0 = (int32_t)1LL;
    return _t0;
}

int32_t reloc_pic(void) {
    int32_t _t0;
    
    _t0 = (int32_t)2LL;
    return _t0;
}

int32_t reloc_dynamic_no_pic(void) {
    int32_t _t0;
    
    _t0 = (int32_t)3LL;
    return _t0;
}

int32_t code_model_default(void) {
    int32_t _t0;
    
    _t0 = (int32_t)0LL;
    return _t0;
}

int32_t code_model_jit(void) {
    int32_t _t0;
    
    _t0 = (int32_t)1LL;
    return _t0;
}

int32_t code_model_small(void) {
    int32_t _t0;
    
    _t0 = (int32_t)2LL;
    return _t0;
}

int32_t code_model_kernel(void) {
    int32_t _t0;
    
    _t0 = (int32_t)3LL;
    return _t0;
}

int32_t code_model_medium(void) {
    int32_t _t0;
    
    _t0 = (int32_t)4LL;
    return _t0;
}

int32_t code_model_large(void) {
    int32_t _t0;
    
    _t0 = (int32_t)5LL;
    return _t0;
}

int32_t codegen_asm(void) {
    int32_t _t0;
    
    _t0 = (int32_t)0LL;
    return _t0;
}

int32_t codegen_obj(void) {
    int32_t _t0;
    
    _t0 = (int32_t)1LL;
    return _t0;
}

int32_t main(void) {
    int32_t _t6;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    uint8_t* _t0;
    uint8_t* _t2;
    uint8_t* _t4;
    
    _t0 = (uint8_t*)"LLVM FFI Module for AetherLang\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"Provides bindings to LLVM C API\u{0}";
    puts(_t2);
    _t4 = (uint8_t*)"Functions: Context, Module, Builder, Types, Values\u{0}";
    puts(_t4);
    _t6 = (int32_t)0LL;
    return _t6;
}

