/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
int32_t token_eof(void);
int32_t token_int(void);
int32_t token_ident(void);
int32_t token_plus(void);
bool is_digit(int32_t);
bool is_alpha(int32_t);
void print_token(int32_t);
void main(void);

int32_t token_eof(void) {
    int32_t _t0;
    
    _t0 = (int32_t)0LL;
    return _t0;
}

int32_t token_int(void) {
    int32_t _t0;
    
    _t0 = (int32_t)1LL;
    return _t0;
}

int32_t token_ident(void) {
    int32_t _t0;
    
    _t0 = (int32_t)2LL;
    return _t0;
}

int32_t token_plus(void) {
    int32_t _t0;
    
    _t0 = (int32_t)3LL;
    return _t0;
}

bool is_digit(int32_t _arg0) {
    int32_t _t0;
    int32_t _t1;
    int32_t _t3;
    int64_t _t2;
    int64_t _t4;
    int64_t _t5;
    
    _t0 = _arg0;
    _t1 = (int32_t)48LL;
    _t2 = _t0 >= _t1;
    _t3 = (int32_t)57LL;
    _t4 = _t0 <= _t3;
    _t5 = _t2 && _t4;
    return _t5;
}

bool is_alpha(int32_t _arg0) {
    int32_t _t0;
    int32_t _t1;
    int32_t _t3;
    int32_t _t6;
    int32_t _t8;
    int64_t _t10;
    int64_t _t11;
    int64_t _t2;
    int64_t _t4;
    int64_t _t5;
    int64_t _t7;
    int64_t _t9;
    
    _t0 = _arg0;
    _t1 = (int32_t)65LL;
    _t2 = _t0 >= _t1;
    _t3 = (int32_t)90LL;
    _t4 = _t0 <= _t3;
    _t5 = _t2 && _t4;
    _t6 = (int32_t)97LL;
    _t7 = _t0 >= _t6;
    _t8 = (int32_t)122LL;
    _t9 = _t0 <= _t8;
    _t10 = _t7 && _t9;
    _t11 = _t5 || _t10;
    return _t11;
}

void print_token(int32_t _arg0) {
    int32_t _t0;
    int32_t _t10;
    int32_t _t1;
    int32_t _t4;
    int32_t _t7;
    int64_t _t11;
    int64_t _t12;
    int64_t _t2;
    int64_t _t3;
    int64_t _t5;
    int64_t _t6;
    int64_t _t8;
    int64_t _t9;
    
    _t0 = _arg0;
    _t1 = (int32_t)0LL;
    _t2 = _t0 == _t1;
    if (_t2) goto L_then; else goto L_else;
L_then:
    printf("EOF\n");
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    _t4 = (int32_t)1LL;
    _t5 = _t0 == _t4;
    if (_t5) goto L_then; else goto L_else;
L_then:
    printf("INT\n");
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    _t7 = (int32_t)2LL;
    _t8 = _t0 == _t7;
    if (_t8) goto L_then; else goto L_else;
L_then:
    printf("IDENT\n");
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    _t10 = (int32_t)3LL;
    _t11 = _t0 == _t10;
    if (_t11) goto L_then; else goto L_else;
L_then:
    printf("PLUS\n");
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    return;
}

void main(void) {
    bool _t6;
    bool _t9;
    int32_t _t1;
    int32_t _t2;
    int32_t _t3;
    int32_t _t4;
    int32_t _t5;
    int32_t _t8;
    int64_t _t0;
    int64_t _t10;
    int64_t _t11;
    int64_t _t7;
    
    printf("Lexer Bootstrap Test\n");
    _t1 = token_int();
    print_token(_t1);
    _t2 = token_ident();
    print_token(_t2);
    _t3 = token_plus();
    print_token(_t3);
    _t4 = token_eof();
    print_token(_t4);
    _t5 = (int32_t)48LL;
    _t6 = is_digit(_t5);
    if (_t6) goto L_then; else goto L_else;
L_then:
    printf("\'0\' is a digit\n");
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    _t8 = (int32_t)65LL;
    _t9 = is_alpha(_t8);
    if (_t9) goto L_then; else goto L_else;
L_then:
    printf("\'A\' is alpha\n");
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    printf("Bootstrap complete!\n");
    return;
}

