/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct Span {
    uint64_t file_id;
    uint64_t start;
    uint64_t end;
};

void Span_new(struct Span*, uint64_t, uint64_t, uint64_t);
void Span_empty(struct Span*, uint64_t, uint64_t);
void Span_merge(struct Span*, struct Span*, struct Span*);

void Span_new(struct Span* _arg0, uint64_t _arg1, uint64_t _arg2, uint64_t _arg3) {
    struct Span* _t0;
    uint64_t _t1;
    uint64_t _t2;
    uint64_t _t3;
    uint64_t* _t4;
    uint64_t* _t5;
    uint64_t* _t6;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = _arg3;
    _t4 = &_t0->file_id;
    *_t4 = _t1;
    _t5 = &_t0->start;
    *_t5 = _t2;
    _t6 = &_t0->end;
    *_t6 = _t3;
    return;
}

void Span_empty(struct Span* _arg0, uint64_t _arg1, uint64_t _arg2) {
    struct Span* _t0;
    uint64_t _t1;
    uint64_t _t2;
    uint64_t* _t3;
    uint64_t* _t4;
    uint64_t* _t5;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = &_t0->file_id;
    *_t3 = _t1;
    _t4 = &_t0->start;
    *_t4 = _t2;
    _t5 = &_t0->end;
    *_t5 = _t2;
    return;
}

void Span_merge(struct Span* _arg0, struct Span* _arg1, struct Span* _arg2) {
    int64_t _t10;
    int64_t _t21;
    struct Span* _t0;
    struct Span* _t1;
    struct Span* _t2;
    uint64_t _t12;
    uint64_t _t14;
    uint64_t _t15;
    uint64_t _t18;
    uint64_t _t20;
    uint64_t _t23;
    uint64_t _t25;
    uint64_t _t26;
    uint64_t _t4;
    uint64_t _t7;
    uint64_t _t9;
    uint64_t* _t11;
    uint64_t* _t13;
    uint64_t* _t16;
    uint64_t* _t17;
    uint64_t* _t19;
    uint64_t* _t22;
    uint64_t* _t24;
    uint64_t* _t27;
    uint64_t* _t3;
    uint64_t* _t5;
    uint64_t* _t6;
    uint64_t* _t8;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = &_t1->file_id;
    _t4 = *_t3;
    _t5 = &_t0->file_id;
    *_t5 = _t4;
    _t6 = &_t1->start;
    _t7 = *_t6;
    _t8 = &_t2->start;
    _t9 = *_t8;
    _t10 = _t7 < _t9;
    if (_t10) goto L_then; else goto L_else;
L_then:
    _t11 = &_t1->start;
    _t12 = *_t11;
    goto L_merge;
L_else:
    _t13 = &_t2->start;
    _t14 = *_t13;
    goto L_merge;
L_merge:
    _t15 = _t12;
    _t16 = &_t0->start;
    *_t16 = _t15;
    _t17 = &_t1->end;
    _t18 = *_t17;
    _t19 = &_t2->end;
    _t20 = *_t19;
    _t21 = _t18 > _t20;
    if (_t21) goto L_then; else goto L_else;
L_then:
    _t22 = &_t1->end;
    _t23 = *_t22;
    goto L_merge;
L_else:
    _t24 = &_t2->end;
    _t25 = *_t24;
    goto L_merge;
L_merge:
    _t26 = _t23;
    _t27 = &_t0->end;
    *_t27 = _t26;
    return;
}

