/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
bool check_project(void);
int32_t build_project(bool);
int32_t run_project(uint8_t*);
int32_t clean_project(void);

bool check_project(void) {
    int32_t _t2;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    uint8_t* _t0;
    uint8_t* _t4;
    uint8_t* _t6;
    
    _t0 = (uint8_t*)"Jxz.toml\u{0}";
    access(_t0, F_OK);
    _t2 = (int32_t)0LL;
    _t3 = _t1 != _t2;
    if (_t3) goto L_then; else goto L_else;
L_then:
    _t4 = (uint8_t*)"Error: No Jxz.toml found in current directory\u{0}";
    puts(_t4);
    _t6 = (uint8_t*)"Run \'jxz init\' to create a new project\u{0}";
    puts(_t6);
    return 0;
L_else:
    goto L_merge;
L_merge:
    return 1;
}

int32_t build_project(bool _arg0) {
    bool _t0;
    bool _t1;
    bool _t2;
    int32_t _t17;
    int32_t _t28;
    int32_t _t31;
    int32_t _t3;
    int64_t _t11;
    int64_t _t13;
    int64_t _t14;
    int64_t _t16;
    int64_t _t19;
    int64_t _t21;
    int64_t _t23;
    int64_t _t24;
    int64_t _t25;
    int64_t _t27;
    int64_t _t30;
    int64_t _t5;
    int64_t _t8;
    int64_t _t9;
    uint32_t _t7;
    uint8_t* _t10;
    uint8_t* _t12;
    uint8_t* _t15;
    uint8_t* _t18;
    uint8_t* _t20;
    uint8_t* _t22;
    uint8_t* _t26;
    uint8_t* _t29;
    uint8_t* _t4;
    uint8_t* _t6;
    
    _t0 = _arg0;
    _t1 = check_project();
    _t2 = !_t1;
    if (_t2) goto L_then; else goto L_else;
L_then:
    _t3 = (int32_t)1LL;
    return _t3;
L_else:
    goto L_merge;
L_merge:
    _t4 = (uint8_t*)"   Compiling project...\u{0}";
    puts(_t4);
    _t6 = (uint8_t*)"target\u{0}";
    _t7 = (uint32_t)493LL;
    mkdir(_t6, _t7);
    _t9 = 0LL;
    _t10 = (uint8_t*)"     Compiling src/main.aeth -> C\u{0}";
    puts(_t10);
    _t12 = (uint8_t*)"aethc --emit-c src/main.aeth\u{0}";
    system(_t12);
    _t9 = _t13;
    _t14 = _t9 != 0LL;
    if (_t14) goto L_then; else goto L_else;
L_then:
    _t15 = (uint8_t*)"Error: Compilation failed\u{0}";
    puts(_t15);
    _t17 = (int32_t)1LL;
    return _t17;
L_else:
    goto L_merge;
L_merge:
    _t18 = (uint8_t*)"     Compiling C -> executable\u{0}";
    puts(_t18);
    if (_t0) goto L_then; else goto L_else;
L_then:
    _t20 = (uint8_t*)"cc -O2 -o target/main src/main.c 2>/dev/null || gcc -O2 -o target/main src/main.c\u{0}";
    system(_t20);
    _t9 = _t21;
    goto L_merge;
L_else:
    _t22 = (uint8_t*)"cc -g -o target/main src/main.c 2>/dev/null || gcc -g -o target/main src/main.c\u{0}";
    system(_t22);
    _t9 = _t23;
    goto L_merge;
L_merge:
    _t24 = _t21;
    _t25 = _t9 != 0LL;
    if (_t25) goto L_then; else goto L_else;
L_then:
    _t26 = (uint8_t*)"Error: C compilation failed\u{0}";
    puts(_t26);
    _t28 = (int32_t)1LL;
    return _t28;
L_else:
    goto L_merge;
L_merge:
    _t29 = (uint8_t*)"    Finished build\u{0}";
    puts(_t29);
    _t31 = (int32_t)0LL;
    return _t31;
}

int32_t run_project(uint8_t* _arg0) {
    int32_t _t1;
    int32_t _t2;
    int32_t _t3;
    int64_t _t10;
    int64_t _t4;
    int64_t _t6;
    int64_t _t8;
    uint8_t* _t0;
    uint8_t* _t5;
    uint8_t* _t7;
    uint8_t* _t9;
    
    _t0 = _arg0;
    _t1 = build_project(0);
    _t2 = _t1;
    _t3 = (int32_t)0LL;
    _t4 = _t2 != _t3;
    if (_t4) goto L_then; else goto L_else;
L_then:
    return _t2;
L_else:
    goto L_merge;
L_merge:
    _t5 = (uint8_t*)"     Running target/main\u{0}";
    puts(_t5);
    _t7 = (uint8_t*)"\u{0}";
    puts(_t7);
    _t9 = (uint8_t*)"./target/main\u{0}";
    system(_t9);
    _t2 = _t10;
    return _t2;
}

int32_t clean_project(void) {
    int32_t _t8;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    uint8_t* _t0;
    uint8_t* _t2;
    uint8_t* _t4;
    uint8_t* _t6;
    
    _t0 = (uint8_t*)"Cleaning build artifacts...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"rm -rf target\u{0}";
    system(_t2);
    _t4 = (uint8_t*)"rm -f src/*.c\u{0}";
    system(_t4);
    _t6 = (uint8_t*)"  Cleaned\u{0}";
    puts(_t6);
    _t8 = (int32_t)0LL;
    return _t8;
}

