/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
int32_t cache_info(void);
int32_t cache_list(void);
int32_t cache_clean(void);
int32_t cache_clean_old(void);
int32_t cache_verify(void);

int32_t cache_info(void) {
    int32_t _t8;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    uint8_t* _t0;
    uint8_t* _t2;
    uint8_t* _t4;
    uint8_t* _t6;
    
    _t0 = (uint8_t*)"==> Cache information:\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"echo \"  Location: ~/.jxz/cache\"\u{0}";
    system(_t2);
    _t4 = (uint8_t*)"echo \"  Size: $(du -sh ~/.jxz/cache 2>/dev/null | cut -f1 || echo \'N/A\')\"\u{0}";
    system(_t4);
    _t6 = (uint8_t*)"echo \"  Files: $(ls ~/.jxz/cache 2>/dev/null | wc -l || echo 0)\"\u{0}";
    system(_t6);
    _t8 = (int32_t)0LL;
    return _t8;
}

int32_t cache_list(void) {
    int32_t _t4;
    int64_t _t1;
    int64_t _t3;
    uint8_t* _t0;
    uint8_t* _t2;
    
    _t0 = (uint8_t*)"==> Cached packages:\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"ls -lh ~/.jxz/cache 2>/dev/null | tail -n +2 || echo \'  (empty)\'\u{0}";
    system(_t2);
    _t4 = (int32_t)0LL;
    return _t4;
}

int32_t cache_clean(void) {
    int32_t _t6;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    uint8_t* _t0;
    uint8_t* _t2;
    uint8_t* _t4;
    
    _t0 = (uint8_t*)"==> Cleaning cache...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"rm -rf ~/.jxz/cache/*\u{0}";
    system(_t2);
    _t4 = (uint8_t*)"  Cache cleaned\u{0}";
    puts(_t4);
    _t6 = (int32_t)0LL;
    return _t6;
}

int32_t cache_clean_old(void) {
    int32_t _t6;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    uint8_t* _t0;
    uint8_t* _t2;
    uint8_t* _t4;
    
    _t0 = (uint8_t*)"==> Cleaning old cache files...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"find ~/.jxz/cache -type f -mtime +30 -delete 2>/dev/null\u{0}";
    system(_t2);
    _t4 = (uint8_t*)"  Old files removed\u{0}";
    puts(_t4);
    _t6 = (int32_t)0LL;
    return _t6;
}

int32_t cache_verify(void) {
    int32_t _t6;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    uint8_t* _t0;
    uint8_t* _t2;
    uint8_t* _t4;
    
    _t0 = (uint8_t*)"==> Verifying cache integrity...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"for f in ~/.jxz/cache/*.tar.gz; do [ -f \"$f\" ] && (tar -tzf \"$f\" >/dev/null 2>&1 || echo \"  Corrupted: $f\"); done\u{0}";
    system(_t2);
    _t4 = (uint8_t*)"  Verification complete\u{0}";
    puts(_t4);
    _t6 = (int32_t)0LL;
    return _t6;
}

