/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct PackageInfo {
    uint8_t* name;
    uint8_t* version;
    uint8_t* description;
};

bool db_is_installed(uint8_t*);
void db_list_installed(void);
int32_t db_count_installed(void);
void db_add_installed(uint8_t*, uint8_t*);
void db_remove_installed(uint8_t*);
struct PackageInfo* db_get_info(uint8_t*);
void db_print_info(uint8_t*);
int32_t db_sync_index(void);
void db_search(uint8_t*);

bool db_is_installed(uint8_t* _arg0) {
    int32_t _t4;
    int64_t _t2;
    int64_t _t3;
    int64_t _t5;
    uint8_t* _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"test -d ~/.jxz/Cellar/$1 2>/dev/null\u{0}";
    system(_t1);
    _t3 = _t2;
    _t4 = (int32_t)0LL;
    _t5 = _t3 == _t4;
    return _t5;
}

void db_list_installed(void) {
    int64_t _t1;
    int64_t _t3;
    uint8_t* _t0;
    uint8_t* _t2;
    
    _t0 = (uint8_t*)"Installed packages:\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"ls ~/.jxz/Cellar 2>/dev/null | while read pkg; do echo \"  $pkg\"; done\u{0}";
    system(_t2);
    return;
}

int32_t db_count_installed(void) {
    int32_t _t2;
    int64_t _t1;
    uint8_t* _t0;
    
    _t0 = (uint8_t*)"echo \"$(ls ~/.jxz/Cellar 2>/dev/null | wc -l) packages installed\"\u{0}";
    system(_t0);
    _t2 = (int32_t)0LL;
    return _t2;
}

void db_add_installed(uint8_t* _arg0, uint8_t* _arg1) {
    int64_t _t3;
    int64_t _t6;
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t2;
    uint8_t* _t4;
    uint8_t* _t5;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"mkdir -p ~/.jxz/db\u{0}";
    system(_t2);
    _t4 = (uint8_t*)"echo \'PLACEHOLDER\' >> ~/.jxz/db/installed.db\u{0}";
    _t5 = _t4;
    system(_t5);
    return;
}

void db_remove_installed(uint8_t* _arg0) {
    int64_t _t2;
    uint8_t* _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"grep -v \'PLACEHOLDER\' ~/.jxz/db/installed.db > /tmp/jxz_tmp && mv /tmp/jxz_tmp ~/.jxz/db/installed.db\u{0}";
    system(_t1);
    return;
}

struct PackageInfo* db_get_info(uint8_t* _arg0) {
    struct PackageInfo* _t1;
    uint8_t* _t0;
    uint8_t* _t3;
    uint8_t* _t5;
    uint8_t** _t2;
    uint8_t** _t4;
    uint8_t** _t6;
    
    _t0 = _arg0;
    struct PackageInfo _alloca__t1;
    _t1 = &_alloca__t1;
    _t2 = &_t1->name;
    *_t2 = _t0;
    _t3 = (uint8_t*)"unknown\u{0}";
    _t4 = &_t1->version;
    *_t4 = _t3;
    _t5 = (uint8_t*)"No description\u{0}";
    _t6 = &_t1->description;
    *_t6 = _t5;
    return _t1;
}

void db_print_info(uint8_t* _arg0) {
    int64_t _t2;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t4;
    uint8_t* _t6;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"Package: \u{0}";
    puts(_t1);
    puts(_t0);
    _t4 = (uint8_t*)"  Version: (checking...)\u{0}";
    puts(_t4);
    _t6 = (uint8_t*)"ls ~/.jxz/Cellar/$1 2>/dev/null | head -1\u{0}";
    system(_t6);
    return;
}

int32_t db_sync_index(void) {
    int32_t _t5;
    int64_t _t10;
    int64_t _t11;
    int64_t _t1;
    int64_t _t3;
    int64_t _t4;
    int64_t _t6;
    int64_t _t8;
    uint8_t* _t0;
    uint8_t* _t2;
    uint8_t* _t7;
    uint8_t* _t9;
    
    _t0 = (uint8_t*)"==> Syncing package index...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"curl -sL -o ~/.jxz/db/packages.idx https://registry.aetherlang.org/index.json 2>/dev/null\u{0}";
    system(_t2);
    _t4 = _t3;
    _t5 = (int32_t)0LL;
    _t6 = _t4 == _t5;
    if (_t6) goto L_then; else goto L_else;
L_then:
    _t7 = (uint8_t*)"==> Index synced\u{0}";
    puts(_t7);
    goto L_merge;
L_else:
    _t9 = (uint8_t*)"==> Failed to sync index\u{0}";
    puts(_t9);
    goto L_merge;
L_merge:
    _t11 = _t8;
    return _t4;
}

void db_search(uint8_t* _arg0) {
    int64_t _t2;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t4;
    uint8_t* _t6;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"Searching for: \u{0}";
    puts(_t1);
    puts(_t0);
    _t4 = (uint8_t*)"\u{0}";
    puts(_t4);
    _t6 = (uint8_t*)"grep -i \'$1\' ~/.jxz/db/packages.idx 2>/dev/null || echo \'No packages found\'\u{0}";
    system(_t6);
    return;
}

