/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
int32_t http_download(uint8_t*, uint8_t*);
bool http_check(uint8_t*);
int32_t download_package(uint8_t*, uint8_t*, uint8_t*);
int32_t extract_package(uint8_t*, uint8_t*);

int32_t http_download(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t33;
    int32_t _t52;
    int32_t _t5;
    int32_t _t6;
    int32_t _t8;
    int32_t _t9;
    int64_t _t10;
    int64_t _t11;
    int64_t _t12;
    int64_t _t13;
    int64_t _t14;
    int64_t _t17;
    int64_t _t18;
    int64_t _t19;
    int64_t _t23;
    int64_t _t24;
    int64_t _t26;
    int64_t _t27;
    int64_t _t29;
    int64_t _t30;
    int64_t _t31;
    int64_t _t34;
    int64_t _t37;
    int64_t _t38;
    int64_t _t39;
    int64_t _t3;
    int64_t _t43;
    int64_t _t44;
    int64_t _t46;
    int64_t _t47;
    int64_t _t49;
    int64_t _t4;
    int64_t _t50;
    int64_t _t53;
    int64_t _t55;
    int64_t _t57;
    int64_t _t58;
    int64_t _t7;
    uint64_t _t15;
    uint64_t _t16;
    uint64_t _t35;
    uint64_t _t36;
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t20;
    uint8_t* _t21;
    uint8_t* _t22;
    uint8_t* _t25;
    uint8_t* _t28;
    uint8_t* _t2;
    uint8_t* _t40;
    uint8_t* _t41;
    uint8_t* _t42;
    uint8_t* _t45;
    uint8_t* _t48;
    uint8_t* _t54;
    uint8_t* _t56;
    void* _t32;
    void* _t51;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"   Downloading...\u{0}";
    puts(_t2);
    strlen(_t0);
    _t5 = (int32_t)_t4;
    _t6 = _t5;
    strlen(_t1);
    _t8 = (int32_t)_t7;
    _t9 = _t8;
    _t10 = (int64_t)_t6;
    _t11 = 20LL + _t10;
    _t12 = (int64_t)_t9;
    _t13 = _t11 + _t12;
    _t14 = _t13;
    _t15 = (uint64_t)_t14;
    _t16 = (uint64_t)50LL;
    _t17 = _t15 + _t16;
    _t18 = (int64_t)_t17;
    malloc(_t18);
    _t20 = (uint8_t*)_t19;
    _t21 = _t20;
    _t22 = (uint8_t*)"curl -sL -o \u{0}";
    strcpy(_t21, _t22);
    strcat(_t21, _t1);
    _t25 = (uint8_t*)" \u{0}";
    strcat(_t21, _t25);
    strcat(_t21, _t0);
    _t28 = (uint8_t*)" 2>/dev/null\u{0}";
    strcat(_t21, _t28);
    system(_t21);
    _t31 = _t30;
    _t32 = (void*)_t21;
    free(_t32);
    _t33 = (int32_t)0LL;
    _t34 = _t31 != _t33;
    if (_t34) goto L_then; else goto L_else;
L_then:
    _t35 = (uint64_t)_t14;
    _t36 = (uint64_t)50LL;
    _t37 = _t35 + _t36;
    _t38 = (int64_t)_t37;
    malloc(_t38);
    _t40 = (uint8_t*)_t39;
    _t41 = _t40;
    _t42 = (uint8_t*)"wget -q -O \u{0}";
    strcpy(_t41, _t42);
    strcat(_t41, _t1);
    _t45 = (uint8_t*)" \u{0}";
    strcat(_t41, _t45);
    strcat(_t41, _t0);
    _t48 = (uint8_t*)" 2>/dev/null\u{0}";
    strcat(_t41, _t48);
    system(_t41);
    _t31 = _t50;
    _t51 = (void*)_t41;
    free(_t51);
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    _t52 = (int32_t)0LL;
    _t53 = _t31 == _t52;
    if (_t53) goto L_then; else goto L_else;
L_then:
    _t54 = (uint8_t*)"   Downloaded successfully\u{0}";
    puts(_t54);
    goto L_merge;
L_else:
    _t56 = (uint8_t*)"   Download failed\u{0}";
    puts(_t56);
    goto L_merge;
L_merge:
    _t58 = _t55;
    return _t31;
}

bool http_check(uint8_t* _arg0) {
    int32_t _t19;
    int32_t _t2;
    int32_t _t3;
    int64_t _t12;
    int64_t _t13;
    int64_t _t15;
    int64_t _t16;
    int64_t _t17;
    int64_t _t1;
    int64_t _t20;
    int64_t _t6;
    int64_t _t7;
    int64_t _t8;
    uint64_t _t4;
    uint64_t _t5;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t11;
    uint8_t* _t14;
    uint8_t* _t9;
    void* _t18;
    
    _t0 = _arg0;
    strlen(_t0);
    _t2 = (int32_t)_t1;
    _t3 = _t2;
    _t4 = (uint64_t)_t3;
    _t5 = (uint64_t)50LL;
    _t6 = _t4 + _t5;
    _t7 = (int64_t)_t6;
    malloc(_t7);
    _t9 = (uint8_t*)_t8;
    _t10 = _t9;
    _t11 = (uint8_t*)"curl -sI \u{0}";
    strcpy(_t10, _t11);
    strcat(_t10, _t0);
    _t14 = (uint8_t*)" >/dev/null 2>&1\u{0}";
    strcat(_t10, _t14);
    system(_t10);
    _t17 = _t16;
    _t18 = (void*)_t10;
    free(_t18);
    _t19 = (int32_t)0LL;
    _t20 = _t17 == _t19;
    return _t20;
}

int32_t download_package(uint8_t* _arg0, uint8_t* _arg1, uint8_t* _arg2) {
    int32_t _t10;
    int32_t _t11;
    int32_t _t13;
    int32_t _t14;
    int32_t _t53;
    int32_t _t54;
    int32_t _t7;
    int32_t _t8;
    int64_t _t12;
    int64_t _t17;
    int64_t _t19;
    int64_t _t21;
    int64_t _t22;
    int64_t _t23;
    int64_t _t26;
    int64_t _t28;
    int64_t _t29;
    int64_t _t31;
    int64_t _t32;
    int64_t _t34;
    int64_t _t37;
    int64_t _t39;
    int64_t _t40;
    int64_t _t41;
    int64_t _t44;
    int64_t _t46;
    int64_t _t47;
    int64_t _t49;
    int64_t _t4;
    int64_t _t50;
    int64_t _t52;
    int64_t _t5;
    int64_t _t6;
    int64_t _t9;
    uint64_t _t15;
    uint64_t _t16;
    uint64_t _t18;
    uint64_t _t20;
    uint64_t _t35;
    uint64_t _t36;
    uint64_t _t38;
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t24;
    uint8_t* _t25;
    uint8_t* _t27;
    uint8_t* _t2;
    uint8_t* _t30;
    uint8_t* _t33;
    uint8_t* _t3;
    uint8_t* _t42;
    uint8_t* _t43;
    uint8_t* _t45;
    uint8_t* _t48;
    uint8_t* _t51;
    void* _t55;
    void* _t56;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = (uint8_t*)"   Fetching package:\u{0}";
    puts(_t3);
    puts(_t0);
    strlen(_t0);
    _t7 = (int32_t)_t6;
    _t8 = _t7;
    strlen(_t1);
    _t10 = (int32_t)_t9;
    _t11 = _t10;
    strlen(REGISTRY_URL);
    _t13 = (int32_t)_t12;
    _t14 = _t13;
    _t15 = (uint64_t)_t8;
    _t16 = (uint64_t)_t11;
    _t17 = _t15 + _t16;
    _t18 = (uint64_t)_t14;
    _t19 = _t17 + _t18;
    _t20 = (uint64_t)30LL;
    _t21 = _t19 + _t20;
    _t22 = (int64_t)_t21;
    malloc(_t22);
    _t24 = (uint8_t*)_t23;
    _t25 = _t24;
    strcpy(_t25, REGISTRY_URL);
    _t27 = (uint8_t*)"packages/\u{0}";
    strcat(_t25, _t27);
    strcat(_t25, _t0);
    _t30 = (uint8_t*)"/\u{0}";
    strcat(_t25, _t30);
    strcat(_t25, _t1);
    _t33 = (uint8_t*)".tar.gz\u{0}";
    strcat(_t25, _t33);
    _t35 = (uint64_t)_t8;
    _t36 = (uint64_t)_t11;
    _t37 = _t35 + _t36;
    _t38 = (uint64_t)50LL;
    _t39 = _t37 + _t38;
    _t40 = (int64_t)_t39;
    malloc(_t40);
    _t42 = (uint8_t*)_t41;
    _t43 = _t42;
    strcpy(_t43, _t2);
    _t45 = (uint8_t*)"/\u{0}";
    strcat(_t43, _t45);
    strcat(_t43, _t0);
    _t48 = (uint8_t*)"-\u{0}";
    strcat(_t43, _t48);
    strcat(_t43, _t1);
    _t51 = (uint8_t*)".tar.gz\u{0}";
    strcat(_t43, _t51);
    _t53 = http_download(_t25, _t43);
    _t54 = _t53;
    _t55 = (void*)_t25;
    free(_t55);
    _t56 = (void*)_t43;
    free(_t56);
    return _t54;
}

int32_t extract_package(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t5;
    int32_t _t6;
    int32_t _t8;
    int32_t _t9;
    int64_t _t12;
    int64_t _t14;
    int64_t _t15;
    int64_t _t16;
    int64_t _t20;
    int64_t _t21;
    int64_t _t23;
    int64_t _t24;
    int64_t _t25;
    int64_t _t26;
    int64_t _t3;
    int64_t _t4;
    int64_t _t7;
    uint64_t _t10;
    uint64_t _t11;
    uint64_t _t13;
    uint8_t* _t0;
    uint8_t* _t17;
    uint8_t* _t18;
    uint8_t* _t19;
    uint8_t* _t1;
    uint8_t* _t22;
    uint8_t* _t2;
    void* _t27;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"   Extracting...\u{0}";
    puts(_t2);
    strlen(_t0);
    _t5 = (int32_t)_t4;
    _t6 = _t5;
    strlen(_t1);
    _t8 = (int32_t)_t7;
    _t9 = _t8;
    _t10 = (uint64_t)_t6;
    _t11 = (uint64_t)_t9;
    _t12 = _t10 + _t11;
    _t13 = (uint64_t)30LL;
    _t14 = _t12 + _t13;
    _t15 = (int64_t)_t14;
    malloc(_t15);
    _t17 = (uint8_t*)_t16;
    _t18 = _t17;
    _t19 = (uint8_t*)"tar -xzf \u{0}";
    strcpy(_t18, _t19);
    strcat(_t18, _t0);
    _t22 = (uint8_t*)" -C \u{0}";
    strcat(_t18, _t22);
    strcat(_t18, _t1);
    system(_t18);
    _t26 = _t25;
    _t27 = (void*)_t18;
    free(_t27);
    return _t26;
}

