/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
bool write_jxz_toml(uint8_t*);
bool write_main_aeth(void);
bool write_gitignore(void);
int32_t init_project(uint8_t*);

bool write_jxz_toml(uint8_t* _arg0) {
    int64_t _t10;
    int64_t _t12;
    int64_t _t13;
    int64_t _t15;
    int64_t _t17;
    int64_t _t19;
    int64_t _t21;
    int64_t _t22;
    int64_t _t3;
    int64_t _t4;
    int64_t _t6;
    int64_t _t8;
    uint8_t* _t0;
    uint8_t* _t11;
    uint8_t* _t14;
    uint8_t* _t16;
    uint8_t* _t18;
    uint8_t* _t1;
    uint8_t* _t20;
    uint8_t* _t2;
    uint8_t* _t7;
    uint8_t* _t9;
    void* _t5;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"Jxz.toml\u{0}";
    _t2 = (uint8_t*)"w\u{0}";
    fopen(_t1, _t2);
    _t4 = _t3;
    _t5 = (void*)0LL;
    _t6 = _t4 == _t5;
    if (_t6) goto L_then; else goto L_else;
L_then:
    _t7 = (uint8_t*)"Error: Could not create Jxz.toml\u{0}";
    puts(_t7);
    return 0;
L_else:
    goto L_merge;
L_merge:
    _t9 = (uint8_t*)"[package]\n\u{0}";
    fputs(_t9, _t4);
    _t11 = (uint8_t*)"name = \"\u{0}";
    fputs(_t11, _t4);
    fputs(_t0, _t4);
    _t14 = (uint8_t*)"\"\n\u{0}";
    fputs(_t14, _t4);
    _t16 = (uint8_t*)"version = \"0.1.0\"\n\u{0}";
    fputs(_t16, _t4);
    _t18 = (uint8_t*)"edition = \"2026\"\n\u{0}";
    fputs(_t18, _t4);
    _t20 = (uint8_t*)"\n[dependencies]\n\u{0}";
    fputs(_t20, _t4);
    fclose(_t4);
    return 1;
}

bool write_main_aeth(void) {
    int64_t _t11;
    int64_t _t13;
    int64_t _t15;
    int64_t _t17;
    int64_t _t19;
    int64_t _t21;
    int64_t _t23;
    int64_t _t25;
    int64_t _t27;
    int64_t _t28;
    int64_t _t2;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    int64_t _t9;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t12;
    uint8_t* _t14;
    uint8_t* _t16;
    uint8_t* _t18;
    uint8_t* _t1;
    uint8_t* _t20;
    uint8_t* _t22;
    uint8_t* _t24;
    uint8_t* _t26;
    uint8_t* _t6;
    uint8_t* _t8;
    void* _t4;
    
    _t0 = (uint8_t*)"src/main.aeth\u{0}";
    _t1 = (uint8_t*)"w\u{0}";
    fopen(_t0, _t1);
    _t3 = _t2;
    _t4 = (void*)0LL;
    _t5 = _t3 == _t4;
    if (_t5) goto L_then; else goto L_else;
L_then:
    _t6 = (uint8_t*)"Error: Could not create src/main.aeth\u{0}";
    puts(_t6);
    return 0;
L_else:
    goto L_merge;
L_merge:
    _t8 = (uint8_t*)"// AetherLang Project\n\u{0}";
    fputs(_t8, _t3);
    _t10 = (uint8_t*)"\n\u{0}";
    fputs(_t10, _t3);
    _t12 = (uint8_t*)"extern \"C\" {\n\u{0}";
    fputs(_t12, _t3);
    _t14 = (uint8_t*)"    fn puts(s: *u8) -> i32;\n\u{0}";
    fputs(_t14, _t3);
    _t16 = (uint8_t*)"}\n\u{0}";
    fputs(_t16, _t3);
    _t18 = (uint8_t*)"\n\u{0}";
    fputs(_t18, _t3);
    _t20 = (uint8_t*)"pub fn main() -> i32 {\n\u{0}";
    fputs(_t20, _t3);
    _t22 = (uint8_t*)"    puts(\"Hello, AetherLang!\\0\" as *u8)\n\u{0}";
    fputs(_t22, _t3);
    _t24 = (uint8_t*)"    return 0\n\u{0}";
    fputs(_t24, _t3);
    _t26 = (uint8_t*)"}\n\u{0}";
    fputs(_t26, _t3);
    fclose(_t3);
    return 1;
}

bool write_gitignore(void) {
    int64_t _t11;
    int64_t _t13;
    int64_t _t14;
    int64_t _t2;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    int64_t _t9;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t12;
    uint8_t* _t1;
    uint8_t* _t6;
    uint8_t* _t8;
    void* _t4;
    
    _t0 = (uint8_t*)".gitignore\u{0}";
    _t1 = (uint8_t*)"w\u{0}";
    fopen(_t0, _t1);
    _t3 = _t2;
    _t4 = (void*)0LL;
    _t5 = _t3 == _t4;
    if (_t5) goto L_then; else goto L_else;
L_then:
    return 0;
L_else:
    goto L_merge;
L_merge:
    _t6 = (uint8_t*)"/target\n\u{0}";
    fputs(_t6, _t3);
    _t8 = (uint8_t*)"*.o\n\u{0}";
    fputs(_t8, _t3);
    _t10 = (uint8_t*)"*.c\n\u{0}";
    fputs(_t10, _t3);
    _t12 = (uint8_t*)"Jxz.lock\n\u{0}";
    fputs(_t12, _t3);
    fclose(_t3);
    return 1;
}

int32_t init_project(uint8_t* _arg0) {
    bool _t23;
    bool _t24;
    bool _t28;
    bool _t29;
    bool _t33;
    int32_t _t13;
    int32_t _t25;
    int32_t _t30;
    int32_t _t50;
    int32_t _t7;
    int64_t _t10;
    int64_t _t12;
    int64_t _t16;
    int64_t _t19;
    int64_t _t22;
    int64_t _t27;
    int64_t _t2;
    int64_t _t32;
    int64_t _t35;
    int64_t _t37;
    int64_t _t39;
    int64_t _t41;
    int64_t _t43;
    int64_t _t45;
    int64_t _t47;
    int64_t _t49;
    int64_t _t4;
    int64_t _t6;
    int64_t _t8;
    uint32_t _t15;
    uint32_t _t18;
    uint32_t _t21;
    uint8_t* _t0;
    uint8_t* _t11;
    uint8_t* _t14;
    uint8_t* _t17;
    uint8_t* _t1;
    uint8_t* _t20;
    uint8_t* _t26;
    uint8_t* _t31;
    uint8_t* _t34;
    uint8_t* _t36;
    uint8_t* _t38;
    uint8_t* _t3;
    uint8_t* _t40;
    uint8_t* _t42;
    uint8_t* _t44;
    uint8_t* _t46;
    uint8_t* _t48;
    uint8_t* _t5;
    uint8_t* _t9;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"Creating new AetherLang project...\u{0}";
    puts(_t1);
    _t3 = (uint8_t*)"\u{0}";
    puts(_t3);
    _t5 = (uint8_t*)"Jxz.toml\u{0}";
    access(_t5, F_OK);
    _t7 = (int32_t)0LL;
    _t8 = _t6 == _t7;
    if (_t8) goto L_then; else goto L_else;
L_then:
    _t9 = (uint8_t*)"Error: Jxz.toml already exists in this directory\u{0}";
    puts(_t9);
    _t11 = (uint8_t*)"Use \'jxz init --force\' to overwrite\u{0}";
    puts(_t11);
    _t13 = (int32_t)1LL;
    return _t13;
L_else:
    goto L_merge;
L_merge:
    _t14 = (uint8_t*)"src\u{0}";
    _t15 = (uint32_t)493LL;
    mkdir(_t14, _t15);
    _t17 = (uint8_t*)"tests\u{0}";
    _t18 = (uint32_t)493LL;
    mkdir(_t17, _t18);
    _t20 = (uint8_t*)"target\u{0}";
    _t21 = (uint32_t)493LL;
    mkdir(_t20, _t21);
    _t23 = write_jxz_toml(_t0);
    _t24 = !_t23;
    if (_t24) goto L_then; else goto L_else;
L_then:
    _t25 = (int32_t)1LL;
    return _t25;
L_else:
    goto L_merge;
L_merge:
    _t26 = (uint8_t*)"  Created Jxz.toml\u{0}";
    puts(_t26);
    _t28 = write_main_aeth();
    _t29 = !_t28;
    if (_t29) goto L_then; else goto L_else;
L_then:
    _t30 = (int32_t)1LL;
    return _t30;
L_else:
    goto L_merge;
L_merge:
    _t31 = (uint8_t*)"  Created src/main.aeth\u{0}";
    puts(_t31);
    _t33 = write_gitignore();
    _t34 = (uint8_t*)"  Created .gitignore\u{0}";
    puts(_t34);
    _t36 = (uint8_t*)"\u{0}";
    puts(_t36);
    _t38 = (uint8_t*)"Project initialized successfully!\u{0}";
    puts(_t38);
    _t40 = (uint8_t*)"\u{0}";
    puts(_t40);
    _t42 = (uint8_t*)"Next steps:\u{0}";
    puts(_t42);
    _t44 = (uint8_t*)"  cd <project-name>\u{0}";
    puts(_t44);
    _t46 = (uint8_t*)"  jxz build\u{0}";
    puts(_t46);
    _t48 = (uint8_t*)"  jxz run\u{0}";
    puts(_t48);
    _t50 = (int32_t)0LL;
    return _t50;
}

