/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
int32_t install_package(uint8_t*, uint8_t*);
int32_t download_pkg(uint8_t*, uint8_t*);
int32_t extract_to_cellar(uint8_t*, uint8_t*);
int32_t link_package(uint8_t*, uint8_t*);
int32_t register_installed(uint8_t*, uint8_t*);
int32_t uninstall_package(uint8_t*);
int32_t upgrade_package(uint8_t*, uint8_t*);
int32_t upgrade_all(void);

int32_t install_package(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t10;
    int32_t _t11;
    int32_t _t15;
    int32_t _t18;
    int32_t _t19;
    int32_t _t20;
    int32_t _t24;
    int32_t _t27;
    int32_t _t28;
    int32_t _t29;
    int32_t _t33;
    int32_t _t36;
    int32_t _t42;
    int32_t _t9;
    int64_t _t12;
    int64_t _t14;
    int64_t _t17;
    int64_t _t21;
    int64_t _t23;
    int64_t _t26;
    int64_t _t30;
    int64_t _t32;
    int64_t _t35;
    int64_t _t38;
    int64_t _t39;
    int64_t _t3;
    int64_t _t41;
    int64_t _t4;
    int64_t _t6;
    int64_t _t8;
    uint8_t* _t0;
    uint8_t* _t13;
    uint8_t* _t16;
    uint8_t* _t1;
    uint8_t* _t22;
    uint8_t* _t25;
    uint8_t* _t2;
    uint8_t* _t31;
    uint8_t* _t34;
    uint8_t* _t37;
    uint8_t* _t40;
    uint8_t* _t5;
    uint8_t* _t7;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"==> Installing \u{0}";
    puts(_t2);
    puts(_t0);
    _t5 = (uint8_t*)"\u{0}";
    puts(_t5);
    _t7 = (uint8_t*)"==> Downloading...\u{0}";
    puts(_t7);
    _t9 = download_pkg(_t0, _t1);
    _t10 = _t9;
    _t11 = (int32_t)0LL;
    _t12 = _t10 != _t11;
    if (_t12) goto L_then; else goto L_else;
L_then:
    _t13 = (uint8_t*)"Error: Download failed\u{0}";
    puts(_t13);
    _t15 = (int32_t)1LL;
    return _t15;
L_else:
    goto L_merge;
L_merge:
    _t16 = (uint8_t*)"==> Extracting to Cellar...\u{0}";
    puts(_t16);
    _t18 = extract_to_cellar(_t0, _t1);
    _t19 = _t18;
    _t20 = (int32_t)0LL;
    _t21 = _t19 != _t20;
    if (_t21) goto L_then; else goto L_else;
L_then:
    _t22 = (uint8_t*)"Error: Extraction failed\u{0}";
    puts(_t22);
    _t24 = (int32_t)1LL;
    return _t24;
L_else:
    goto L_merge;
L_merge:
    _t25 = (uint8_t*)"==> Linking...\u{0}";
    puts(_t25);
    _t27 = link_package(_t0, _t1);
    _t28 = _t27;
    _t29 = (int32_t)0LL;
    _t30 = _t28 != _t29;
    if (_t30) goto L_then; else goto L_else;
L_then:
    _t31 = (uint8_t*)"Error: Linking failed\u{0}";
    puts(_t31);
    _t33 = (int32_t)1LL;
    return _t33;
L_else:
    goto L_merge;
L_merge:
    _t34 = (uint8_t*)"==> Registering...\u{0}";
    puts(_t34);
    _t36 = register_installed(_t0, _t1);
    _t37 = (uint8_t*)"==> \u{0}";
    puts(_t37);
    puts(_t0);
    _t40 = (uint8_t*)" installed successfully!\u{0}";
    puts(_t40);
    _t42 = (int32_t)0LL;
    return _t42;
}

int32_t download_pkg(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t3;
    int32_t _t4;
    int32_t _t6;
    int32_t _t7;
    int64_t _t10;
    int64_t _t12;
    int64_t _t13;
    int64_t _t14;
    int64_t _t18;
    int64_t _t19;
    int64_t _t21;
    int64_t _t22;
    int64_t _t24;
    int64_t _t25;
    int64_t _t27;
    int64_t _t28;
    int64_t _t2;
    int64_t _t30;
    int64_t _t31;
    int64_t _t32;
    int64_t _t5;
    uint64_t _t11;
    uint64_t _t8;
    uint64_t _t9;
    uint8_t* _t0;
    uint8_t* _t15;
    uint8_t* _t16;
    uint8_t* _t17;
    uint8_t* _t1;
    uint8_t* _t20;
    uint8_t* _t23;
    uint8_t* _t26;
    uint8_t* _t29;
    void* _t33;
    
    _t0 = _arg0;
    _t1 = _arg1;
    strlen(_t0);
    _t3 = (int32_t)_t2;
    _t4 = _t3;
    strlen(_t1);
    _t6 = (int32_t)_t5;
    _t7 = _t6;
    _t8 = (uint64_t)_t4;
    _t9 = (uint64_t)_t7;
    _t10 = _t8 + _t9;
    _t11 = (uint64_t)200LL;
    _t12 = _t10 + _t11;
    _t13 = (int64_t)_t12;
    malloc(_t13);
    _t15 = (uint8_t*)_t14;
    _t16 = _t15;
    _t17 = (uint8_t*)"curl -sL -o ~/.jxz/cache/\u{0}";
    strcpy(_t16, _t17);
    strcat(_t16, _t0);
    _t20 = (uint8_t*)"-\u{0}";
    strcat(_t16, _t20);
    strcat(_t16, _t1);
    _t23 = (uint8_t*)".tar.gz https://registry.aetherlang.org/packages/\u{0}";
    strcat(_t16, _t23);
    strcat(_t16, _t0);
    _t26 = (uint8_t*)"/\u{0}";
    strcat(_t16, _t26);
    strcat(_t16, _t1);
    _t29 = (uint8_t*)".tar.gz 2>/dev/null\u{0}";
    strcat(_t16, _t29);
    system(_t16);
    _t32 = _t31;
    _t33 = (void*)_t16;
    free(_t33);
    return _t32;
}

int32_t extract_to_cellar(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t3;
    int32_t _t4;
    int32_t _t6;
    int32_t _t7;
    int64_t _t10;
    int64_t _t12;
    int64_t _t13;
    int64_t _t14;
    int64_t _t18;
    int64_t _t19;
    int64_t _t21;
    int64_t _t22;
    int64_t _t25;
    int64_t _t28;
    int64_t _t29;
    int64_t _t2;
    int64_t _t31;
    int64_t _t32;
    int64_t _t33;
    int64_t _t37;
    int64_t _t38;
    int64_t _t40;
    int64_t _t41;
    int64_t _t43;
    int64_t _t44;
    int64_t _t46;
    int64_t _t47;
    int64_t _t48;
    int64_t _t49;
    int64_t _t5;
    uint64_t _t11;
    uint64_t _t23;
    uint64_t _t24;
    uint64_t _t26;
    uint64_t _t27;
    uint64_t _t30;
    uint64_t _t8;
    uint64_t _t9;
    uint8_t* _t0;
    uint8_t* _t15;
    uint8_t* _t16;
    uint8_t* _t17;
    uint8_t* _t1;
    uint8_t* _t20;
    uint8_t* _t34;
    uint8_t* _t35;
    uint8_t* _t36;
    uint8_t* _t39;
    uint8_t* _t42;
    uint8_t* _t45;
    void* _t50;
    void* _t51;
    
    _t0 = _arg0;
    _t1 = _arg1;
    strlen(_t0);
    _t3 = (int32_t)_t2;
    _t4 = _t3;
    strlen(_t1);
    _t6 = (int32_t)_t5;
    _t7 = _t6;
    _t8 = (uint64_t)_t4;
    _t9 = (uint64_t)_t7;
    _t10 = _t8 + _t9;
    _t11 = (uint64_t)50LL;
    _t12 = _t10 + _t11;
    _t13 = (int64_t)_t12;
    malloc(_t13);
    _t15 = (uint8_t*)_t14;
    _t16 = _t15;
    _t17 = (uint8_t*)"~/.jxz/Cellar/\u{0}";
    strcpy(_t16, _t17);
    strcat(_t16, _t0);
    _t20 = (uint8_t*)"/\u{0}";
    strcat(_t16, _t20);
    strcat(_t16, _t1);
    _t23 = (uint64_t)_t4;
    _t24 = (uint64_t)2LL;
    _t25 = _t23 * _t24;
    _t26 = (uint64_t)_t7;
    _t27 = (uint64_t)2LL;
    _t28 = _t26 * _t27;
    _t29 = _t25 + _t28;
    _t30 = (uint64_t)150LL;
    _t31 = _t29 + _t30;
    _t32 = (int64_t)_t31;
    malloc(_t32);
    _t34 = (uint8_t*)_t33;
    _t35 = _t34;
    _t36 = (uint8_t*)"mkdir -p \u{0}";
    strcpy(_t35, _t36);
    strcat(_t35, _t16);
    _t39 = (uint8_t*)" && tar -xzf ~/.jxz/cache/\u{0}";
    strcat(_t35, _t39);
    strcat(_t35, _t0);
    _t42 = (uint8_t*)"-\u{0}";
    strcat(_t35, _t42);
    strcat(_t35, _t1);
    _t45 = (uint8_t*)".tar.gz -C \u{0}";
    strcat(_t35, _t45);
    strcat(_t35, _t16);
    system(_t35);
    _t49 = _t48;
    _t50 = (void*)_t35;
    free(_t50);
    _t51 = (void*)_t16;
    free(_t51);
    return _t49;
}

int32_t link_package(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t3;
    int32_t _t4;
    int32_t _t6;
    int32_t _t7;
    int64_t _t10;
    int64_t _t12;
    int64_t _t13;
    int64_t _t14;
    int64_t _t18;
    int64_t _t19;
    int64_t _t21;
    int64_t _t22;
    int64_t _t24;
    int64_t _t25;
    int64_t _t26;
    int64_t _t2;
    int64_t _t5;
    uint64_t _t11;
    uint64_t _t8;
    uint64_t _t9;
    uint8_t* _t0;
    uint8_t* _t15;
    uint8_t* _t16;
    uint8_t* _t17;
    uint8_t* _t1;
    uint8_t* _t20;
    uint8_t* _t23;
    void* _t27;
    
    _t0 = _arg0;
    _t1 = _arg1;
    strlen(_t0);
    _t3 = (int32_t)_t2;
    _t4 = _t3;
    strlen(_t1);
    _t6 = (int32_t)_t5;
    _t7 = _t6;
    _t8 = (uint64_t)_t4;
    _t9 = (uint64_t)_t7;
    _t10 = _t8 + _t9;
    _t11 = (uint64_t)100LL;
    _t12 = _t10 + _t11;
    _t13 = (int64_t)_t12;
    malloc(_t13);
    _t15 = (uint8_t*)_t14;
    _t16 = _t15;
    _t17 = (uint8_t*)"ln -sf ~/.jxz/Cellar/\u{0}";
    strcpy(_t16, _t17);
    strcat(_t16, _t0);
    _t20 = (uint8_t*)"/\u{0}";
    strcat(_t16, _t20);
    strcat(_t16, _t1);
    _t23 = (uint8_t*)"/bin/* ~/.jxz/bin/ 2>/dev/null\u{0}";
    strcat(_t16, _t23);
    system(_t16);
    _t26 = _t25;
    _t27 = (void*)_t16;
    free(_t27);
    return _t26;
}

int32_t register_installed(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t3;
    int32_t _t4;
    int32_t _t6;
    int32_t _t7;
    int64_t _t10;
    int64_t _t12;
    int64_t _t13;
    int64_t _t14;
    int64_t _t18;
    int64_t _t19;
    int64_t _t21;
    int64_t _t22;
    int64_t _t24;
    int64_t _t25;
    int64_t _t26;
    int64_t _t2;
    int64_t _t5;
    uint64_t _t11;
    uint64_t _t8;
    uint64_t _t9;
    uint8_t* _t0;
    uint8_t* _t15;
    uint8_t* _t16;
    uint8_t* _t17;
    uint8_t* _t1;
    uint8_t* _t20;
    uint8_t* _t23;
    void* _t27;
    
    _t0 = _arg0;
    _t1 = _arg1;
    strlen(_t0);
    _t3 = (int32_t)_t2;
    _t4 = _t3;
    strlen(_t1);
    _t6 = (int32_t)_t5;
    _t7 = _t6;
    _t8 = (uint64_t)_t4;
    _t9 = (uint64_t)_t7;
    _t10 = _t8 + _t9;
    _t11 = (uint64_t)80LL;
    _t12 = _t10 + _t11;
    _t13 = (int64_t)_t12;
    malloc(_t13);
    _t15 = (uint8_t*)_t14;
    _t16 = _t15;
    _t17 = (uint8_t*)"echo \'\u{0}";
    strcpy(_t16, _t17);
    strcat(_t16, _t0);
    _t20 = (uint8_t*)" \u{0}";
    strcat(_t16, _t20);
    strcat(_t16, _t1);
    _t23 = (uint8_t*)"\' >> ~/.jxz/db/installed.db\u{0}";
    strcat(_t16, _t23);
    system(_t16);
    _t26 = _t25;
    _t27 = (void*)_t16;
    free(_t27);
    return _t26;
}

int32_t uninstall_package(uint8_t* _arg0) {
    int32_t _t10;
    int32_t _t30;
    int32_t _t9;
    int64_t _t13;
    int64_t _t14;
    int64_t _t15;
    int64_t _t19;
    int64_t _t20;
    int64_t _t21;
    int64_t _t24;
    int64_t _t26;
    int64_t _t27;
    int64_t _t29;
    int64_t _t2;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    int64_t _t8;
    uint64_t _t11;
    uint64_t _t12;
    uint8_t* _t0;
    uint8_t* _t16;
    uint8_t* _t17;
    uint8_t* _t18;
    uint8_t* _t1;
    uint8_t* _t23;
    uint8_t* _t25;
    uint8_t* _t28;
    uint8_t* _t4;
    uint8_t* _t6;
    void* _t22;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"==> Uninstalling \u{0}";
    puts(_t1);
    puts(_t0);
    _t4 = (uint8_t*)"\u{0}";
    puts(_t4);
    _t6 = (uint8_t*)"==> Removing from Cellar...\u{0}";
    puts(_t6);
    strlen(_t0);
    _t9 = (int32_t)_t8;
    _t10 = _t9;
    _t11 = (uint64_t)_t10;
    _t12 = (uint64_t)50LL;
    _t13 = _t11 + _t12;
    _t14 = (int64_t)_t13;
    malloc(_t14);
    _t16 = (uint8_t*)_t15;
    _t17 = _t16;
    _t18 = (uint8_t*)"rm -rf ~/.jxz/Cellar/\u{0}";
    strcpy(_t17, _t18);
    strcat(_t17, _t0);
    system(_t17);
    _t22 = (void*)_t17;
    free(_t22);
    _t23 = (uint8_t*)"==> Removing symlinks...\u{0}";
    puts(_t23);
    _t25 = (uint8_t*)"==> \u{0}";
    puts(_t25);
    puts(_t0);
    _t28 = (uint8_t*)" uninstalled\u{0}";
    puts(_t28);
    _t30 = (int32_t)0LL;
    return _t30;
}

int32_t upgrade_package(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t12;
    int32_t _t13;
    int64_t _t11;
    int64_t _t3;
    int64_t _t4;
    int64_t _t6;
    int64_t _t7;
    int64_t _t9;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t1;
    uint8_t* _t2;
    uint8_t* _t5;
    uint8_t* _t8;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"==> Upgrading \u{0}";
    puts(_t2);
    puts(_t0);
    _t5 = (uint8_t*)" to \u{0}";
    puts(_t5);
    puts(_t1);
    _t8 = (uint8_t*)"\u{0}";
    puts(_t8);
    _t10 = (uint8_t*)"==> Unlinking old version...\u{0}";
    puts(_t10);
    _t12 = install_package(_t0, _t1);
    _t13 = _t12;
    return _t13;
}

int32_t upgrade_all(void) {
    int32_t _t4;
    int64_t _t1;
    int64_t _t3;
    uint8_t* _t0;
    uint8_t* _t2;
    
    _t0 = (uint8_t*)"==> Upgrading all packages...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"==> All packages up to date\u{0}";
    puts(_t2);
    _t4 = (int32_t)0LL;
    return _t4;
}

