/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
void print_help(void);
void print_version(void);
int32_t cmd_init(void);
int32_t cmd_build(void);
int32_t cmd_run(void);
int32_t cmd_test(void);
int32_t cmd_add(uint8_t*);
int32_t cmd_remove(uint8_t*);
int32_t cmd_update(void);
int32_t main(int32_t, uint8_t**);

void print_help(void) {
    int64_t _t11;
    int64_t _t13;
    int64_t _t15;
    int64_t _t17;
    int64_t _t19;
    int64_t _t1;
    int64_t _t21;
    int64_t _t23;
    int64_t _t25;
    int64_t _t27;
    int64_t _t29;
    int64_t _t31;
    int64_t _t33;
    int64_t _t35;
    int64_t _t37;
    int64_t _t39;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    int64_t _t9;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t12;
    uint8_t* _t14;
    uint8_t* _t16;
    uint8_t* _t18;
    uint8_t* _t20;
    uint8_t* _t22;
    uint8_t* _t24;
    uint8_t* _t26;
    uint8_t* _t28;
    uint8_t* _t2;
    uint8_t* _t30;
    uint8_t* _t32;
    uint8_t* _t34;
    uint8_t* _t36;
    uint8_t* _t38;
    uint8_t* _t4;
    uint8_t* _t6;
    uint8_t* _t8;
    
    _t0 = (uint8_t*)"JXZ - AetherLang Package Manager\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"\u{0}";
    puts(_t2);
    _t4 = (uint8_t*)"USAGE:\u{0}";
    puts(_t4);
    _t6 = (uint8_t*)"    jxz <COMMAND> [OPTIONS]\u{0}";
    puts(_t6);
    _t8 = (uint8_t*)"\u{0}";
    puts(_t8);
    _t10 = (uint8_t*)"COMMANDS:\u{0}";
    puts(_t10);
    _t12 = (uint8_t*)"    init        Create a new project\u{0}";
    puts(_t12);
    _t14 = (uint8_t*)"    build       Build the project\u{0}";
    puts(_t14);
    _t16 = (uint8_t*)"    run         Run the project\u{0}";
    puts(_t16);
    _t18 = (uint8_t*)"    test        Run tests\u{0}";
    puts(_t18);
    _t20 = (uint8_t*)"    add         Add a dependency\u{0}";
    puts(_t20);
    _t22 = (uint8_t*)"    remove      Remove a dependency\u{0}";
    puts(_t22);
    _t24 = (uint8_t*)"    update      Update dependencies\u{0}";
    puts(_t24);
    _t26 = (uint8_t*)"    help        Show this help message\u{0}";
    puts(_t26);
    _t28 = (uint8_t*)"    version     Show version\u{0}";
    puts(_t28);
    _t30 = (uint8_t*)"\u{0}";
    puts(_t30);
    _t32 = (uint8_t*)"OPTIONS:\u{0}";
    puts(_t32);
    _t34 = (uint8_t*)"    -h, --help      Show help\u{0}";
    puts(_t34);
    _t36 = (uint8_t*)"    -V, --version   Show version\u{0}";
    puts(_t36);
    _t38 = (uint8_t*)"    -v, --verbose   Verbose output\u{0}";
    puts(_t38);
    return;
}

void print_version(void) {
    int64_t _t1;
    uint8_t* _t0;
    
    _t0 = (uint8_t*)"jxz 0.1.0\u{0}";
    puts(_t0);
    return;
}

int32_t cmd_init(void) {
    int32_t _t10;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    int64_t _t9;
    uint8_t* _t0;
    uint8_t* _t2;
    uint8_t* _t4;
    uint8_t* _t6;
    uint8_t* _t8;
    
    _t0 = (uint8_t*)"Creating new AetherLang project...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"  Created Jxz.toml\u{0}";
    puts(_t2);
    _t4 = (uint8_t*)"  Created src/main.aeth\u{0}";
    puts(_t4);
    _t6 = (uint8_t*)"\u{0}";
    puts(_t6);
    _t8 = (uint8_t*)"Project initialized successfully!\u{0}";
    puts(_t8);
    _t10 = (int32_t)0LL;
    return _t10;
}

int32_t cmd_build(void) {
    int32_t _t6;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    uint8_t* _t0;
    uint8_t* _t2;
    uint8_t* _t4;
    
    _t0 = (uint8_t*)"Building project...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"  Compiling src/main.aeth\u{0}";
    puts(_t2);
    _t4 = (uint8_t*)"  Finished release build\u{0}";
    puts(_t4);
    _t6 = (int32_t)0LL;
    return _t6;
}

int32_t cmd_run(void) {
    int32_t _t2;
    int32_t _t5;
    int64_t _t1;
    int64_t _t4;
    uint8_t* _t0;
    uint8_t* _t3;
    
    _t0 = (uint8_t*)"Building and running project...\u{0}";
    puts(_t0);
    _t2 = cmd_build();
    _t3 = (uint8_t*)"Running ./target/main\u{0}";
    puts(_t3);
    _t5 = (int32_t)0LL;
    return _t5;
}

int32_t cmd_test(void) {
    int32_t _t4;
    int64_t _t1;
    int64_t _t3;
    uint8_t* _t0;
    uint8_t* _t2;
    
    _t0 = (uint8_t*)"Running tests...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"  0 tests passed, 0 failed\u{0}";
    puts(_t2);
    _t4 = (int32_t)0LL;
    return _t4;
}

int32_t cmd_add(uint8_t* _arg0) {
    int32_t _t3;
    int64_t _t2;
    uint8_t* _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"Adding dependency...\u{0}";
    puts(_t1);
    _t3 = (int32_t)0LL;
    return _t3;
}

int32_t cmd_remove(uint8_t* _arg0) {
    int32_t _t3;
    int64_t _t2;
    uint8_t* _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"Removing dependency...\u{0}";
    puts(_t1);
    _t3 = (int32_t)0LL;
    return _t3;
}

int32_t cmd_update(void) {
    int32_t _t2;
    int64_t _t1;
    uint8_t* _t0;
    
    _t0 = (uint8_t*)"Updating dependencies...\u{0}";
    puts(_t0);
    _t2 = (int32_t)0LL;
    return _t2;
}

int32_t main(int32_t _arg0, uint8_t** _arg1) {
    int32_t _t0;
    int32_t _t10;
    int32_t _t14;
    int32_t _t19;
    int32_t _t22;
    int32_t _t25;
    int32_t _t29;
    int32_t _t2;
    int32_t _t34;
    int32_t _t37;
    int32_t _t40;
    int32_t _t42;
    int32_t _t45;
    int32_t _t47;
    int32_t _t4;
    int32_t _t50;
    int32_t _t52;
    int32_t _t55;
    int32_t _t57;
    int32_t _t60;
    int32_t _t62;
    int32_t _t66;
    int32_t _t70;
    int32_t _t73;
    int32_t _t74;
    int32_t _t78;
    int32_t _t82;
    int32_t _t85;
    int32_t _t86;
    int32_t _t91;
    int64_t _t11;
    int64_t _t13;
    int64_t _t15;
    int64_t _t16;
    int64_t _t18;
    int64_t _t20;
    int64_t _t21;
    int64_t _t24;
    int64_t _t26;
    int64_t _t28;
    int64_t _t30;
    int64_t _t31;
    int64_t _t33;
    int64_t _t35;
    int64_t _t36;
    int64_t _t39;
    int64_t _t3;
    int64_t _t41;
    int64_t _t44;
    int64_t _t46;
    int64_t _t49;
    int64_t _t51;
    int64_t _t54;
    int64_t _t56;
    int64_t _t59;
    int64_t _t61;
    int64_t _t63;
    int64_t _t65;
    int64_t _t67;
    int64_t _t69;
    int64_t _t75;
    int64_t _t77;
    int64_t _t79;
    int64_t _t81;
    int64_t _t88;
    int64_t _t90;
    int64_t _t9;
    uint8_t* _t12;
    uint8_t* _t17;
    uint8_t* _t23;
    uint8_t* _t27;
    uint8_t* _t32;
    uint8_t* _t38;
    uint8_t* _t43;
    uint8_t* _t48;
    uint8_t* _t53;
    uint8_t* _t58;
    uint8_t* _t64;
    uint8_t* _t68;
    uint8_t* _t6;
    uint8_t* _t72;
    uint8_t* _t76;
    uint8_t* _t7;
    uint8_t* _t80;
    uint8_t* _t84;
    uint8_t* _t87;
    uint8_t* _t89;
    uint8_t* _t8;
    uint8_t** _t1;
    uint8_t** _t5;
    uint8_t** _t71;
    uint8_t** _t83;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (int32_t)2LL;
    _t3 = _t0 < _t2;
    if (_t3) goto L_then; else goto L_else;
L_then:
    print_help();
    _t4 = (int32_t)0LL;
    return _t4;
L_else:
    goto L_merge;
L_merge:
    _t5 = &_t1[1LL];
    _t6 = *_t5;
    _t7 = _t6;
    _t8 = (uint8_t*)"-h\u{0}";
    strcmp(_t7, _t8);
    _t10 = (int32_t)0LL;
    _t11 = _t9 == _t10;
    _t12 = (uint8_t*)"--help\u{0}";
    strcmp(_t7, _t12);
    _t14 = (int32_t)0LL;
    _t15 = _t13 == _t14;
    _t16 = _t11 || _t15;
    _t17 = (uint8_t*)"help\u{0}";
    strcmp(_t7, _t17);
    _t19 = (int32_t)0LL;
    _t20 = _t18 == _t19;
    _t21 = _t16 || _t20;
    if (_t21) goto L_then; else goto L_else;
L_then:
    print_help();
    _t22 = (int32_t)0LL;
    return _t22;
L_else:
    goto L_merge;
L_merge:
    _t23 = (uint8_t*)"-V\u{0}";
    strcmp(_t7, _t23);
    _t25 = (int32_t)0LL;
    _t26 = _t24 == _t25;
    _t27 = (uint8_t*)"--version\u{0}";
    strcmp(_t7, _t27);
    _t29 = (int32_t)0LL;
    _t30 = _t28 == _t29;
    _t31 = _t26 || _t30;
    _t32 = (uint8_t*)"version\u{0}";
    strcmp(_t7, _t32);
    _t34 = (int32_t)0LL;
    _t35 = _t33 == _t34;
    _t36 = _t31 || _t35;
    if (_t36) goto L_then; else goto L_else;
L_then:
    print_version();
    _t37 = (int32_t)0LL;
    return _t37;
L_else:
    goto L_merge;
L_merge:
    _t38 = (uint8_t*)"init\u{0}";
    strcmp(_t7, _t38);
    _t40 = (int32_t)0LL;
    _t41 = _t39 == _t40;
    if (_t41) goto L_then; else goto L_else;
L_then:
    _t42 = cmd_init();
    return _t42;
L_else:
    goto L_merge;
L_merge:
    _t43 = (uint8_t*)"build\u{0}";
    strcmp(_t7, _t43);
    _t45 = (int32_t)0LL;
    _t46 = _t44 == _t45;
    if (_t46) goto L_then; else goto L_else;
L_then:
    _t47 = cmd_build();
    return _t47;
L_else:
    goto L_merge;
L_merge:
    _t48 = (uint8_t*)"run\u{0}";
    strcmp(_t7, _t48);
    _t50 = (int32_t)0LL;
    _t51 = _t49 == _t50;
    if (_t51) goto L_then; else goto L_else;
L_then:
    _t52 = cmd_run();
    return _t52;
L_else:
    goto L_merge;
L_merge:
    _t53 = (uint8_t*)"test\u{0}";
    strcmp(_t7, _t53);
    _t55 = (int32_t)0LL;
    _t56 = _t54 == _t55;
    if (_t56) goto L_then; else goto L_else;
L_then:
    _t57 = cmd_test();
    return _t57;
L_else:
    goto L_merge;
L_merge:
    _t58 = (uint8_t*)"add\u{0}";
    strcmp(_t7, _t58);
    _t60 = (int32_t)0LL;
    _t61 = _t59 == _t60;
    if (_t61) goto L_then; else goto L_else;
L_then:
    _t62 = (int32_t)3LL;
    _t63 = _t0 < _t62;
    if (_t63) goto L_then; else goto L_else;
L_else:
    goto L_merge;
L_merge:
    _t64 = (uint8_t*)"remove\u{0}";
    strcmp(_t7, _t64);
    _t66 = (int32_t)0LL;
    _t67 = _t65 == _t66;
    if (_t67) goto L_then; else goto L_else;
L_then:
    _t68 = (uint8_t*)"Error: missing package name\u{0}";
    puts(_t68);
    _t70 = (int32_t)1LL;
    return _t70;
L_else:
    goto L_merge;
L_merge:
    _t71 = &_t1[2LL];
    _t72 = *_t71;
    _t73 = cmd_add(_t72);
    return _t73;
L_then:
    _t74 = (int32_t)3LL;
    _t75 = _t0 < _t74;
    if (_t75) goto L_then; else goto L_else;
L_else:
    goto L_merge;
L_merge:
    _t76 = (uint8_t*)"update\u{0}";
    strcmp(_t7, _t76);
    _t78 = (int32_t)0LL;
    _t79 = _t77 == _t78;
    if (_t79) goto L_then; else goto L_else;
L_then:
    _t80 = (uint8_t*)"Error: missing package name\u{0}";
    puts(_t80);
    _t82 = (int32_t)1LL;
    return _t82;
L_else:
    goto L_merge;
L_merge:
    _t83 = &_t1[2LL];
    _t84 = *_t83;
    _t85 = cmd_remove(_t84);
    return _t85;
L_then:
    _t86 = cmd_update();
    return _t86;
L_else:
    goto L_merge;
L_merge:
    _t87 = (uint8_t*)"Error: unknown command\u{0}";
    puts(_t87);
    _t89 = (uint8_t*)"Run \'jxz help\' for usage\u{0}";
    puts(_t89);
    _t91 = (int32_t)1LL;
    return _t91;
}

