/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
int32_t detect_platform(void);
uint8_t* platform_name(int32_t);
uint8_t* jxz_prefix(void);
uint8_t* jxz_bin(void);
uint8_t* jxz_lib(void);
uint8_t* jxz_cellar(void);
uint8_t* jxz_cache(void);
uint8_t* jxz_db(void);
bool jxz_setup_dirs(void);
void jxz_print_config(void);

int32_t detect_platform(void) {
    int32_t _t2;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    int64_t _t6;
    int64_t _t8;
    uint8_t* _t0;
    uint8_t* _t4;
    uint8_t* _t7;
    
    _t0 = (uint8_t*)"/usr/bin/sw_vers\u{0}";
    access(_t0, F_OK);
    _t2 = (int32_t)0LL;
    _t3 = _t1 == _t2;
    if (_t3) goto L_then; else goto L_else;
L_then:
    return PLATFORM_MACOS;
L_else:
    goto L_merge;
L_merge:
    _t4 = (uint8_t*)"WINDIR\u{0}";
    getenv(_t4);
    _t6 = _t5;
    _t7 = (uint8_t*)0LL;
    _t8 = _t6 != _t7;
    if (_t8) goto L_then; else goto L_else;
L_then:
    return PLATFORM_WINDOWS;
L_else:
    goto L_merge;
L_merge:
    return PLATFORM_LINUX;
}

uint8_t* platform_name(int32_t _arg0) {
    int32_t _t0;
    int64_t _t1;
    int64_t _t3;
    uint8_t* _t2;
    uint8_t* _t4;
    uint8_t* _t5;
    
    _t0 = _arg0;
    _t1 = _t0 == PLATFORM_MACOS;
    if (_t1) goto L_then; else goto L_else;
L_then:
    _t2 = (uint8_t*)"macos\u{0}";
    return _t2;
L_else:
    _t3 = _t0 == PLATFORM_WINDOWS;
    if (_t3) goto L_then; else goto L_else;
L_merge:
    _t4 = (uint8_t*)"linux\u{0}";
    return _t4;
L_then:
    _t5 = (uint8_t*)"windows\u{0}";
    return _t5;
L_else:
    goto L_merge;
L_merge:
    goto L_merge;
}

uint8_t* jxz_prefix(void) {
    int32_t _t11;
    int32_t _t12;
    int64_t _t10;
    int64_t _t15;
    int64_t _t16;
    int64_t _t17;
    int64_t _t1;
    int64_t _t20;
    int64_t _t22;
    int64_t _t2;
    int64_t _t4;
    int64_t _t6;
    int64_t _t8;
    uint64_t _t13;
    uint64_t _t14;
    uint8_t* _t0;
    uint8_t* _t18;
    uint8_t* _t19;
    uint8_t* _t21;
    uint8_t* _t3;
    uint8_t* _t5;
    uint8_t* _t7;
    uint8_t* _t9;
    
    _t0 = (uint8_t*)"HOME\u{0}";
    getenv(_t0);
    _t2 = _t1;
    _t3 = (uint8_t*)0LL;
    _t4 = _t2 == _t3;
    if (_t4) goto L_then; else goto L_else;
L_then:
    _t5 = (uint8_t*)"USERPROFILE\u{0}";
    getenv(_t5);
    _t2 = _t6;
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    _t7 = (uint8_t*)0LL;
    _t8 = _t2 == _t7;
    if (_t8) goto L_then; else goto L_else;
L_then:
    _t9 = (uint8_t*)"/tmp/jxz\u{0}";
    return _t9;
L_else:
    goto L_merge;
L_merge:
    strlen(_t2);
    _t11 = (int32_t)_t10;
    _t12 = _t11;
    _t13 = (uint64_t)_t12;
    _t14 = (uint64_t)10LL;
    _t15 = _t13 + _t14;
    _t16 = (int64_t)_t15;
    malloc(_t16);
    _t18 = (uint8_t*)_t17;
    _t19 = _t18;
    strcpy(_t19, _t2);
    _t21 = (uint8_t*)"/.jxz\u{0}";
    strcat(_t19, _t21);
    return _t19;
}

uint8_t* jxz_bin(void) {
    int32_t _t3;
    int32_t _t4;
    int64_t _t12;
    int64_t _t14;
    int64_t _t2;
    int64_t _t7;
    int64_t _t8;
    int64_t _t9;
    uint64_t _t5;
    uint64_t _t6;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t11;
    uint8_t* _t13;
    uint8_t* _t1;
    
    _t0 = jxz_prefix();
    _t1 = _t0;
    strlen(_t1);
    _t3 = (int32_t)_t2;
    _t4 = _t3;
    _t5 = (uint64_t)_t4;
    _t6 = (uint64_t)10LL;
    _t7 = _t5 + _t6;
    _t8 = (int64_t)_t7;
    malloc(_t8);
    _t10 = (uint8_t*)_t9;
    _t11 = _t10;
    strcpy(_t11, _t1);
    _t13 = (uint8_t*)"/bin\u{0}";
    strcat(_t11, _t13);
    return _t11;
}

uint8_t* jxz_lib(void) {
    int32_t _t3;
    int32_t _t4;
    int64_t _t12;
    int64_t _t14;
    int64_t _t2;
    int64_t _t7;
    int64_t _t8;
    int64_t _t9;
    uint64_t _t5;
    uint64_t _t6;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t11;
    uint8_t* _t13;
    uint8_t* _t1;
    
    _t0 = jxz_prefix();
    _t1 = _t0;
    strlen(_t1);
    _t3 = (int32_t)_t2;
    _t4 = _t3;
    _t5 = (uint64_t)_t4;
    _t6 = (uint64_t)10LL;
    _t7 = _t5 + _t6;
    _t8 = (int64_t)_t7;
    malloc(_t8);
    _t10 = (uint8_t*)_t9;
    _t11 = _t10;
    strcpy(_t11, _t1);
    _t13 = (uint8_t*)"/lib\u{0}";
    strcat(_t11, _t13);
    return _t11;
}

uint8_t* jxz_cellar(void) {
    int32_t _t3;
    int32_t _t4;
    int64_t _t12;
    int64_t _t14;
    int64_t _t2;
    int64_t _t7;
    int64_t _t8;
    int64_t _t9;
    uint64_t _t5;
    uint64_t _t6;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t11;
    uint8_t* _t13;
    uint8_t* _t1;
    
    _t0 = jxz_prefix();
    _t1 = _t0;
    strlen(_t1);
    _t3 = (int32_t)_t2;
    _t4 = _t3;
    _t5 = (uint64_t)_t4;
    _t6 = (uint64_t)15LL;
    _t7 = _t5 + _t6;
    _t8 = (int64_t)_t7;
    malloc(_t8);
    _t10 = (uint8_t*)_t9;
    _t11 = _t10;
    strcpy(_t11, _t1);
    _t13 = (uint8_t*)"/Cellar\u{0}";
    strcat(_t11, _t13);
    return _t11;
}

uint8_t* jxz_cache(void) {
    int32_t _t3;
    int32_t _t4;
    int64_t _t12;
    int64_t _t14;
    int64_t _t2;
    int64_t _t7;
    int64_t _t8;
    int64_t _t9;
    uint64_t _t5;
    uint64_t _t6;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t11;
    uint8_t* _t13;
    uint8_t* _t1;
    
    _t0 = jxz_prefix();
    _t1 = _t0;
    strlen(_t1);
    _t3 = (int32_t)_t2;
    _t4 = _t3;
    _t5 = (uint64_t)_t4;
    _t6 = (uint64_t)15LL;
    _t7 = _t5 + _t6;
    _t8 = (int64_t)_t7;
    malloc(_t8);
    _t10 = (uint8_t*)_t9;
    _t11 = _t10;
    strcpy(_t11, _t1);
    _t13 = (uint8_t*)"/cache\u{0}";
    strcat(_t11, _t13);
    return _t11;
}

uint8_t* jxz_db(void) {
    int32_t _t3;
    int32_t _t4;
    int64_t _t12;
    int64_t _t14;
    int64_t _t2;
    int64_t _t7;
    int64_t _t8;
    int64_t _t9;
    uint64_t _t5;
    uint64_t _t6;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t11;
    uint8_t* _t13;
    uint8_t* _t1;
    
    _t0 = jxz_prefix();
    _t1 = _t0;
    strlen(_t1);
    _t3 = (int32_t)_t2;
    _t4 = _t3;
    _t5 = (uint64_t)_t4;
    _t6 = (uint64_t)10LL;
    _t7 = _t5 + _t6;
    _t8 = (int64_t)_t7;
    malloc(_t8);
    _t10 = (uint8_t*)_t9;
    _t11 = _t10;
    strcpy(_t11, _t1);
    _t13 = (uint8_t*)"/db\u{0}";
    strcat(_t11, _t13);
    return _t11;
}

bool jxz_setup_dirs(void) {
    int64_t _t11;
    int64_t _t14;
    int64_t _t17;
    int64_t _t1;
    int64_t _t20;
    int64_t _t22;
    int64_t _t5;
    int64_t _t8;
    uint32_t _t10;
    uint32_t _t13;
    uint32_t _t16;
    uint32_t _t19;
    uint32_t _t4;
    uint32_t _t7;
    uint8_t* _t0;
    uint8_t* _t12;
    uint8_t* _t15;
    uint8_t* _t18;
    uint8_t* _t21;
    uint8_t* _t2;
    uint8_t* _t3;
    uint8_t* _t6;
    uint8_t* _t9;
    
    _t0 = (uint8_t*)"Setting up JXZ directories...\u{0}";
    puts(_t0);
    _t2 = jxz_prefix();
    _t3 = _t2;
    _t4 = (uint32_t)493LL;
    mkdir(_t3, _t4);
    _t6 = jxz_bin();
    _t7 = (uint32_t)493LL;
    mkdir(_t6, _t7);
    _t9 = jxz_lib();
    _t10 = (uint32_t)493LL;
    mkdir(_t9, _t10);
    _t12 = jxz_cellar();
    _t13 = (uint32_t)493LL;
    mkdir(_t12, _t13);
    _t15 = jxz_cache();
    _t16 = (uint32_t)493LL;
    mkdir(_t15, _t16);
    _t18 = jxz_db();
    _t19 = (uint32_t)493LL;
    mkdir(_t18, _t19);
    _t21 = (uint8_t*)"  JXZ directories ready\u{0}";
    puts(_t21);
    return 1;
}

void jxz_print_config(void) {
    int32_t _t4;
    int64_t _t10;
    int64_t _t12;
    int64_t _t14;
    int64_t _t16;
    int64_t _t18;
    int64_t _t1;
    int64_t _t20;
    int64_t _t22;
    int64_t _t3;
    int64_t _t6;
    int64_t _t8;
    uint8_t* _t0;
    uint8_t* _t11;
    uint8_t* _t13;
    uint8_t* _t15;
    uint8_t* _t17;
    uint8_t* _t19;
    uint8_t* _t21;
    uint8_t* _t2;
    uint8_t* _t5;
    uint8_t* _t7;
    uint8_t* _t9;
    
    _t0 = (uint8_t*)"JXZ Configuration:\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"  Platform: \u{0}";
    puts(_t2);
    _t4 = detect_platform();
    _t5 = platform_name(_t4);
    puts(_t5);
    _t7 = (uint8_t*)"  Prefix:   \u{0}";
    puts(_t7);
    _t9 = jxz_prefix();
    puts(_t9);
    _t11 = (uint8_t*)"  Bin:      \u{0}";
    puts(_t11);
    _t13 = jxz_bin();
    puts(_t13);
    _t15 = (uint8_t*)"  Cellar:   \u{0}";
    puts(_t15);
    _t17 = jxz_cellar();
    puts(_t17);
    _t19 = (uint8_t*)"  Cache:    \u{0}";
    puts(_t19);
    _t21 = jxz_cache();
    puts(_t21);
    return;
}

