/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
int32_t package_create(uint8_t*, uint8_t*);
bool package_verify(void);
int32_t registry_login(void);
int32_t publish_package(uint8_t*, uint8_t*);
int32_t unpublish_version(uint8_t*, uint8_t*);

int32_t package_create(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t30;
    int32_t _t5;
    int32_t _t6;
    int32_t _t8;
    int32_t _t9;
    int64_t _t12;
    int64_t _t14;
    int64_t _t15;
    int64_t _t16;
    int64_t _t20;
    int64_t _t21;
    int64_t _t23;
    int64_t _t24;
    int64_t _t26;
    int64_t _t27;
    int64_t _t28;
    int64_t _t31;
    int64_t _t33;
    int64_t _t35;
    int64_t _t36;
    int64_t _t3;
    int64_t _t4;
    int64_t _t7;
    uint64_t _t10;
    uint64_t _t11;
    uint64_t _t13;
    uint8_t* _t0;
    uint8_t* _t17;
    uint8_t* _t18;
    uint8_t* _t19;
    uint8_t* _t1;
    uint8_t* _t22;
    uint8_t* _t25;
    uint8_t* _t2;
    uint8_t* _t32;
    uint8_t* _t34;
    void* _t29;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"   Creating package archive...\u{0}";
    puts(_t2);
    strlen(_t0);
    _t5 = (int32_t)_t4;
    _t6 = _t5;
    strlen(_t1);
    _t8 = (int32_t)_t7;
    _t9 = _t8;
    _t10 = (uint64_t)_t6;
    _t11 = (uint64_t)_t9;
    _t12 = _t10 + _t11;
    _t13 = (uint64_t)100LL;
    _t14 = _t12 + _t13;
    _t15 = (int64_t)_t14;
    malloc(_t15);
    _t17 = (uint8_t*)_t16;
    _t18 = _t17;
    _t19 = (uint8_t*)"tar -czf \u{0}";
    strcpy(_t18, _t19);
    strcat(_t18, _t0);
    _t22 = (uint8_t*)"-\u{0}";
    strcat(_t18, _t22);
    strcat(_t18, _t1);
    _t25 = (uint8_t*)".tar.gz src Jxz.toml\u{0}";
    strcat(_t18, _t25);
    system(_t18);
    _t28 = _t27;
    _t29 = (void*)_t18;
    free(_t29);
    _t30 = (int32_t)0LL;
    _t31 = _t28 == _t30;
    if (_t31) goto L_then; else goto L_else;
L_then:
    _t32 = (uint8_t*)"   Package created\u{0}";
    puts(_t32);
    goto L_merge;
L_else:
    _t34 = (uint8_t*)"   Failed to create package\u{0}";
    puts(_t34);
    goto L_merge;
L_merge:
    _t36 = _t33;
    return _t28;
}

bool package_verify(void) {
    int32_t _t10;
    int32_t _t4;
    int64_t _t11;
    int64_t _t13;
    int64_t _t15;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    int64_t _t9;
    uint8_t* _t0;
    uint8_t* _t12;
    uint8_t* _t14;
    uint8_t* _t2;
    uint8_t* _t6;
    uint8_t* _t8;
    
    _t0 = (uint8_t*)"   Verifying package...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"Jxz.toml\u{0}";
    access(_t2, F_OK);
    _t4 = (int32_t)0LL;
    _t5 = _t3 != _t4;
    if (_t5) goto L_then; else goto L_else;
L_then:
    _t6 = (uint8_t*)"   Error: Jxz.toml not found\u{0}";
    puts(_t6);
    return 0;
L_else:
    goto L_merge;
L_merge:
    _t8 = (uint8_t*)"src/main.aeth\u{0}";
    access(_t8, F_OK);
    _t10 = (int32_t)0LL;
    _t11 = _t9 != _t10;
    if (_t11) goto L_then; else goto L_else;
L_then:
    _t12 = (uint8_t*)"   Warning: src/main.aeth not found\u{0}";
    puts(_t12);
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    _t14 = (uint8_t*)"   Package verified\u{0}";
    puts(_t14);
    return 1;
}

int32_t registry_login(void) {
    int32_t _t11;
    int32_t _t14;
    int64_t _t10;
    int64_t _t13;
    int64_t _t1;
    int64_t _t3;
    int64_t _t4;
    int64_t _t6;
    int64_t _t8;
    uint8_t* _t0;
    uint8_t* _t12;
    uint8_t* _t2;
    uint8_t* _t5;
    uint8_t* _t7;
    uint8_t* _t9;
    
    _t0 = (uint8_t*)"   Logging in to registry...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"JXZ_TOKEN\u{0}";
    getenv(_t2);
    _t4 = _t3;
    _t5 = (uint8_t*)0LL;
    _t6 = _t4 == _t5;
    if (_t6) goto L_then; else goto L_else;
L_then:
    _t7 = (uint8_t*)"   Error: JXZ_TOKEN not set\u{0}";
    puts(_t7);
    _t9 = (uint8_t*)"   Set JXZ_TOKEN environment variable with your API token\u{0}";
    puts(_t9);
    _t11 = (int32_t)1LL;
    return _t11;
L_else:
    goto L_merge;
L_merge:
    _t12 = (uint8_t*)"   Logged in successfully\u{0}";
    puts(_t12);
    _t14 = (int32_t)0LL;
    return _t14;
}

int32_t publish_package(uint8_t* _arg0, uint8_t* _arg1) {
    bool _t6;
    bool _t7;
    int32_t _t18;
    int32_t _t19;
    int32_t _t20;
    int32_t _t21;
    int32_t _t26;
    int32_t _t27;
    int32_t _t29;
    int32_t _t30;
    int32_t _t52;
    int32_t _t8;
    int64_t _t10;
    int64_t _t11;
    int64_t _t13;
    int64_t _t15;
    int64_t _t17;
    int64_t _t22;
    int64_t _t24;
    int64_t _t25;
    int64_t _t28;
    int64_t _t33;
    int64_t _t35;
    int64_t _t36;
    int64_t _t37;
    int64_t _t3;
    int64_t _t41;
    int64_t _t43;
    int64_t _t44;
    int64_t _t46;
    int64_t _t47;
    int64_t _t49;
    int64_t _t50;
    int64_t _t53;
    int64_t _t55;
    int64_t _t57;
    int64_t _t59;
    int64_t _t5;
    int64_t _t60;
    uint64_t _t31;
    uint64_t _t32;
    uint64_t _t34;
    uint8_t* _t0;
    uint8_t* _t12;
    uint8_t* _t14;
    uint8_t* _t16;
    uint8_t* _t1;
    uint8_t* _t23;
    uint8_t* _t2;
    uint8_t* _t38;
    uint8_t* _t39;
    uint8_t* _t40;
    uint8_t* _t42;
    uint8_t* _t45;
    uint8_t* _t48;
    uint8_t* _t4;
    uint8_t* _t54;
    uint8_t* _t56;
    uint8_t* _t58;
    uint8_t* _t9;
    void* _t51;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"Publishing package...\u{0}";
    puts(_t2);
    _t4 = (uint8_t*)"\u{0}";
    puts(_t4);
    _t6 = package_verify();
    _t7 = !_t6;
    if (_t7) goto L_then; else goto L_else;
L_then:
    _t8 = (int32_t)1LL;
    return _t8;
L_else:
    goto L_merge;
L_merge:
    _t9 = (uint8_t*)"JXZ_TOKEN\u{0}";
    getenv(_t9);
    _t11 = _t10;
    _t12 = (uint8_t*)0LL;
    _t13 = _t11 == _t12;
    if (_t13) goto L_then; else goto L_else;
L_then:
    _t14 = (uint8_t*)"   Error: Not logged in\u{0}";
    puts(_t14);
    _t16 = (uint8_t*)"   Run \'jxz login\' first\u{0}";
    puts(_t16);
    _t18 = (int32_t)1LL;
    return _t18;
L_else:
    goto L_merge;
L_merge:
    _t19 = package_create(_t0, _t1);
    _t20 = _t19;
    _t21 = (int32_t)0LL;
    _t22 = _t20 != _t21;
    if (_t22) goto L_then; else goto L_else;
L_then:
    return _t20;
L_else:
    goto L_merge;
L_merge:
    _t23 = (uint8_t*)"   Uploading to registry...\u{0}";
    puts(_t23);
    strlen(_t0);
    _t26 = (int32_t)_t25;
    _t27 = _t26;
    strlen(_t1);
    _t29 = (int32_t)_t28;
    _t30 = _t29;
    _t31 = (uint64_t)_t27;
    _t32 = (uint64_t)_t30;
    _t33 = _t31 + _t32;
    _t34 = (uint64_t)200LL;
    _t35 = _t33 + _t34;
    _t36 = (int64_t)_t35;
    malloc(_t36);
    _t38 = (uint8_t*)_t37;
    _t39 = _t38;
    _t40 = (uint8_t*)"curl -sX POST -H \"Authorization: Bearer $JXZ_TOKEN\" \u{0}";
    strcpy(_t39, _t40);
    _t42 = (uint8_t*)"-F \"file=@\u{0}";
    strcat(_t39, _t42);
    strcat(_t39, _t0);
    _t45 = (uint8_t*)"-\u{0}";
    strcat(_t39, _t45);
    strcat(_t39, _t1);
    _t48 = (uint8_t*)".tar.gz\" https://registry.aetherlang.org/publish 2>/dev/null\u{0}";
    strcat(_t39, _t48);
    system(_t39);
    _t20 = _t50;
    _t51 = (void*)_t39;
    free(_t51);
    _t52 = (int32_t)0LL;
    _t53 = _t20 == _t52;
    if (_t53) goto L_then; else goto L_else;
L_then:
    _t54 = (uint8_t*)"\u{0}";
    puts(_t54);
    _t56 = (uint8_t*)"Package published successfully!\u{0}";
    puts(_t56);
    goto L_merge;
L_else:
    _t58 = (uint8_t*)"   Upload failed\u{0}";
    puts(_t58);
    goto L_merge;
L_merge:
    _t60 = _t57;
    return _t20;
}

int32_t unpublish_version(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t6;
    int64_t _t3;
    int64_t _t5;
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t2;
    uint8_t* _t4;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"   Yanking version...\u{0}";
    puts(_t2);
    _t4 = (uint8_t*)"   Version yanked\u{0}";
    puts(_t4);
    _t6 = (int32_t)0LL;
    return _t6;
}

