/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
int32_t resolve_deps(uint8_t*);
int32_t install_with_deps(uint8_t*, uint8_t*);
int32_t version_compare(uint8_t*, uint8_t*);
bool version_matches(uint8_t*, uint8_t*);
uint8_t* get_latest_version(uint8_t*);
bool check_conflicts(uint8_t*);
int32_t generate_lockfile(void);
int32_t install_from_lockfile(void);

int32_t resolve_deps(uint8_t* _arg0) {
    int32_t _t23;
    int32_t _t7;
    int32_t _t8;
    int64_t _t11;
    int64_t _t12;
    int64_t _t13;
    int64_t _t17;
    int64_t _t18;
    int64_t _t20;
    int64_t _t21;
    int64_t _t2;
    int64_t _t3;
    int64_t _t5;
    int64_t _t6;
    uint64_t _t10;
    uint64_t _t9;
    uint8_t* _t0;
    uint8_t* _t14;
    uint8_t* _t15;
    uint8_t* _t16;
    uint8_t* _t19;
    uint8_t* _t1;
    uint8_t* _t4;
    void* _t22;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"==> Resolving dependencies for: \u{0}";
    puts(_t1);
    puts(_t0);
    _t4 = (uint8_t*)"\u{0}";
    puts(_t4);
    strlen(_t0);
    _t7 = (int32_t)_t6;
    _t8 = _t7;
    _t9 = (uint64_t)_t8;
    _t10 = (uint64_t)100LL;
    _t11 = _t9 + _t10;
    _t12 = (int64_t)_t11;
    malloc(_t12);
    _t14 = (uint8_t*)_t13;
    _t15 = _t14;
    _t16 = (uint8_t*)"cat ~/.jxz/Cellar/\u{0}";
    strcpy(_t15, _t16);
    strcat(_t15, _t0);
    _t19 = (uint8_t*)"/*/deps.txt 2>/dev/null || echo \'No dependencies\'\u{0}";
    strcat(_t15, _t19);
    system(_t15);
    _t22 = (void*)_t15;
    free(_t22);
    _t23 = (int32_t)0LL;
    return _t23;
}

int32_t install_with_deps(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t4;
    int32_t _t9;
    int64_t _t3;
    int64_t _t6;
    int64_t _t8;
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t2;
    uint8_t* _t5;
    uint8_t* _t7;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"==> Installing with dependencies...\u{0}";
    puts(_t2);
    _t4 = resolve_deps(_t0);
    _t5 = (uint8_t*)"  Installing dependencies first...\u{0}";
    puts(_t5);
    _t7 = (uint8_t*)"  Installing main package...\u{0}";
    puts(_t7);
    _t9 = (int32_t)0LL;
    return _t9;
}

int32_t version_compare(uint8_t* _arg0, uint8_t* _arg1) {
    int64_t _t2;
    uint8_t* _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    strcmp(_t0, _t1);
    return _t2;
}

bool version_matches(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t3;
    int64_t _t2;
    int64_t _t4;
    uint8_t* _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    strcmp(_t0, _t1);
    _t3 = (int32_t)0LL;
    _t4 = _t2 == _t3;
    return _t4;
}

uint8_t* get_latest_version(uint8_t* _arg0) {
    uint8_t* _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"latest\u{0}";
    return _t1;
}

bool check_conflicts(uint8_t* _arg0) {
    int64_t _t2;
    int64_t _t4;
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t3;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"  Checking for conflicts...\u{0}";
    puts(_t1);
    _t3 = (uint8_t*)"  No conflicts detected\u{0}";
    puts(_t3);
    return 0;
}

int32_t generate_lockfile(void) {
    int32_t _t12;
    int64_t _t11;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    int64_t _t7;
    int64_t _t9;
    uint8_t* _t0;
    uint8_t* _t10;
    uint8_t* _t2;
    uint8_t* _t4;
    uint8_t* _t6;
    uint8_t* _t8;
    
    _t0 = (uint8_t*)"==> Generating Jxz.lock...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"echo \'# JXZ Lock File\' > Jxz.lock\u{0}";
    system(_t2);
    _t4 = (uint8_t*)"echo \'# Generated automatically\' >> Jxz.lock\u{0}";
    system(_t4);
    _t6 = (uint8_t*)"echo \'\' >> Jxz.lock\u{0}";
    system(_t6);
    _t8 = (uint8_t*)"ls ~/.jxz/Cellar 2>/dev/null | while read pkg; do \n        version=$(ls ~/.jxz/Cellar/$pkg 2>/dev/null | head -1); \n        echo \"$pkg = \\\"$version\\\"\" >> Jxz.lock; \n    done\u{0}";
    system(_t8);
    _t10 = (uint8_t*)"  Lock file generated\u{0}";
    puts(_t10);
    _t12 = (int32_t)0LL;
    return _t12;
}

int32_t install_from_lockfile(void) {
    int32_t _t4;
    int64_t _t1;
    int64_t _t3;
    uint8_t* _t0;
    uint8_t* _t2;
    
    _t0 = (uint8_t*)"==> Installing from Jxz.lock...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"grep -v \'^#\' Jxz.lock | grep -v \'^$\' | while read line; do \n        pkg=$(echo $line | cut -d\'=\' -f1 | tr -d \' \'); \n        ver=$(echo $line | cut -d\'\"\' -f2); \n        echo \"  Installing $pkg $ver\"; \n    done\u{0}";
    system(_t2);
    _t4 = (int32_t)0LL;
    return _t4;
}

