/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct TestResult {
    int32_t total;
    int32_t passed;
    int32_t failed;
};

int32_t run_tests(void);
int32_t run_single_test(uint8_t*);
int32_t watch_tests(void);

int32_t run_tests(void) {
    int32_t _t11;
    int32_t _t36;
    int64_t _t10;
    int64_t _t12;
    int64_t _t14;
    int64_t _t17;
    int64_t _t1;
    int64_t _t20;
    int64_t _t22;
    int64_t _t23;
    int64_t _t25;
    int64_t _t27;
    int64_t _t29;
    int64_t _t31;
    int64_t _t33;
    int64_t _t35;
    int64_t _t3;
    int64_t _t4;
    int64_t _t6;
    int64_t _t8;
    uint32_t _t16;
    uint32_t _t19;
    uint8_t* _t0;
    uint8_t* _t13;
    uint8_t* _t15;
    uint8_t* _t18;
    uint8_t* _t21;
    uint8_t* _t24;
    uint8_t* _t26;
    uint8_t* _t28;
    uint8_t* _t2;
    uint8_t* _t30;
    uint8_t* _t32;
    uint8_t* _t34;
    uint8_t* _t7;
    uint8_t* _t9;
    void* _t5;
    
    _t0 = (uint8_t*)"   Discovering tests...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"tests\u{0}";
    opendir(_t2);
    _t4 = _t3;
    _t5 = (void*)0LL;
    _t6 = _t4 == _t5;
    if (_t6) goto L_then; else goto L_else;
L_then:
    _t7 = (uint8_t*)"   No tests directory found\u{0}";
    puts(_t7);
    _t9 = (uint8_t*)"   Create tests/ directory with test_*.aeth files\u{0}";
    puts(_t9);
    _t11 = (int32_t)0LL;
    return _t11;
L_else:
    goto L_merge;
L_merge:
    closedir(_t4);
    _t13 = (uint8_t*)"   Compiling tests...\u{0}";
    puts(_t13);
    _t15 = (uint8_t*)"target\u{0}";
    _t16 = (uint32_t)493LL;
    mkdir(_t15, _t16);
    _t18 = (uint8_t*)"target/tests\u{0}";
    _t19 = (uint32_t)493LL;
    mkdir(_t18, _t19);
    _t21 = (uint8_t*)"for f in tests/test_*.aeth; do [ -f \"$f\" ] && aethc --emit-c \"$f\" 2>/dev/null; done\u{0}";
    system(_t21);
    _t23 = _t22;
    _t24 = (uint8_t*)"for f in tests/test_*.c; do [ -f \"$f\" ] && cc -o \"target/tests/$(basename $f .c)\" \"$f\" 2>/dev/null; done\u{0}";
    system(_t24);
    _t23 = _t25;
    _t26 = (uint8_t*)"   Running tests...\u{0}";
    puts(_t26);
    _t28 = (uint8_t*)"\u{0}";
    puts(_t28);
    _t30 = (uint8_t*)"for f in target/tests/test_*; do [ -x \"$f\" ] && echo \"Running $f\" && \"$f\"; done\u{0}";
    system(_t30);
    _t23 = _t31;
    _t32 = (uint8_t*)"\u{0}";
    puts(_t32);
    _t34 = (uint8_t*)"   Tests completed\u{0}";
    puts(_t34);
    _t36 = (int32_t)0LL;
    return _t36;
}

int32_t run_single_test(uint8_t* _arg0) {
    int64_t _t2;
    int64_t _t3;
    int64_t _t5;
    int64_t _t6;
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t4;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"   Running single test:\u{0}";
    puts(_t1);
    puts(_t0);
    _t4 = (uint8_t*)"aethc --emit-c\u{0}";
    system(_t4);
    _t6 = _t5;
    return _t6;
}

int32_t watch_tests(void) {
    int32_t _t4;
    int64_t _t1;
    int64_t _t3;
    uint8_t* _t0;
    uint8_t* _t2;
    
    _t0 = (uint8_t*)"   Watching for changes...\u{0}";
    puts(_t0);
    _t2 = (uint8_t*)"   Press Ctrl+C to stop\u{0}";
    puts(_t2);
    _t4 = run_tests();
    return _t4;
}

