/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
/* Enum Definitions (Tagged Unions) */
int64_t __closure_0(int64_t);
int64_t __closure_1(int64_t);
int32_t main(void);

int64_t __closure_0(int64_t _arg0) {
    int64_t _t0;
    
    _t0 = _arg0 + 1LL;
    return _t0;
}

int64_t __closure_1(int64_t _arg0) {
    int64_t _t0;
    
    _t0 = _arg0 * 2LL;
    return _t0;
}

int32_t main(void) {
    int32_t _t3;
    int32_t _t4;
    int64_t _t0;
    int64_t _t1;
    uint8_t* _t2;
    
    _t0 = __closure_0;
    _t1 = __closure_1;
    _t2 = (uint8_t*)"Closure defined!\n\0";
    _t3 = printf(_t2);
    _t4 = (int32_t)0LL;
    return _t4;
}

