/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
/* Enum Definitions (Tagged Unions) */
int32_t main(void);

int32_t main(void) {
    int32_t _t10;
    int32_t _t1;
    int32_t _t2;
    int32_t _t3;
    int32_t _t4;
    int32_t _t5;
    int32_t _t7;
    int32_t _t9;
    uint8_t* _t0;
    uint8_t* _t6;
    uint8_t* _t8;
    
    _t0 = (uint8_t*)"Testing module import!\0";
    _t1 = puts(_t0);
    helper_greet();
    _t2 = (int32_t)10LL;
    _t3 = (int32_t)20LL;
    _t4 = helper_add(_t2, _t3);
    _t5 = _t4;
    _t6 = (uint8_t*)"10 + 20 = %d\n\0";
    _t7 = printf(_t6, _t5);
    _t8 = (uint8_t*)"Module import test passed!\0";
    _t9 = puts(_t8);
    _t10 = (int32_t)0LL;
    return _t10;
}

