/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
void naked_entry(void);
void timer_irq(void);
void main(void);

/* @naked: no prologue/epilogue */
#if defined(__GNUC__) || defined(__clang__)
__attribute__((naked))
#endif
void naked_entry(void) {
    
    __asm__ volatile ("ret" :  :  : );
    return;
}

/* @interrupt: interrupt handler */
#if defined(__GNUC__) || defined(__clang__)
__attribute__((interrupt))
#endif
void timer_irq(void) {
    
    return;
}

void main(void) {
    int64_t _t0;
    
    aether_println("Kernel annotations test!");
    return;
}

