/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
/* Enum Definitions (Tagged Unions) */
int32_t main(void);

int32_t main(void) {
    int32_t _t1;
    int32_t _t2;
    uint8_t* _t0;
    
    _t0 = (uint8_t*)"Module import test passed!";
    _t1 = puts(_t0);
    _t2 = (int32_t)0LL;
    return _t2;
}

