/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct Counter {
    uint64_t value;
};


/* Enum Definitions (Tagged Unions) */
uint64_t get_value(struct Counter*);
int32_t main(void);

uint64_t get_value(struct Counter* _arg0) {
    struct Counter _t1;
    struct Counter* _t0;
    
    _t0 = _arg0;
    _t1 = *_t0;
    return NULL;
}

int32_t main(void) {
    int32_t _t10;
    int32_t _t14;
    int32_t _t16;
    int32_t _t17;
    int32_t _t1;
    struct Counter* _t2;
    struct Counter* _t4;
    struct Counter* _t5;
    struct Counter* _t6;
    uint64_t _t11;
    uint64_t _t12;
    uint64_t _t9;
    uint64_t* _t3;
    uint64_t* _t8;
    uint8_t* _t0;
    uint8_t* _t13;
    uint8_t* _t15;
    uint8_t* _t7;
    
    _t0 = (uint8_t*)"Pointer Field Test\0";
    _t1 = puts(_t0);
    struct Counter _alloca__t2;
    _t2 = &_alloca__t2;
    _t3 = &_t2->value;
    *_t3 = 42LL;
    _t4 = _t2;
    _t5 = (struct Counter*)_t4;
    _t6 = _t5;
    _t7 = (uint8_t*)"Direct: %llu\n\0";
    _t8 = &_t4->value;
    _t9 = *_t8;
    _t10 = printf(_t7, _t9);
    _t11 = get_value(_t6);
    _t12 = _t11;
    _t13 = (uint8_t*)"Via function: %llu\n\0";
    _t14 = printf(_t13, _t12);
    _t15 = (uint8_t*)"Done!\0";
    _t16 = puts(_t15);
    _t17 = (int32_t)0LL;
    return _t17;
}

