/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
__m128 use_vector(__m128);
void main(void);

__m128 use_vector(__m128 _arg0) {
    __m128 _t0;
    
    _t0 = _arg0;
    return _t0;
}

void main(void) {
    int64_t _t0;
    
    aether_println("SIMD type f32x4 parsed successfully!");
    return;
}

