/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
/* Enum Definitions (Tagged Unions) */
int32_t main(void);

int32_t main(void) {
    int32_t _t3;
    int32_t _t6;
    int32_t _t7;
    int64_t _t0;
    int64_t _t1;
    int64_t _t4;
    uint8_t* _t2;
    uint8_t* _t5;
    
    _t0 = 0LL;
    goto L_while_cond_1;
L_while_cond_1:
    _t1 = _t0 < 5LL;
    if (_t1) goto L_while_body_2; else goto L_while_exit_3;
L_while_body_2:
    _t2 = (uint8_t*)"Count: %d\n\0";
    _t3 = printf(_t2, _t0);
    _t4 = _t0 + 1LL;
    _t0 = _t4;
    goto L_while_cond_1;
L_while_exit_3:
    _t5 = (uint8_t*)"Final count: %d\n\0";
    _t6 = printf(_t5, _t0);
    _t7 = (int32_t)0LL;
    return _t7;
}

