/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct MultibootHeader {
    struct u32 magic;
    struct u32 flags;
    struct u32 checksum;
};

struct MultibootHeader get_multiboot_header(void);

struct MultibootHeader get_multiboot_header(void) {
    struct MultibootHeader* _t0;
    struct u32* _t1;
    struct u32* _t2;
    struct u32* _t3;
    
    struct MultibootHeader _alloca__t0;
    _t0 = &_alloca__t0;
    _t1 = &_t0->magic;
    *_t1 = 464367618LL;
    _t2 = &_t0->flags;
    *_t2 = 3LL;
    _t3 = &_t0->checksum;
    *_t3 = 3830599675LL;
    return _t0;
}

