/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct Graph {
    int32_t* ops;
    float* values;
    int32_t* input1s;
    int32_t* input2s;
    bool* evaluated;
    int32_t count;
    int32_t capacity;
};

struct Graph* graph_new(void);
int32_t add_node(struct Graph**, int32_t, float, int32_t, int32_t);
int32_t const_node(struct Graph**, float);
int32_t var_node(struct Graph**);
void set_var(struct Graph**, int32_t, float);
int32_t add_op(struct Graph**, int32_t, int32_t);
int32_t sub_op(struct Graph**, int32_t, int32_t);
int32_t mul_op(struct Graph**, int32_t, int32_t);
int32_t div_op(struct Graph**, int32_t, int32_t);
int32_t neg_op(struct Graph**, int32_t);
int32_t exp_op(struct Graph**, int32_t);
int32_t relu_op(struct Graph**, int32_t);
int32_t sigmoid_op(struct Graph**, int32_t);
float eval_node(struct Graph**, int32_t);
float eval(struct Graph**, int32_t);
void graph_reset(struct Graph**);

struct Graph* graph_new(void) {
    bool* _t18;
    bool* _t19;
    bool** _t25;
    float* _t7;
    float* _t8;
    float** _t22;
    int32_t* _t11;
    int32_t* _t12;
    int32_t* _t15;
    int32_t* _t16;
    int32_t* _t26;
    int32_t* _t27;
    int32_t* _t3;
    int32_t* _t4;
    int32_t** _t21;
    int32_t** _t23;
    int32_t** _t24;
    int64_t _t0;
    int64_t _t10;
    int64_t _t13;
    int64_t _t14;
    int64_t _t17;
    int64_t _t1;
    int64_t _t2;
    int64_t _t5;
    int64_t _t6;
    int64_t _t9;
    struct Graph* _t20;
    
    _t0 = 64LL;
    _t1 = _t0 * 4LL;
    malloc(_t1);
    _t3 = (int32_t*)_t2;
    _t4 = _t3;
    _t5 = _t0 * 4LL;
    malloc(_t5);
    _t7 = (float*)_t6;
    _t8 = _t7;
    _t9 = _t0 * 4LL;
    malloc(_t9);
    _t11 = (int32_t*)_t10;
    _t12 = _t11;
    _t13 = _t0 * 4LL;
    malloc(_t13);
    _t15 = (int32_t*)_t14;
    _t16 = _t15;
    malloc(_t0);
    _t18 = (bool*)_t17;
    _t19 = _t18;
    struct Graph _alloca__t20;
    _t20 = &_alloca__t20;
    _t21 = &_t20->ops;
    *_t21 = _t4;
    _t22 = &_t20->values;
    *_t22 = _t8;
    _t23 = &_t20->input1s;
    *_t23 = _t12;
    _t24 = &_t20->input2s;
    *_t24 = _t16;
    _t25 = &_t20->evaluated;
    *_t25 = _t19;
    _t26 = &_t20->count;
    *_t26 = 0LL;
    _t27 = &_t20->capacity;
    *_t27 = _t0;
    return _t20;
}

int32_t add_node(struct Graph** _arg0, int32_t _arg1, float _arg2, int32_t _arg3, int32_t _arg4) {
    bool _t49;
    bool* _t47;
    bool* _t48;
    bool* _t52;
    bool* _t53;
    bool** _t46;
    bool** _t51;
    float _t22;
    float _t2;
    float* _t20;
    float* _t21;
    float* _t25;
    float* _t26;
    float** _t19;
    float** _t24;
    int32_t _t13;
    int32_t _t1;
    int32_t _t31;
    int32_t _t3;
    int32_t _t40;
    int32_t _t4;
    int32_t _t56;
    int32_t _t59;
    int32_t _t60;
    int32_t _t7;
    int32_t _t8;
    int32_t* _t11;
    int32_t* _t12;
    int32_t* _t16;
    int32_t* _t17;
    int32_t* _t29;
    int32_t* _t30;
    int32_t* _t34;
    int32_t* _t35;
    int32_t* _t38;
    int32_t* _t39;
    int32_t* _t43;
    int32_t* _t44;
    int32_t* _t55;
    int32_t* _t58;
    int32_t* _t63;
    int32_t* _t6;
    int32_t** _t10;
    int32_t** _t15;
    int32_t** _t28;
    int32_t** _t33;
    int32_t** _t37;
    int32_t** _t42;
    int64_t _t61;
    struct Graph* _t14;
    struct Graph* _t18;
    struct Graph* _t23;
    struct Graph* _t27;
    struct Graph* _t32;
    struct Graph* _t36;
    struct Graph* _t41;
    struct Graph* _t45;
    struct Graph* _t50;
    struct Graph* _t54;
    struct Graph* _t57;
    struct Graph* _t5;
    struct Graph* _t62;
    struct Graph* _t9;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = _arg3;
    _t4 = _arg4;
    _t5 = *_t0;
    _t6 = &_t5->count;
    _t7 = *_t6;
    _t8 = _t7;
    _t9 = *_t0;
    _t10 = &_t9->ops;
    _t11 = *_t10;
    _t12 = &_t11[_t8];
    _t13 = *_t12;
    _t14 = *_t0;
    _t15 = &_t14->ops;
    _t16 = *_t15;
    _t17 = &_t16[_t8];
    *_t17 = _t1;
    _t18 = *_t0;
    _t19 = &_t18->values;
    _t20 = *_t19;
    _t21 = &_t20[_t8];
    _t22 = *_t21;
    _t23 = *_t0;
    _t24 = &_t23->values;
    _t25 = *_t24;
    _t26 = &_t25[_t8];
    *_t26 = _t2;
    _t27 = *_t0;
    _t28 = &_t27->input1s;
    _t29 = *_t28;
    _t30 = &_t29[_t8];
    _t31 = *_t30;
    _t32 = *_t0;
    _t33 = &_t32->input1s;
    _t34 = *_t33;
    _t35 = &_t34[_t8];
    *_t35 = _t3;
    _t36 = *_t0;
    _t37 = &_t36->input2s;
    _t38 = *_t37;
    _t39 = &_t38[_t8];
    _t40 = *_t39;
    _t41 = *_t0;
    _t42 = &_t41->input2s;
    _t43 = *_t42;
    _t44 = &_t43[_t8];
    *_t44 = _t4;
    _t45 = *_t0;
    _t46 = &_t45->evaluated;
    _t47 = *_t46;
    _t48 = &_t47[_t8];
    _t49 = *_t48;
    _t50 = *_t0;
    _t51 = &_t50->evaluated;
    _t52 = *_t51;
    _t53 = &_t52[_t8];
    *_t53 = 0;
    _t54 = *_t0;
    _t55 = &_t54->count;
    _t56 = *_t55;
    _t57 = *_t0;
    _t58 = &_t57->count;
    _t59 = *_t58;
    _t60 = (int32_t)1LL;
    _t61 = _t59 + _t60;
    _t62 = *_t0;
    _t63 = &_t62->count;
    *_t63 = _t61;
    return _t8;
}

int32_t const_node(struct Graph** _arg0, float _arg1) {
    bool _t12;
    bool* _t10;
    bool* _t11;
    bool* _t15;
    bool* _t16;
    bool** _t14;
    bool** _t9;
    float _t1;
    int32_t _t3;
    int32_t _t5;
    int32_t _t6;
    int32_t _t7;
    int64_t _t2;
    int64_t _t4;
    struct Graph* _t13;
    struct Graph* _t8;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = -1LL;
    _t3 = (int32_t)_t2;
    _t4 = -1LL;
    _t5 = (int32_t)_t4;
    _t6 = add_node(_t0, OP_CONST, _t1, _t3, _t5);
    _t7 = _t6;
    _t8 = *_t0;
    _t9 = &_t8->evaluated;
    _t10 = *_t9;
    _t11 = &_t10[_t7];
    _t12 = *_t11;
    _t13 = *_t0;
    _t14 = &_t13->evaluated;
    _t15 = *_t14;
    _t16 = &_t15[_t7];
    *_t16 = 1;
    return _t7;
}

int32_t var_node(struct Graph** _arg0) {
    int32_t _t2;
    int32_t _t4;
    int32_t _t5;
    int64_t _t1;
    int64_t _t3;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = -1LL;
    _t2 = (int32_t)_t1;
    _t3 = -1LL;
    _t4 = (int32_t)_t3;
    _t5 = add_node(_t0, OP_VAR, 0, _t2, _t4);
    return _t5;
}

void set_var(struct Graph** _arg0, int32_t _arg1, float _arg2) {
    bool _t16;
    bool* _t14;
    bool* _t15;
    bool* _t19;
    bool* _t20;
    bool** _t13;
    bool** _t18;
    float _t2;
    float _t7;
    float* _t10;
    float* _t11;
    float* _t5;
    float* _t6;
    float** _t4;
    float** _t9;
    int32_t _t1;
    struct Graph* _t12;
    struct Graph* _t17;
    struct Graph* _t3;
    struct Graph* _t8;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = *_t0;
    _t4 = &_t3->values;
    _t5 = *_t4;
    _t6 = &_t5[_t1];
    _t7 = *_t6;
    _t8 = *_t0;
    _t9 = &_t8->values;
    _t10 = *_t9;
    _t11 = &_t10[_t1];
    *_t11 = _t2;
    _t12 = *_t0;
    _t13 = &_t12->evaluated;
    _t14 = *_t13;
    _t15 = &_t14[_t1];
    _t16 = *_t15;
    _t17 = *_t0;
    _t18 = &_t17->evaluated;
    _t19 = *_t18;
    _t20 = &_t19[_t1];
    *_t20 = 1;
    return;
}

int32_t add_op(struct Graph** _arg0, int32_t _arg1, int32_t _arg2) {
    int32_t _t1;
    int32_t _t2;
    int32_t _t3;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = add_node(_t0, OP_ADD, 0, _t1, _t2);
    return _t3;
}

int32_t sub_op(struct Graph** _arg0, int32_t _arg1, int32_t _arg2) {
    int32_t _t1;
    int32_t _t2;
    int32_t _t3;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = add_node(_t0, OP_SUB, 0, _t1, _t2);
    return _t3;
}

int32_t mul_op(struct Graph** _arg0, int32_t _arg1, int32_t _arg2) {
    int32_t _t1;
    int32_t _t2;
    int32_t _t3;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = add_node(_t0, OP_MUL, 0, _t1, _t2);
    return _t3;
}

int32_t div_op(struct Graph** _arg0, int32_t _arg1, int32_t _arg2) {
    int32_t _t1;
    int32_t _t2;
    int32_t _t3;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = add_node(_t0, OP_DIV, 0, _t1, _t2);
    return _t3;
}

int32_t neg_op(struct Graph** _arg0, int32_t _arg1) {
    int32_t _t1;
    int32_t _t3;
    int32_t _t4;
    int64_t _t2;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = -1LL;
    _t3 = (int32_t)_t2;
    _t4 = add_node(_t0, OP_NEG, 0, _t1, _t3);
    return _t4;
}

int32_t exp_op(struct Graph** _arg0, int32_t _arg1) {
    int32_t _t1;
    int32_t _t3;
    int32_t _t4;
    int64_t _t2;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = -1LL;
    _t3 = (int32_t)_t2;
    _t4 = add_node(_t0, OP_EXP, 0, _t1, _t3);
    return _t4;
}

int32_t relu_op(struct Graph** _arg0, int32_t _arg1) {
    int32_t _t1;
    int32_t _t3;
    int32_t _t4;
    int64_t _t2;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = -1LL;
    _t3 = (int32_t)_t2;
    _t4 = add_node(_t0, OP_RELU, 0, _t1, _t3);
    return _t4;
}

int32_t sigmoid_op(struct Graph** _arg0, int32_t _arg1) {
    int32_t _t1;
    int32_t _t3;
    int32_t _t4;
    int64_t _t2;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = -1LL;
    _t3 = (int32_t)_t2;
    _t4 = add_node(_t0, OP_SIGMOID, 0, _t1, _t3);
    return _t4;
}

float eval_node(struct Graph** _arg0, int32_t _arg1) {
    bool _t54;
    bool _t6;
    bool* _t4;
    bool* _t52;
    bool* _t53;
    bool* _t57;
    bool* _t58;
    bool* _t5;
    bool** _t3;
    bool** _t51;
    bool** _t56;
    float _t11;
    float _t12;
    float _t13;
    float _t27;
    float _t29;
    float _t45;
    float _t68;
    float _t70;
    float _t80;
    float _t81;
    float* _t10;
    float* _t43;
    float* _t44;
    float* _t48;
    float* _t49;
    float* _t9;
    float** _t42;
    float** _t47;
    float** _t8;
    int32_t _t18;
    int32_t _t19;
    int32_t _t1;
    int32_t _t24;
    int32_t _t25;
    int32_t _t34;
    int32_t _t35;
    int32_t* _t16;
    int32_t* _t17;
    int32_t* _t22;
    int32_t* _t23;
    int32_t* _t32;
    int32_t* _t33;
    int32_t** _t15;
    int32_t** _t21;
    int32_t** _t31;
    int64_t _t26;
    int64_t _t28;
    int64_t _t36;
    int64_t _t37;
    int64_t _t38;
    int64_t _t39;
    int64_t _t40;
    int64_t _t59;
    int64_t _t60;
    int64_t _t61;
    int64_t _t62;
    int64_t _t63;
    int64_t _t64;
    int64_t _t65;
    int64_t _t66;
    int64_t _t67;
    int64_t _t69;
    int64_t _t71;
    int64_t _t72;
    int64_t _t73;
    int64_t _t74;
    int64_t _t75;
    int64_t _t76;
    int64_t _t77;
    int64_t _t78;
    int64_t _t79;
    int64_t _t82;
    int64_t _t83;
    int64_t _t84;
    struct Graph* _t14;
    struct Graph* _t20;
    struct Graph* _t2;
    struct Graph* _t30;
    struct Graph* _t41;
    struct Graph* _t46;
    struct Graph* _t50;
    struct Graph* _t55;
    struct Graph* _t7;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t0;
    _t3 = &_t2->evaluated;
    _t4 = *_t3;
    _t5 = &_t4[_t1];
    _t6 = *_t5;
    if (_t6) goto L_then; else goto L_else;
L_then:
    _t7 = *_t0;
    _t8 = &_t7->values;
    _t9 = *_t8;
    _t10 = &_t9[_t1];
    _t11 = *_t10;
    return _t11;
L_else:
    goto L_merge;
L_merge:
    _t12 = 0;
    _t13 = 0;
    _t14 = *_t0;
    _t15 = &_t14->input1s;
    _t16 = *_t15;
    _t17 = &_t16[_t1];
    _t18 = *_t17;
    _t19 = _t18;
    _t20 = *_t0;
    _t21 = &_t20->input2s;
    _t22 = *_t21;
    _t23 = &_t22[_t1];
    _t24 = *_t23;
    _t25 = _t24;
    _t26 = _t19 >= 0LL;
    if (_t26) goto L_then; else goto L_else;
L_then:
    _t27 = eval_node(_t0, _t19);
    _t12 = _t27;
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    _t28 = _t25 >= 0LL;
    if (_t28) goto L_then; else goto L_else;
L_then:
    _t29 = eval_node(_t0, _t25);
    _t13 = _t29;
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    _t30 = *_t0;
    _t31 = &_t30->ops;
    _t32 = *_t31;
    _t33 = &_t32[_t1];
    _t34 = *_t33;
    _t35 = _t34;
    _t36 = 0;
    _t37 = _t35 == OP_ADD;
    if (_t37) goto L_then; else goto L_else;
L_then:
    _t38 = _t12 + _t13;
    _t36 = _t38;
    goto L_merge;
L_else:
    _t39 = _t35 == OP_SUB;
    if (_t39) goto L_then; else goto L_else;
L_merge:
    _t40 = _t38;
    _t41 = *_t0;
    _t42 = &_t41->values;
    _t43 = *_t42;
    _t44 = &_t43[_t1];
    _t45 = *_t44;
    _t46 = *_t0;
    _t47 = &_t46->values;
    _t48 = *_t47;
    _t49 = &_t48[_t1];
    *_t49 = _t36;
    _t50 = *_t0;
    _t51 = &_t50->evaluated;
    _t52 = *_t51;
    _t53 = &_t52[_t1];
    _t54 = *_t53;
    _t55 = *_t0;
    _t56 = &_t55->evaluated;
    _t57 = *_t56;
    _t58 = &_t57[_t1];
    *_t58 = 1;
    return _t36;
L_then:
    _t59 = _t12 - _t13;
    _t36 = _t59;
    goto L_merge;
L_else:
    _t60 = _t35 == OP_MUL;
    if (_t60) goto L_then; else goto L_else;
L_merge:
    _t61 = _t59;
    goto L_merge;
L_then:
    _t62 = _t12 * _t13;
    _t36 = _t62;
    goto L_merge;
L_else:
    _t63 = _t35 == OP_DIV;
    if (_t63) goto L_then; else goto L_else;
L_merge:
    _t64 = _t62;
    goto L_merge;
L_then:
    _t65 = _t12 / _t13;
    _t36 = _t65;
    goto L_merge;
L_else:
    _t66 = _t35 == OP_NEG;
    if (_t66) goto L_then; else goto L_else;
L_merge:
    _t67 = _t65;
    goto L_merge;
L_then:
    _t68 = -_t12;
    _t36 = _t68;
    goto L_merge;
L_else:
    _t69 = _t35 == OP_EXP;
    if (_t69) goto L_then; else goto L_else;
L_merge:
    _t70 = _t68;
    goto L_merge;
L_then:
    expf(_t12);
    _t36 = _t71;
    goto L_merge;
L_else:
    _t72 = _t35 == OP_LOG;
    if (_t72) goto L_then; else goto L_else;
L_merge:
    _t73 = _t71;
    goto L_merge;
L_then:
    logf(_t12);
    _t36 = _t74;
    goto L_merge;
L_else:
    _t75 = _t35 == OP_RELU;
    if (_t75) goto L_then; else goto L_else;
L_merge:
    _t76 = _t74;
    goto L_merge;
L_then:
    _t77 = _t12 > 0;
    if (_t77) goto L_then; else goto L_else;
L_else:
    _t78 = _t35 == OP_SIGMOID;
    if (_t78) goto L_then; else goto L_else;
L_merge:
    _t79 = _t80;
    goto L_merge;
L_then:
    _t36 = _t12;
    goto L_merge;
L_else:
    _t36 = 0;
    goto L_merge;
L_merge:
    _t80 = _t12;
    goto L_merge;
L_then:
    _t81 = -_t12;
    expf(_t81);
    _t83 = 1 + _t82;
    _t84 = 1 / _t83;
    _t36 = _t84;
    goto L_merge;
L_else:
    goto L_merge;
L_merge:
    goto L_merge;
}

float eval(struct Graph** _arg0, int32_t _arg1) {
    float _t2;
    int32_t _t1;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = eval_node(_t0, _t1);
    return _t2;
}

void graph_reset(struct Graph** _arg0) {
    int64_t _t1;
    struct Graph** _t0;
    
    _t0 = _arg0;
    _t1 = 0LL;
    return;
}

