/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
/* Enum Definitions (Tagged Unions) */
void helper_greet(void);
int32_t helper_add(int32_t, int32_t);

void helper_greet(void) {
    int32_t _t1;
    uint8_t* _t0;
    
    _t0 = (uint8_t*)"Hello from helper module!\0";
    _t1 = puts(_t0);
    return;
}

int32_t helper_add(int32_t _arg0, int32_t _arg1) {
    int32_t _t0;
    int32_t _t1;
    int64_t _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _t0 + _t1;
    return _t2;
}

