/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct File {
    void* handle;
};


/* Enum Definitions (Tagged Unions) */
void io_print(uint8_t*);
void io_println(uint8_t*);
void io_print_int(int64_t);
void io_println_int(int64_t);
void io_open_read(struct File*, uint8_t*);
void io_open_write(struct File*, uint8_t*);
int32_t io_close(struct File**);
bool io_is_valid(struct File**);

void io_print(uint8_t* _arg0) {
    int32_t _t2;
    uint8_t* _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"%s\0";
    _t2 = printf(_t1, _t0);
    return;
}

void io_println(uint8_t* _arg0) {
    int32_t _t1;
    uint8_t* _t0;
    
    _t0 = _arg0;
    _t1 = puts(_t0);
    return;
}

void io_print_int(int64_t _arg0) {
    int32_t _t2;
    int64_t _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"%lld\0";
    _t2 = printf(_t1, _t0);
    return;
}

void io_println_int(int64_t _arg0) {
    int32_t _t2;
    int64_t _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = (uint8_t*)"%lld\n\0";
    _t2 = printf(_t1, _t0);
    return;
}

void io_open_read(struct File* _arg0, uint8_t* _arg1) {
    struct File* _t0;
    uint8_t* _t1;
    uint8_t* _t2;
    void* _t3;
    void* _t4;
    void** _t5;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"r\0";
    _t3 = fopen(_t1, _t2);
    _t4 = _t3;
    _t5 = &_t0->handle;
    *_t5 = _t4;
    return;
}

void io_open_write(struct File* _arg0, uint8_t* _arg1) {
    struct File* _t0;
    uint8_t* _t1;
    uint8_t* _t2;
    void* _t3;
    void* _t4;
    void** _t5;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = (uint8_t*)"w\0";
    _t3 = fopen(_t1, _t2);
    _t4 = _t3;
    _t5 = &_t0->handle;
    *_t5 = _t4;
    return;
}

int32_t io_close(struct File** _arg0) {
    int32_t _t4;
    struct File* _t1;
    struct File** _t0;
    void* _t3;
    void** _t2;
    
    _t0 = _arg0;
    _t1 = *_t0;
    _t2 = &_t1->handle;
    _t3 = *_t2;
    _t4 = fclose(_t3);
    return _t4;
}

bool io_is_valid(struct File** _arg0) {
    int64_t _t5;
    struct File* _t1;
    struct File** _t0;
    void* _t3;
    void* _t4;
    void** _t2;
    
    _t0 = _arg0;
    _t1 = *_t0;
    _t2 = &_t1->handle;
    _t3 = *_t2;
    _t4 = (void*)0LL;
    _t5 = _t3 != _t4;
    return _t5;
}

