/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct JNIEnv {
    void* ptr;
};

struct JavaVM {
    void* ptr;
};

struct JavaVMInitArgs {
    int32_t version;
    int32_t nOptions;
    void* options;
    uint8_t ignoreUnrecognized;
};

int32_t jni_version_1_1(void);
int32_t jni_version_1_2(void);
int32_t jni_version_1_4(void);
int32_t jni_version_1_6(void);
int32_t jni_version_1_8(void);
int32_t jni_version_9(void);
int32_t jni_version_10(void);
int32_t jni_ok(void);
int32_t jni_err(void);
int32_t jni_edetached(void);
int32_t jni_eversion(void);
int32_t jni_enomem(void);
int32_t jni_eexist(void);
int32_t jni_einval(void);
int32_t main(void);

int32_t jni_version_1_1(void) {
    int32_t _t0;
    
    _t0 = (int32_t)65537LL;
    return _t0;
}

int32_t jni_version_1_2(void) {
    int32_t _t0;
    
    _t0 = (int32_t)65538LL;
    return _t0;
}

int32_t jni_version_1_4(void) {
    int32_t _t0;
    
    _t0 = (int32_t)65540LL;
    return _t0;
}

int32_t jni_version_1_6(void) {
    int32_t _t0;
    
    _t0 = (int32_t)65542LL;
    return _t0;
}

int32_t jni_version_1_8(void) {
    int32_t _t0;
    
    _t0 = (int32_t)65544LL;
    return _t0;
}

int32_t jni_version_9(void) {
    int32_t _t0;
    
    _t0 = (int32_t)589824LL;
    return _t0;
}

int32_t jni_version_10(void) {
    int32_t _t0;
    
    _t0 = (int32_t)655360LL;
    return _t0;
}

int32_t jni_ok(void) {
    int32_t _t0;
    
    _t0 = (int32_t)0LL;
    return _t0;
}

int32_t jni_err(void) {
    int32_t _t1;
    int64_t _t0;
    
    _t0 = -1LL;
    _t1 = (int32_t)_t0;
    return _t1;
}

int32_t jni_edetached(void) {
    int32_t _t1;
    int64_t _t0;
    
    _t0 = -2LL;
    _t1 = (int32_t)_t0;
    return _t1;
}

int32_t jni_eversion(void) {
    int32_t _t1;
    int64_t _t0;
    
    _t0 = -3LL;
    _t1 = (int32_t)_t0;
    return _t1;
}

int32_t jni_enomem(void) {
    int32_t _t1;
    int64_t _t0;
    
    _t0 = -4LL;
    _t1 = (int32_t)_t0;
    return _t1;
}

int32_t jni_eexist(void) {
    int32_t _t1;
    int64_t _t0;
    
    _t0 = -5LL;
    _t1 = (int32_t)_t0;
    return _t1;
}

int32_t jni_einval(void) {
    int32_t _t1;
    int64_t _t0;
    
    _t0 = -6LL;
    _t1 = (int32_t)_t0;
    return _t1;
}

int32_t main(void) {
    int32_t _t6;
    int64_t _t1;
    int64_t _t3;
    int64_t _t5;
    uint8_t* _t0;
    uint8_t* _t2;
    uint8_t* _t4;
    
    _t0 = (uint8_t*)"JNI Module for AetherLang";
    puts(_t0);
    _t2 = (uint8_t*)"Version: 1.1, 1.2, 1.4, 1.6, 1.8, 9, 10";
    puts(_t2);
    _t4 = (uint8_t*)"Functions: JNI_CreateJavaVM, JNI_GetDefaultJavaVMInitArgs";
    puts(_t4);
    _t6 = (int32_t)0LL;
    return _t6;
}

