/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
/* Enum Definitions (Tagged Unions) */
uint64_t string_len(uint8_t*);
int32_t string_compare(uint8_t*, uint8_t*);
bool string_equals(uint8_t*, uint8_t*);
uint8_t* string_alloc(uint64_t);
void string_dealloc(uint8_t*);
uint8_t* string_copy(uint8_t*, uint8_t*);
uint8_t* string_concat(uint8_t*, uint8_t*);
uint8_t* string_dup(uint8_t*);

uint64_t string_len(uint8_t* _arg0) {
    uint64_t _t1;
    uint8_t* _t0;
    
    _t0 = _arg0;
    _t1 = strlen(_t0);
    return _t1;
}

int32_t string_compare(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t2;
    uint8_t* _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = strcmp(_t0, _t1);
    return _t2;
}

bool string_equals(uint8_t* _arg0, uint8_t* _arg1) {
    int32_t _t2;
    int32_t _t3;
    int64_t _t4;
    uint8_t* _t0;
    uint8_t* _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = strcmp(_t0, _t1);
    _t3 = (int32_t)0LL;
    _t4 = _t2 == _t3;
    return _t4;
}

uint8_t* string_alloc(uint64_t _arg0) {
    int64_t _t1;
    uint64_t _t0;
    uint8_t* _t3;
    void* _t2;
    
    _t0 = _arg0;
    _t1 = (int64_t)_t0;
    _t2 = malloc(_t1);
    _t3 = (uint8_t*)_t2;
    return _t3;
}

void string_dealloc(uint8_t* _arg0) {
    uint8_t* _t0;
    void* _t1;
    
    _t0 = _arg0;
    _t1 = (void*)_t0;
    free(_t1);
    return;
}

uint8_t* string_copy(uint8_t* _arg0, uint8_t* _arg1) {
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = strcpy(_t0, _t1);
    return _t2;
}

uint8_t* string_concat(uint8_t* _arg0, uint8_t* _arg1) {
    uint8_t* _t0;
    uint8_t* _t1;
    uint8_t* _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = strcat(_t0, _t1);
    return _t2;
}

uint8_t* string_dup(uint8_t* _arg0) {
    int64_t _t3;
    int64_t _t4;
    int64_t _t5;
    uint64_t _t1;
    uint64_t _t2;
    uint8_t* _t0;
    uint8_t* _t7;
    uint8_t* _t8;
    uint8_t* _t9;
    void* _t6;
    
    _t0 = _arg0;
    _t1 = strlen(_t0);
    _t2 = (uint64_t)1LL;
    _t3 = _t1 + _t2;
    _t4 = _t3;
    _t5 = (int64_t)_t4;
    _t6 = malloc(_t5);
    _t7 = (uint8_t*)_t6;
    _t8 = _t7;
    _t9 = strcpy(_t8, _t0);
    return _t8;
}

