/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <immintrin.h>  /* SSE/AVX */

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct Tensor1D {
    float* data;
    int32_t size;
};

struct Tensor2D {
    float* data;
    int32_t rows;
    int32_t cols;
};

struct Tensor3D {
    float* data;
    int32_t depth;
    int32_t rows;
    int32_t cols;
};

struct Tensor4D {
    float* data;
    int32_t batch;
    int32_t channels;
    int32_t height;
    int32_t width;
};

struct Tensor1D* tensor1d_new(int32_t);
struct Tensor2D* tensor2d_new(int32_t, int32_t);
struct Tensor3D* tensor3d_new(int32_t, int32_t, int32_t);
float tensor1d_get(struct Tensor1D**, int32_t);
void tensor1d_set(struct Tensor1D**, int32_t, float);
float tensor2d_get(struct Tensor2D**, int32_t, int32_t);
void tensor2d_set(struct Tensor2D**, int32_t, int32_t, float);
void tensor1d_add(struct Tensor1D**, struct Tensor1D**, struct Tensor1D**);
void tensor1d_mul(struct Tensor1D**, struct Tensor1D**, struct Tensor1D**);
float tensor1d_dot(struct Tensor1D**, struct Tensor1D**);
void tensor1d_scale(struct Tensor1D**, float, struct Tensor1D**);
void tensor2d_matvec(struct Tensor2D**, struct Tensor1D**, struct Tensor1D**);
void tensor2d_matmul(struct Tensor2D**, struct Tensor2D**, struct Tensor2D**);
float relu(float);
float sigmoid(float);
float tanh_act(float);
void tensor1d_relu(struct Tensor1D**, struct Tensor1D**);
void tensor1d_sigmoid(struct Tensor1D**, struct Tensor1D**);
void tensor1d_fill(struct Tensor1D**, float);
void tensor2d_fill(struct Tensor2D**, float);
float tensor1d_sum(struct Tensor1D**);

struct Tensor1D* tensor1d_new(int32_t _arg0) {
    float* _t6;
    float* _t7;
    float** _t9;
    int32_t _t0;
    int32_t _t1;
    int32_t* _t10;
    int64_t _t2;
    int64_t _t3;
    int64_t _t4;
    int64_t _t5;
    struct Tensor1D* _t8;
    
    _t0 = _arg0;
    _t1 = (int32_t)4LL;
    _t2 = _t0 * _t1;
    _t3 = _t2;
    _t4 = (int64_t)_t3;
    malloc(_t4);
    _t6 = (float*)_t5;
    _t7 = _t6;
    struct Tensor1D _alloca__t8;
    _t8 = &_alloca__t8;
    _t9 = &_t8->data;
    *_t9 = _t7;
    _t10 = &_t8->size;
    *_t10 = _t0;
    return _t8;
}

struct Tensor2D* tensor2d_new(int32_t _arg0, int32_t _arg1) {
    float* _t8;
    float* _t9;
    float** _t11;
    int32_t _t0;
    int32_t _t1;
    int32_t _t3;
    int32_t* _t12;
    int32_t* _t13;
    int64_t _t2;
    int64_t _t4;
    int64_t _t5;
    int64_t _t6;
    int64_t _t7;
    struct Tensor2D* _t10;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _t0 * _t1;
    _t3 = (int32_t)4LL;
    _t4 = _t2 * _t3;
    _t5 = _t4;
    _t6 = (int64_t)_t5;
    malloc(_t6);
    _t8 = (float*)_t7;
    _t9 = _t8;
    struct Tensor2D _alloca__t10;
    _t10 = &_alloca__t10;
    _t11 = &_t10->data;
    *_t11 = _t9;
    _t12 = &_t10->rows;
    *_t12 = _t0;
    _t13 = &_t10->cols;
    *_t13 = _t1;
    return _t10;
}

struct Tensor3D* tensor3d_new(int32_t _arg0, int32_t _arg1, int32_t _arg2) {
    float* _t10;
    float* _t11;
    float** _t13;
    int32_t _t0;
    int32_t _t1;
    int32_t _t2;
    int32_t _t5;
    int32_t* _t14;
    int32_t* _t15;
    int32_t* _t16;
    int64_t _t3;
    int64_t _t4;
    int64_t _t6;
    int64_t _t7;
    int64_t _t8;
    int64_t _t9;
    struct Tensor3D* _t12;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = _t0 * _t1;
    _t4 = _t3 * _t2;
    _t5 = (int32_t)4LL;
    _t6 = _t4 * _t5;
    _t7 = _t6;
    _t8 = (int64_t)_t7;
    malloc(_t8);
    _t10 = (float*)_t9;
    _t11 = _t10;
    struct Tensor3D _alloca__t12;
    _t12 = &_alloca__t12;
    _t13 = &_t12->data;
    *_t13 = _t11;
    _t14 = &_t12->depth;
    *_t14 = _t0;
    _t15 = &_t12->rows;
    *_t15 = _t1;
    _t16 = &_t12->cols;
    *_t16 = _t2;
    return _t12;
}

float tensor1d_get(struct Tensor1D** _arg0, int32_t _arg1) {
    float _t6;
    float* _t4;
    float* _t5;
    float** _t3;
    int32_t _t1;
    struct Tensor1D* _t2;
    struct Tensor1D** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t0;
    _t3 = &_t2->data;
    _t4 = *_t3;
    _t5 = &_t4[_t1];
    _t6 = *_t5;
    return _t6;
}

void tensor1d_set(struct Tensor1D** _arg0, int32_t _arg1, float _arg2) {
    float _t2;
    float _t7;
    float* _t10;
    float* _t11;
    float* _t5;
    float* _t6;
    float** _t4;
    float** _t9;
    int32_t _t1;
    struct Tensor1D* _t3;
    struct Tensor1D* _t8;
    struct Tensor1D** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = *_t0;
    _t4 = &_t3->data;
    _t5 = *_t4;
    _t6 = &_t5[_t1];
    _t7 = *_t6;
    _t8 = *_t0;
    _t9 = &_t8->data;
    _t10 = *_t9;
    _t11 = &_t10[_t1];
    *_t11 = _t2;
    return;
}

float tensor2d_get(struct Tensor2D** _arg0, int32_t _arg1, int32_t _arg2) {
    float _t13;
    float* _t11;
    float* _t12;
    float** _t10;
    int32_t _t1;
    int32_t _t2;
    int32_t _t5;
    int32_t* _t4;
    int64_t _t6;
    int64_t _t7;
    int64_t _t8;
    struct Tensor2D* _t3;
    struct Tensor2D* _t9;
    struct Tensor2D** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = *_t0;
    _t4 = &_t3->cols;
    _t5 = *_t4;
    _t6 = _t1 * _t5;
    _t7 = _t6 + _t2;
    _t8 = _t7;
    _t9 = *_t0;
    _t10 = &_t9->data;
    _t11 = *_t10;
    _t12 = &_t11[_t8];
    _t13 = *_t12;
    return _t13;
}

void tensor2d_set(struct Tensor2D** _arg0, int32_t _arg1, int32_t _arg2, float _arg3) {
    float _t14;
    float _t3;
    float* _t12;
    float* _t13;
    float* _t17;
    float* _t18;
    float** _t11;
    float** _t16;
    int32_t _t1;
    int32_t _t2;
    int32_t _t6;
    int32_t* _t5;
    int64_t _t7;
    int64_t _t8;
    int64_t _t9;
    struct Tensor2D* _t10;
    struct Tensor2D* _t15;
    struct Tensor2D* _t4;
    struct Tensor2D** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = _arg3;
    _t4 = *_t0;
    _t5 = &_t4->cols;
    _t6 = *_t5;
    _t7 = _t1 * _t6;
    _t8 = _t7 + _t2;
    _t9 = _t8;
    _t10 = *_t0;
    _t11 = &_t10->data;
    _t12 = *_t11;
    _t13 = &_t12[_t9];
    _t14 = *_t13;
    _t15 = *_t0;
    _t16 = &_t15->data;
    _t17 = *_t16;
    _t18 = &_t17[_t9];
    *_t18 = _t3;
    return;
}

void tensor1d_add(struct Tensor1D** _arg0, struct Tensor1D** _arg1, struct Tensor1D** _arg2) {
    int64_t _t3;
    struct Tensor1D** _t0;
    struct Tensor1D** _t1;
    struct Tensor1D** _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = 0LL;
    return;
}

void tensor1d_mul(struct Tensor1D** _arg0, struct Tensor1D** _arg1, struct Tensor1D** _arg2) {
    int64_t _t3;
    struct Tensor1D** _t0;
    struct Tensor1D** _t1;
    struct Tensor1D** _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = 0LL;
    return;
}

float tensor1d_dot(struct Tensor1D** _arg0, struct Tensor1D** _arg1) {
    int64_t _t2;
    int64_t _t3;
    struct Tensor1D** _t0;
    struct Tensor1D** _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = 0;
    _t3 = 0LL;
    return _t2;
}

void tensor1d_scale(struct Tensor1D** _arg0, float _arg1, struct Tensor1D** _arg2) {
    float _t1;
    int64_t _t3;
    struct Tensor1D** _t0;
    struct Tensor1D** _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = 0LL;
    return;
}

void tensor2d_matvec(struct Tensor2D** _arg0, struct Tensor1D** _arg1, struct Tensor1D** _arg2) {
    int64_t _t3;
    struct Tensor1D** _t1;
    struct Tensor1D** _t2;
    struct Tensor2D** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = 0LL;
    return;
}

void tensor2d_matmul(struct Tensor2D** _arg0, struct Tensor2D** _arg1, struct Tensor2D** _arg2) {
    int64_t _t3;
    struct Tensor2D** _t0;
    struct Tensor2D** _t1;
    struct Tensor2D** _t2;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _arg2;
    _t3 = 0LL;
    return;
}

float relu(float _arg0) {
    float _t0;
    int64_t _t1;
    
    _t0 = _arg0;
    _t1 = _t0 > 0;
    if (_t1) goto L_then; else goto L_else;
L_then:
    return _t0;
L_else:
    goto L_merge;
L_merge:
    return 0;
}

float sigmoid(float _arg0) {
    float _t0;
    float _t1;
    int64_t _t2;
    int64_t _t3;
    int64_t _t4;
    
    _t0 = _arg0;
    _t1 = -_t0;
    exp(_t1);
    _t3 = 1 + _t2;
    _t4 = 1 / _t3;
    return _t4;
}

float tanh_act(float _arg0) {
    float _t0;
    int64_t _t1;
    int64_t _t2;
    int64_t _t3;
    int64_t _t4;
    int64_t _t5;
    int64_t _t6;
    
    _t0 = _arg0;
    _t1 = 2 * _t0;
    exp(_t1);
    _t3 = _t2;
    _t4 = _t3 - 1;
    _t5 = _t3 + 1;
    _t6 = _t4 / _t5;
    return _t6;
}

void tensor1d_relu(struct Tensor1D** _arg0, struct Tensor1D** _arg1) {
    int64_t _t2;
    struct Tensor1D** _t0;
    struct Tensor1D** _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = 0LL;
    return;
}

void tensor1d_sigmoid(struct Tensor1D** _arg0, struct Tensor1D** _arg1) {
    int64_t _t2;
    struct Tensor1D** _t0;
    struct Tensor1D** _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = 0LL;
    return;
}

void tensor1d_fill(struct Tensor1D** _arg0, float _arg1) {
    float _t1;
    int64_t _t2;
    struct Tensor1D** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = 0LL;
    return;
}

void tensor2d_fill(struct Tensor2D** _arg0, float _arg1) {
    float _t1;
    int32_t _t4;
    int32_t _t7;
    int32_t* _t3;
    int32_t* _t6;
    int64_t _t10;
    int64_t _t8;
    int64_t _t9;
    struct Tensor2D* _t2;
    struct Tensor2D* _t5;
    struct Tensor2D** _t0;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = *_t0;
    _t3 = &_t2->rows;
    _t4 = *_t3;
    _t5 = *_t0;
    _t6 = &_t5->cols;
    _t7 = *_t6;
    _t8 = _t4 * _t7;
    _t9 = _t8;
    _t10 = 0LL;
    return;
}

float tensor1d_sum(struct Tensor1D** _arg0) {
    int64_t _t1;
    int64_t _t2;
    struct Tensor1D** _t0;
    
    _t0 = _arg0;
    _t1 = 0;
    _t2 = 0LL;
    return _t1;
}

