/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct Point {
    struct i32 x;
    struct i32 y;
};

struct i32 divide(struct i32, struct i32);
void log_message(struct str);
struct i32 binary_search(struct i32, struct i32);
void process_shared(void);
struct i32 consume(struct String);
void main(void);

struct i32 divide(struct i32 _arg0, struct i32 _arg1) {
    int64_t _t2;
    struct i32 _t0;
    struct i32 _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    _t2 = _t0 / _t1;
    return;
}

void log_message(struct str _arg0) {
    int64_t _t1;
    struct str _t0;
    
    _t0 = _arg0;
    aether_println(_t0);
    return;
}

struct i32 binary_search(struct i32 _arg0, struct i32 _arg1) {
    struct i32 _t0;
    struct i32 _t1;
    
    _t0 = _arg0;
    _t1 = _arg1;
    return 0LL;
}

void process_shared(void _arg0) {
    void _t0;
    
    _t0 = _arg0;
    return;
}

struct i32 consume(struct String _arg0) {
    struct String _t0;
    
    _t0 = _arg0;
    return 42LL;
}

void main(void) {
    int64_t _t0;
    int64_t _t1;
    int64_t _t4;
    struct i32 _t2;
    struct i32 _t3;
    
    _t0 = 10LL;
    _t1 = 2LL;
    _t2 = divide(_t0, _t1);
    _t3 = _t2;
    aether_println(_t3);
    return;
}

