/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

int64_t fib(int64_t);
void main(void);

int64_t fib(int64_t _arg0) {
    int64_t _t0;
    int64_t _t1;
    int64_t _t2;
    int64_t _t3;
    int64_t _t4;
    int64_t _t5;
    int64_t _t6;
    int64_t _t7;
    
    _t0 = _arg0;
    _t1 = _t0 <= 1LL;
    if (_t1) goto L_then; else goto L_else;
L_then:
    return _t0;
L_else:
    goto L_merge;
L_merge:
    _t2 = ((void)0);
    _t3 = _t0 - 1LL;
    _t4 = fib(_t3);
    _t5 = _t0 - 2LL;
    _t6 = fib(_t5);
    _t7 = _t4 + _t6;
    return _t7;
}

void main(void) {
    int64_t _t0;
    int64_t _t10;
    int64_t _t11;
    int64_t _t12;
    int64_t _t13;
    int64_t _t14;
    int64_t _t1;
    int64_t _t2;
    int64_t _t3;
    int64_t _t4;
    int64_t _t5;
    int64_t _t6;
    int64_t _t7;
    int64_t _t8;
    int64_t _t9;
    
    aether_println("Fibonacci sequence:");
    _t1 = fib(0LL);
    aether_println_i64(_t1);
    _t3 = fib(1LL);
    aether_println_i64(_t3);
    _t5 = fib(2LL);
    aether_println_i64(_t5);
    _t7 = fib(3LL);
    aether_println_i64(_t7);
    _t9 = fib(4LL);
    aether_println_i64(_t9);
    _t11 = fib(5LL);
    aether_println_i64(_t11);
    _t13 = fib(10LL);
    aether_println_i64(_t13);
    return;
}

