/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct Box {
    struct T inner;
};

void main(void);

void main(void) {
    int64_t _t3;
    int64_t _t4;
    struct Box* _t0;
    struct Box* _t2;
    struct T* _t1;
    
    struct Box _alloca__t0;
    _t0 = &_alloca__t0;
    _t1 = &_t0->inner;
    *_t1 = 42LL;
    _t2 = _t0;
    _t3 = Option_Some(100LL);
    _t4 = _t3;
    return;
}

