/* Generated by AetherLang C Backend */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

/* AetherLang Runtime */
static void aether_print(const char* s) { printf("%s", s); }
static void aether_println(const char* s) { printf("%s\n", s); }
static void aether_print_i64(int64_t n) { printf("%lld", (long long)n); }
static void aether_println_i64(int64_t n) { printf("%lld\n", (long long)n); }
static void aether_assert(bool c) { if(!c) { fprintf(stderr, "Assertion failed\n"); exit(1); } }

/* Struct Definitions */
struct GDTEntry __attribute__((packed)) {
    int64_t limit_low;
    int64_t base_low;
    int64_t base_middle;
    int64_t access;
    int64_t granularity;
    int64_t base_high;
};

struct GDTPointer {
    int64_t limit;
    int64_t base;
};

struct NestedStruct {
    struct GDTEntry entry;
    int64_t count;
};

void test_struct_creation(void);
void test_pointer_field(void);
void test_nested_struct(void);
void main(void);

void test_struct_creation(void) {
    int64_t _t10;
    int64_t _t12;
    int64_t _t13;
    int64_t _t9;
    int64_t* _t11;
    int64_t* _t1;
    int64_t* _t2;
    int64_t* _t3;
    int64_t* _t4;
    int64_t* _t5;
    int64_t* _t6;
    int64_t* _t8;
    struct GDTEntry* _t0;
    struct GDTEntry* _t7;
    
    struct GDTEntry _alloca__t0;
    _t0 = &_alloca__t0;
    _t1 = &_t0->limit_low;
    *_t1 = 65535LL;
    _t2 = &_t0->base_low;
    *_t2 = 0LL;
    _t3 = &_t0->base_middle;
    *_t3 = 0LL;
    _t4 = &_t0->access;
    *_t4 = 154LL;
    _t5 = &_t0->granularity;
    *_t5 = 207LL;
    _t6 = &_t0->base_high;
    *_t6 = 0LL;
    _t7 = _t0;
    _t8 = &_t7->limit_low;
    _t9 = *_t8;
    aether_println_i64(_t9);
    _t11 = &_t7->access;
    _t12 = *_t11;
    aether_println_i64(_t12);
    return;
}

void test_pointer_field(void) {
    int64_t _t10;
    int64_t _t14;
    int64_t _t15;
    int64_t _t17;
    int64_t _t18;
    int64_t* _t11;
    int64_t* _t13;
    int64_t* _t16;
    int64_t* _t1;
    int64_t* _t2;
    int64_t* _t3;
    int64_t* _t4;
    int64_t* _t5;
    int64_t* _t6;
    int64_t* _t9;
    struct GDTEntry* _t0;
    struct GDTEntry* _t7;
    struct GDTPointer* _t12;
    struct GDTPointer* _t8;
    
    struct GDTEntry _alloca__t0;
    _t0 = &_alloca__t0;
    _t1 = &_t0->limit_low;
    *_t1 = 4660LL;
    _t2 = &_t0->base_low;
    *_t2 = 22136LL;
    _t3 = &_t0->base_middle;
    *_t3 = 171LL;
    _t4 = &_t0->access;
    *_t4 = 205LL;
    _t5 = &_t0->granularity;
    *_t5 = 239LL;
    _t6 = &_t0->base_high;
    *_t6 = 0LL;
    _t7 = _t0;
    struct GDTPointer _alloca__t8;
    _t8 = &_alloca__t8;
    _t9 = &_t8->limit;
    *_t9 = 47LL;
    _t10 = (int64_t)753664LL;
    _t11 = &_t8->base;
    *_t11 = _t10;
    _t12 = _t8;
    _t13 = &_t12->limit;
    _t14 = *_t13;
    aether_println_i64(_t14);
    _t16 = &_t12->base;
    _t17 = *_t16;
    aether_println_i64(_t17);
    return;
}

void test_nested_struct(void) {
    int64_t _t14;
    int64_t _t15;
    int64_t _t17;
    int64_t _t18;
    int64_t* _t10;
    int64_t* _t13;
    int64_t* _t16;
    int64_t* _t1;
    int64_t* _t2;
    int64_t* _t3;
    int64_t* _t4;
    int64_t* _t5;
    int64_t* _t6;
    struct GDTEntry* _t0;
    struct GDTEntry* _t12;
    struct GDTEntry* _t7;
    struct GDTEntry* _t9;
    struct NestedStruct* _t11;
    struct NestedStruct* _t8;
    
    struct GDTEntry _alloca__t0;
    _t0 = &_alloca__t0;
    _t1 = &_t0->limit_low;
    *_t1 = 43981LL;
    _t2 = &_t0->base_low;
    *_t2 = 4660LL;
    _t3 = &_t0->base_middle;
    *_t3 = 86LL;
    _t4 = &_t0->access;
    *_t4 = 120LL;
    _t5 = &_t0->granularity;
    *_t5 = 154LL;
    _t6 = &_t0->base_high;
    *_t6 = 188LL;
    _t7 = _t0;
    struct NestedStruct _alloca__t8;
    _t8 = &_alloca__t8;
    _t9 = &_t8->entry;
    *_t9 = *_t7;
    _t10 = &_t8->count;
    *_t10 = 42LL;
    _t11 = _t8;
    _t12 = &_t11->entry;
    _t13 = &_t12->limit_low;
    _t14 = *_t13;
    aether_println_i64(_t14);
    _t16 = &_t11->count;
    _t17 = *_t16;
    aether_println_i64(_t17);
    return;
}

void main(void) {
    
    test_struct_creation();
    test_pointer_field();
    test_nested_struct();
    return;
}

